<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\Category;
use App\Models\ProductImage;

/**
 * LANCEMENT (sans effacer les données existantes) :
 *   php artisan db:seed --class=AdditionalProductsSeeder
 *
 * ⚠️  Ce seeder AJOUTE des produits sans effacer les existants.
 *     Il utilise les catégories déjà créées par ProductSeeder.
 */
class AdditionalProductsSeeder extends Seeder
{
    public function run(): void
    {
        $catIds = Category::pluck('id', 'slug');

        if ($catIds->isEmpty()) {
            $this->command->error('❌ Aucune catégorie trouvée. Lance d\'abord ProductSeeder.');
            return;
        }

        $make = function (array $d) use ($catIds) {
            $images = $d['images'] ?? [];
            $cat    = $d['cat'];
            unset($d['images'], $d['cat']);

            // Évite les doublons de slug
            if (Product::where('slug', $d['slug'])->exists()) {
                return;
            }

            $product = Product::create(array_merge([
                'category_id'      => $catIds[$cat] ?? null,
                'sale_price'       => null,
                'is_featured'      => false,
                'is_new'           => false,
                'assembly_required'=> false,
                'stock'            => rand(3, 20),
                'year'             => '2025',
            ], $d));

            foreach ($images as $i => $url) {
                ProductImage::create([
                    'product_id' => $product->id,
                    'image_path' => $url,
                    'is_primary' => $i === 0,
                    'sort_order' => $i,
                ]);
            }
        };

        // ═══════════════════════════════════════════════
        // IMAGES UNSPLASH PAR CATÉGORIE
        // ═══════════════════════════════════════════════
        $imgVTT      = 'https://images.unsplash.com/photo-1544191696-102dbdaeeaa0?w=900&q=85';
        $imgVTT2     = 'https://images.unsplash.com/photo-1576435728678-68d0fbf94946?w=900&q=85';
        $imgVTT3     = 'https://images.unsplash.com/photo-1553764854-53ac4f1e175b?w=900&q=85';
        $imgRoute    = 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=900&q=85';
        $imgRoute2   = 'https://images.unsplash.com/photo-1526307616774-60d0098f7642?w=900&q=85';
        $imgRoute3   = 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=900&q=85';
        $imgGravel   = 'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=900&q=85';
        $imgVille    = 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=900&q=85';
        $imgElec     = 'https://images.unsplash.com/photo-1559348349-86f1f65817fe?w=900&q=85';
        $imgElec2    = 'https://images.unsplash.com/photo-1571333250630-f0230c320b6d?w=900&q=85';
        $imgEnfant   = 'https://images.unsplash.com/photo-1503455637927-730bce8583c0?w=900&q=85';
        $imgBMX      = 'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=900&q=85';
        $imgRecon    = 'https://images.unsplash.com/photo-1511994298241-608e28f14fde?w=900&q=85';

        // ═══════════════════════════════════════════════
        // ██ VTT — 25 produits supplémentaires
        // ═══════════════════════════════════════════════

        $make(['cat'=>'vtt','brand'=>'Trek','name'=>'Trek Roscoe 8 27.5"','name_de'=>'Trek Roscoe 8 27.5"','slug'=>'trek-roscoe-8-27-5','description'=>'Le Roscoe 8 est un VTT hardtail fat-tire taillé pour les terrains techniques. Ses pneus 27,5+ offrent une adhérence exceptionnelle sur tous les types de sols, du gravier à la boue.','description_de'=>'Das Roscoe 8 ist ein Hardtail-MTB mit Fat-Tires für technisches Gelände. Die 27,5+ Reifen bieten außergewöhnlichen Grip auf allen Bodenarten.','price'=>1499.00,'sale_price'=>1199.00,'is_new'=>false,'is_featured'=>false,'bike_type'=>'Hardtail Fat','wheel_size'=>'27.5"+','frame_material'=>'Aluminium Alpha Gold','number_of_speeds'=>'12 vitesses Shimano Deore','suspension_type'=>'RockShox Judy 120 mm','brake_style'=>'Hydraulique Shimano MT200','weight'=>'14,8 kg','warranty_type'=>'Garantie Trek à vie cadre','colors'=>'Noir,Bleu','sizes'=>'S,M,L,XL','images'=>[$imgVTT,$imgVTT2]]);

        $make(['cat'=>'vtt','brand'=>'Trek','name'=>'Trek Slash 9.8 GX AXS 29"','name_de'=>'Trek Slash 9.8 GX AXS 29"','slug'=>'trek-slash-9-8-gx-axs','description'=>'Le Trek Slash est le VTT enduro de référence. Avec 160 mm de débattement et un groupe SRAM GX AXS électronique, il domine les descentes les plus techniques tout en restant efficace en montée.','description_de'=>'Das Trek Slash ist das Referenz-Enduro-MTB. Mit 160 mm Federweg und elektronischer SRAM GX AXS Gruppe dominiert es die technischsten Abfahrten.','price'=>5999.00,'sale_price'=>null,'is_new'=>true,'is_featured'=>true,'bike_type'=>'Enduro Tout-suspendu','wheel_size'=>'29"','frame_material'=>'Carbone OCLV 600','number_of_speeds'=>'12 vitesses SRAM GX AXS','suspension_type'=>'Fox 36 Factory 160 mm / Fox Float X2 160 mm','brake_style'=>'Hydraulique SRAM Code RSC','weight'=>'13,2 kg','warranty_type'=>'Garantie Trek à vie cadre carbone','colors'=>'Noir mat,Gris','sizes'=>'S,M,L,XL','images'=>[$imgVTT2,$imgVTT]]);

        $make(['cat'=>'vtt','brand'=>'Specialized','name'=>'Specialized Epic World Cup Pro 29"','name_de'=>'Specialized Epic World Cup Pro 29"','slug'=>'specialized-epic-world-cup-pro-29','description'=>'Le vélo sur lequel les champions du monde gagnent leurs médailles. Cadre carbone FACT 12m ultra-léger, suspension FSR optimisée pour le XC, groupe SRAM XX AXS. La perfection en cross-country.','description_de'=>'Das Fahrrad, auf dem Weltmeister ihre Medaillen gewinnen. FACT 12m Ultraleicht-Carbon, FSR-Federung für XC, SRAM XX AXS Gruppe. Perfektion im Cross-Country.','price'=>8999.00,'sale_price'=>null,'is_new'=>true,'is_featured'=>true,'bike_type'=>'XC Race','wheel_size'=>'29"','frame_material'=>'Carbone FACT 12m','number_of_speeds'=>'12 vitesses SRAM XX AXS','suspension_type'=>'Brain FSR 100 mm','brake_style'=>'Hydraulique SRAM Level Ultimate','weight'=>'9,1 kg','warranty_type'=>'Garantie Specialized 5 ans','colors'=>'Blanc,Noir','sizes'=>'S,M,L,XL','images'=>[$imgVTT3,$imgVTT]]);

        $make(['cat'=>'vtt','brand'=>'Specialized','name'=>'Specialized Enduro Expert 29"','name_de'=>'Specialized Enduro Expert 29"','slug'=>'specialized-enduro-expert-29','description'=>'Le Specialized Enduro Expert est le vélo de descente ultime pour les amateurs de sensations. Avec 170 mm de débattement et une géométrie race, il vous permettra de dévaler les pentes les plus raides.','description_de'=>'Das Specialized Enduro Expert ist das ultimative Downhill-Bike für Adrenalin-Junkies. Mit 170 mm Federweg und Race-Geometrie bewältigt es die steilsten Hänge.','price'=>4499.00,'sale_price'=>3899.00,'is_new'=>false,'is_featured'=>true,'bike_type'=>'Enduro','wheel_size'=>'29"','frame_material'=>'Aluminium M5','number_of_speeds'=>'12 vitesses SRAM X01 Eagle','suspension_type'=>'Fox 38 Float 170 mm / Fox Float X2 170 mm','brake_style'=>'Hydraulique SRAM Code R 4 pistons','weight'=>'14,6 kg','warranty_type'=>'Garantie Specialized 5 ans','colors'=>'Bleu,Noir','sizes'=>'S,M,L,XL','images'=>[$imgVTT,$imgVTT3]]);

        $make(['cat'=>'vtt','brand'=>'Giant','name'=>'Giant Trance X Advanced Pro 29 1','name_de'=>'Giant Trance X Advanced Pro 29 1','slug'=>'giant-trance-x-advanced-pro-29-1','description'=>'Le Giant Trance X Advanced Pro 29 combine légèreté carbone et polyvalence trail. Sa géométrie Maestro et son amortisseur FOX garantissent un contrôle parfait sur tous les types de sentiers.','description_de'=>'Das Giant Trance X Advanced Pro 29 kombiniert Carbon-Leichtigkeit mit Trail-Vielseitigkeit. Maestro-Geometrie und FOX-Dämpfer garantieren perfekte Kontrolle.','price'=>5299.00,'sale_price'=>null,'is_new'=>true,'is_featured'=>false,'bike_type'=>'Trail Tout-suspendu','wheel_size'=>'29"','frame_material'=>'Carbone Advanced Grade Composite','number_of_speeds'=>'12 vitesses SRAM X01 Eagle','suspension_type'=>'Fox 36 Float 140 mm / Maestro 140 mm','brake_style'=>'Hydraulique SRAM Code R','weight'=>'12,9 kg','warranty_type'=>'Garantie Giant 5 ans cadre','colors'=>'Noir,Vert','sizes'=>'S,M,L,XL','images'=>[$imgVTT2,$imgVTT3]]);

        $make(['cat'=>'vtt','brand'=>'Giant','name'=>'Giant Talon 1 29" 2025','name_de'=>'Giant Talon 1 29" 2025','slug'=>'giant-talon-1-29-2025','description'=>'Le Giant Talon 1 est le hardtail parfait pour découvrir le VTT. Léger, maniable et robuste, il convient aux débutants comme aux riders intermédiaires qui veulent progresser sur les sentiers.','description_de'=>'Das Giant Talon 1 ist das perfekte Hardtail für den Einstieg ins MTB. Leicht, wendig und robust, geeignet für Anfänger und Fortgeschrittene.','price'=>899.00,'sale_price'=>749.00,'is_new'=>false,'is_featured'=>false,'bike_type'=>'Hardtail VTT','wheel_size'=>'29"','frame_material'=>'Aluminium ALUXX','number_of_speeds'=>'21 vitesses Shimano Acera','suspension_type'=>'SR Suntour XCT 100 mm','brake_style'=>'Disque mécanique Tektro','weight'=>'13,9 kg','warranty_type'=>'Garantie Giant 2 ans','colors'=>'Noir,Rouge,Bleu','sizes'=>'S,M,L,XL','images'=>[$imgVTT,$imgVTT2]]);

        $make(['cat'=>'vtt','brand'=>'Santa Cruz','name'=>'Santa Cruz Hightower CC X01 AXS','name_de'=>'Santa Cruz Hightower CC X01 AXS','slug'=>'santa-cruz-hightower-cc-x01-axs','description'=>'Le Santa Cruz Hightower CC est le vélo de trail carbone par excellence. Sa géométrie progressive, son débattement de 135 mm et son groupe SRAM X01 AXS le placent au sommet des vélos trail haut de gamme.','description_de'=>'Das Santa Cruz Hightower CC ist das ultimative Carbon-Trail-Bike. Progressive Geometrie, 135 mm Federweg und SRAM X01 AXS platzieren es an die Spitze.','price'=>7499.00,'sale_price'=>null,'is_new'=>true,'is_featured'=>true,'bike_type'=>'Trail Carbone','wheel_size'=>'29"','frame_material'=>'Carbone CC (haut module)','number_of_speeds'=>'12 vitesses SRAM X01 AXS','suspension_type'=>'Fox 36 Factory 140 mm / Fox Float DPS 135 mm','brake_style'=>'Hydraulique SRAM Code RSC','weight'=>'12,4 kg','warranty_type'=>'Garantie Santa Cruz à vie cadre','colors'=>'Bleu,Noir','sizes'=>'S,M,L,XL','images'=>[$imgVTT3,$imgVTT2]]);

        $make(['cat'=>'vtt','brand'=>'Santa Cruz','name'=>'Santa Cruz Bronson S Carbon 29"','name_de'=>'Santa Cruz Bronson S Carbon 29"','slug'=>'santa-cruz-bronson-s-carbon-29','description'=>'Le Santa Cruz Bronson S est le vélo enduro carbone de référence pour ceux qui veulent dévaler les sentiers avec style. 150 mm de débattement, cadre carbone C et composants Shimano XT.','description_de'=>'Das Santa Cruz Bronson S ist das Referenz-Carbon-Enduro-Bike für Stile-Fahrer. 150 mm Federweg, C-Carbon-Rahmen und Shimano XT Komponenten.','price'=>5499.00,'sale_price'=>4899.00,'is_new'=>false,'is_featured'=>false,'bike_type'=>'Enduro Carbone','wheel_size'=>'29"','frame_material'=>'Carbone C (moyen module)','number_of_speeds'=>'12 vitesses Shimano Deore XT','suspension_type'=>'RockShox Pike 150 mm / RockShox Super Deluxe','brake_style'=>'Hydraulique Shimano XT 4 pistons','weight'=>'13,8 kg','warranty_type'=>'Garantie Santa Cruz à vie','colors'=>'Vert,Bleu,Noir','sizes'=>'S,M,L,XL','images'=>[$imgVTT2,$imgVTT]]);

        $make(['cat'=>'vtt','brand'=>'YT Industries','name'=>'YT Jeffsy Core 4 29" 2025','name_de'=>'YT Jeffsy Core 4 29" 2025','slug'=>'yt-jeffsy-core-4-29-2025','description'=>'Le YT Jeffsy est le trail bike allemand qui allie agressivité et polyvalence. Sa géométrie longue et basse et ses 140 mm de débattement en font un vélo redoutable sur les sentiers techniques.','description_de'=>'Das YT Jeffsy ist das deutsche Trail-Bike, das Aggressivität und Vielseitigkeit verbindet. Lange, tiefe Geometrie und 140 mm Federweg machen es auf technischen Trails gefährlich.','price'=>3299.00,'sale_price'=>null,'is_new'=>true,'is_featured'=>false,'bike_type'=>'Trail Tout-suspendu','wheel_size'=>'29"','frame_material'=>'Aluminium 6061','number_of_speeds'=>'12 vitesses SRAM SX Eagle','suspension_type'=>'Fox 36 Rhythm 140 mm / Fox Float DPS 140 mm','brake_style'=>'Hydraulique SRAM G2 R','weight'=>'14,2 kg','warranty_type'=>'Garantie YT 2 ans','colors'=>'Noir,Blanc','sizes'=>'S,M,L,XL','images'=>[$imgVTT,$imgVTT3]]);

        $make(['cat'=>'vtt','brand'=>'Orbea','name'=>'Orbea Occam M30 29" 2025','name_de'=>'Orbea Occam M30 29" 2025','slug'=>'orbea-occam-m30-29-2025','description'=>'L\'Orbea Occam M30 est le vélo trail espagnol qui s\'adapte à tout. Sa géométrie ajustable MyGeometry et ses 130 mm de débattement en font un vélo polyvalent pour tous les niveaux.','description_de'=>'Das Orbea Occam M30 ist das spanische Trail-Bike, das sich an alles anpasst. Einstellbare MyGeometry und 130 mm Federweg machen es für alle Niveaus vielseitig.','price'=>2899.00,'sale_price'=>null,'is_new'=>false,'is_featured'=>false,'bike_type'=>'Trail Tout-suspendu','wheel_size'=>'29"','frame_material'=>'Aluminium 6061 T6','number_of_speeds'=>'12 vitesses Shimano Deore','suspension_type'=>'RockShox Recon 130 mm / RockShox Deluxe Select+','brake_style'=>'Hydraulique Shimano Deore 4 pistons','weight'=>'14,0 kg','warranty_type'=>'Garantie Orbea 5 ans cadre','colors'=>'Bleu,Noir,Rouge','sizes'=>'XS,S,M,L,XL','images'=>[$imgVTT3,$imgVTT2]]);

        $make(['cat'=>'vtt','brand'=>'Orbea','name'=>'Orbea Rallon M20 29" Enduro','name_de'=>'Orbea Rallon M20 29" Enduro','slug'=>'orbea-rallon-m20-29-enduro','description'=>'Le Orbea Rallon M20 est conçu pour les riders qui veulent tout donner en descente. Avec 170 mm de débattement, une géométrie agressive et des composants de qualité, il est taillé pour la compétition.','description_de'=>'Das Orbea Rallon M20 ist für Fahrer gemacht, die beim Abfahren alles geben wollen. 170 mm Federweg, aggressive Geometrie und Qualitätskomponenten für den Wettkampf.','price'=>3499.00,'sale_price'=>2999.00,'is_new'=>false,'is_featured'=>false,'bike_type'=>'Enduro','wheel_size'=>'29"','frame_material'=>'Aluminium 6061','number_of_speeds'=>'12 vitesses Shimano Deore XT','suspension_type'=>'Fox 38 Rhythm 170 mm / Fox Float X2 170 mm','brake_style'=>'Hydraulique Shimano XT 4 pistons','weight'=>'15,1 kg','warranty_type'=>'Garantie Orbea 5 ans','colors'=>'Rouge,Noir','sizes'=>'S,M,L,XL','images'=>[$imgVTT,$imgVTT2]]);

        $make(['cat'=>'vtt','brand'=>'Merida','name'=>'Merida Big.Nine 400 29" 2025','name_de'=>'Merida Big.Nine 400 29" 2025','slug'=>'merida-big-nine-400-29-2025','description'=>'Le Merida Big.Nine 400 est un VTT XC hardtail performant et accessible. Son cadre aluminium Lite et sa fourche RockShox 30 Silver offrent légèreté et confort pour vos sorties cross-country.','description_de'=>'Das Merida Big.Nine 400 ist ein leistungsstarkes und zugängliches XC Hardtail-MTB. Der Lite-Aluminiumrahmen und die RockShox 30 Silver Gabel bieten Leichtigkeit und Komfort.','price'=>1199.00,'sale_price'=>999.00,'is_new'=>false,'is_featured'=>false,'bike_type'=>'XC Hardtail','wheel_size'=>'29"','frame_material'=>'Aluminium Lite','number_of_speeds'=>'20 vitesses Shimano Deore','suspension_type'=>'RockShox 30 Silver 100 mm','brake_style'=>'Hydraulique Shimano MT200','weight'=>'12,8 kg','warranty_type'=>'Garantie Merida 5 ans','colors'=>'Noir,Bleu','sizes'=>'XS,S,M,L,XL,XXL','images'=>[$imgVTT2,$imgVTT]]);

        $make(['cat'=>'vtt','brand'=>'Merida','name'=>'Merida One-Sixty 800 29" 2025','name_de'=>'Merida One-Sixty 800 29" 2025','slug'=>'merida-one-sixty-800-29-2025','description'=>'Le Merida One-Sixty 800 est le vélo enduro haut de gamme de la marque taïwanaise. Avec 160 mm de débattement et un groupe Shimano XT, il est prêt pour les compétitions enduro les plus exigeantes.','description_de'=>'Das Merida One-Sixty 800 ist das Top-Enduro-Bike der taiwanesischen Marke. Mit 160 mm Federweg und Shimano XT Gruppe ist es für die anspruchsvollsten Enduro-Wettkämpfe bereit.','price'=>3299.00,'sale_price'=>null,'is_new'=>true,'is_featured'=>false,'bike_type'=>'Enduro','wheel_size'=>'29"','frame_material'=>'Aluminium 6061','number_of_speeds'=>'12 vitesses Shimano Deore XT','suspension_type'=>'RockShox Lyrik 160 mm / RockShox Super Deluxe 160 mm','brake_style'=>'Hydraulique Shimano XT 4 pistons','weight'=>'14,9 kg','warranty_type'=>'Garantie Merida 5 ans','colors'=>'Gris,Noir','sizes'=>'S,M,L,XL','images'=>[$imgVTT3,$imgVTT]]);

        $make(['cat'=>'vtt','brand'=>'Pivot','name'=>'Pivot Mach 4 SL Team XTR 29"','name_de'=>'Pivot Mach 4 SL Team XTR 29"','slug'=>'pivot-mach-4-sl-team-xtr-29','description'=>'Le Pivot Mach 4 SL Team est le vélo XC carbone ultime. Utilisé par les équipes professionnelles, il combine le meilleur de la technologie carbone avec un groupe Shimano XTR et des composants race.','description_de'=>'Das Pivot Mach 4 SL Team ist das ultimative XC Carbon-Bike. Von Profi-Teams eingesetzt, kombiniert es beste Carbon-Technologie mit Shimano XTR und Race-Komponenten.','price'=>9999.00,'sale_price'=>null,'is_new'=>true,'is_featured'=>true,'bike_type'=>'XC Race Carbone','wheel_size'=>'29"','frame_material'=>'Carbone UD','number_of_speeds'=>'12 vitesses Shimano XTR','suspension_type'=>'Fox 34 Float Factory 100 mm / Fox Float DPS Factory','brake_style'=>'Hydraulique Shimano XTR','weight'=>'8,9 kg','warranty_type'=>'Garantie Pivot à vie cadre','colors'=>'Blanc,Bleu','sizes'=>'XS,S,M,L,XL','images'=>[$imgVTT,$imgVTT2]]);

        $make(['cat'=>'vtt','brand'=>'Norco','name'=>'Norco Sight A2 29" 2025','name_de'=>'Norco Sight A2 29" 2025','slug'=>'norco-sight-a2-29-2025','description'=>'Le Norco Sight A2 est un trail bike canadien taillé pour l\'aventure. Sa géométrie progressive et son débattement de 140 mm en font un vélo capable et confiant sur tous les types de terrains.','description_de'=>'Das Norco Sight A2 ist ein kanadisches Trail-Bike für Abenteuer. Progressive Geometrie und 140 mm Federweg machen es fähig und souverän auf allen Geländearten.','price'=>2999.00,'sale_price'=>null,'is_new'=>false,'is_featured'=>false,'bike_type'=>'Trail Tout-suspendu','wheel_size'=>'29"','frame_material'=>'Aluminium A6061','number_of_speeds'=>'12 vitesses SRAM GX Eagle','suspension_type'=>'Fox 36 Rhythm 140 mm / Fox Float DPS','brake_style'=>'Hydraulique SRAM G2 R','weight'=>'14,3 kg','warranty_type'=>'Garantie Norco à vie cadre','colors'=>'Vert,Noir','sizes'=>'XS,S,M,L,XL','images'=>[$imgVTT2,$imgVTT3]]);

        // ═══════════════════════════════════════════════
        // ██ ROUTE — 20 produits supplémentaires
        // ═══════════════════════════════════════════════

        $make(['cat'=>'route','brand'=>'Colnago','name'=>'Colnago C68 Disc Shimano Dura-Ace Di2','name_de'=>'Colnago C68 Disc Shimano Dura-Ace Di2','slug'=>'colnago-c68-disc-dura-ace-di2','description'=>'Le Colnago C68 représente le summum de l\'artisanat italien. Son cadre carbone de la plus haute qualité, associé à un groupe Shimano Dura-Ace Di2, en fait le vélo de route le plus désirable du moment.','description_de'=>'Das Colnago C68 steht für den Gipfel italienischer Handwerkskunst. Höchste Qualität Carbon plus Shimano Dura-Ace Di2 macht es zum begehrtesten Rennrad der Zeit.','price'=>12999.00,'sale_price'=>null,'is_new'=>true,'is_featured'=>true,'bike_type'=>'Vélo de route haut de gamme','wheel_size'=>'700c','frame_material'=>'Carbone T800/T1000 haute modélisation','number_of_speeds'=>'22 vitesses Shimano Dura-Ace Di2','suspension_type'=>'Rigide','brake_style'=>'Disque hydraulique Shimano Dura-Ace','weight'=>'6,8 kg','warranty_type'=>'Garantie Colnago à vie cadre','colors'=>'Blanc,Rouge,Bleu','sizes'=>'45,48,50,52,54,56,58','images'=>[$imgRoute,$imgRoute2]]);

        $make(['cat'=>'route','brand'=>'Pinarello','name'=>'Pinarello Dogma F Shimano Dura-Ace','name_de'=>'Pinarello Dogma F Shimano Dura-Ace','slug'=>'pinarello-dogma-f-dura-ace','description'=>'Le Pinarello Dogma F est le vélo sur lequel Chris Froome et Egan Bernal ont gagné le Tour de France. Sa géométrie asymétrique brevetée ONDA et son carbone T1100 le placent au sommet de la technologie cycliste mondiale.','description_de'=>'Das Pinarello Dogma F ist das Fahrrad, auf dem Chris Froome und Egan Bernal die Tour de France gewannen. Asymmetrische ONDA-Geometrie und T1100 Carbon an der Weltspitze.','price'=>14999.00,'sale_price'=>null,'is_new'=>true,'is_featured'=>true,'bike_type'=>'Vélo de route pro','wheel_size'=>'700c','frame_material'=>'Carbone TorayCA T1100 1K','number_of_speeds'=>'22 vitesses Shimano Dura-Ace Di2','suspension_type'=>'Rigide','brake_style'=>'Disque hydraulique Shimano Dura-Ace','weight'=>'6,5 kg','warranty_type'=>'Garantie Pinarello 5 ans','colors'=>'Noir,Blanc','sizes'=>'44,46,50,51.5,53,54,55,56,57.5,59,62','images'=>[$imgRoute2,$imgRoute]]);

        $make(['cat'=>'route','brand'=>'De Rosa','name'=>'De Rosa SK Disc Ultegra Di2','name_de'=>'De Rosa SK Disc Ultegra Di2','slug'=>'de-rosa-sk-disc-ultegra-di2','description'=>'Le De Rosa SK Disc est un vélo de route carbone élégant et performant. La marque italienne légendaire propose ici un vélo qui allie esthétique raffinée et performances de haut niveau avec le groupe Shimano Ultegra Di2.','description_de'=>'Das De Rosa SK Disc ist ein elegantes und leistungsstarkes Carbon-Rennrad. Die legendäre italienische Marke bietet hier ein Bike mit raffinierter Ästhetik und Spitzenleistung.','price'=>6999.00,'sale_price'=>5999.00,'is_new'=>false,'is_featured'=>false,'bike_type'=>'Vélo de route','wheel_size'=>'700c','frame_material'=>'Carbone HM','number_of_speeds'=>'22 vitesses Shimano Ultegra Di2','suspension_type'=>'Rigide','brake_style'=>'Disque hydraulique Shimano Ultegra','weight'=>'7,4 kg','warranty_type'=>'Garantie De Rosa 5 ans','colors'=>'Rouge,Blanc,Noir','sizes'=>'44,47,49,51,53,55,57','images'=>[$imgRoute,$imgRoute3]]);

        $make(['cat'=>'route','brand'=>'Bianchi','name'=>'Bianchi Oltre RC Dura-Ace Di2','name_de'=>'Bianchi Oltre RC Dura-Ace Di2','slug'=>'bianchi-oltre-rc-dura-ace-di2','description'=>'Le Bianchi Oltre RC est le vaisseau amiral de la marque italienne historique. Sa couleur Celeste emblématique et son groupe Dura-Ace Di2 en font un vélo aussi beau que performant, taillé pour la victoire.','description_de'=>'Das Bianchi Oltre RC ist das Flaggschiff der historischen italienischen Marke. Die ikonische Celeste-Farbe und Dura-Ace Di2 machen es so schön wie leistungsstark.','price'=>11999.00,'sale_price'=>null,'is_new'=>true,'is_featured'=>true,'bike_type'=>'Vélo de route aero','wheel_size'=>'700c','frame_material'=>'Carbone CV (CounterVail)','number_of_speeds'=>'22 vitesses Shimano Dura-Ace Di2','suspension_type'=>'Rigide CounterVail','brake_style'=>'Disque hydraulique Shimano Dura-Ace','weight'=>'6,9 kg','warranty_type'=>'Garantie Bianchi à vie','colors'=>'Celeste,Noir,Blanc','sizes'=>'44,47,50,53,55,57,59','images'=>[$imgRoute3,$imgRoute2]]);

        $make(['cat'=>'route','brand'=>'Look','name'=>'Look 795 Blade RS Disc Ultegra Di2','name_de'=>'Look 795 Blade RS Disc Ultegra Di2','slug'=>'look-795-blade-rs-disc-ultegra-di2','description'=>'Le Look 795 Blade RS est le vélo aérodynamique phare de la marque française. Sa conception avant-gardiste et son cadre carbone high-modulus le rendent aussi élégant que rapide.','description_de'=>'Das Look 795 Blade RS ist das aerodynamische Flaggschiff der französischen Marke. Avantgardistisches Design und High-Modulus-Carbon machen es so elegant wie schnell.','price'=>8499.00,'sale_price'=>null,'is_new'=>false,'is_featured'=>true,'bike_type'=>'Vélo de route aero','wheel_size'=>'700c','frame_material'=>'Carbone HM UD','number_of_speeds'=>'22 vitesses Shimano Ultegra Di2','suspension_type'=>'Rigide','brake_style'=>'Disque hydraulique Shimano Ultegra','weight'=>'7,2 kg','warranty_type'=>'Garantie Look 5 ans','colors'=>'Noir mat,Blanc,Blanc/Rouge','sizes'=>'44,47,49,52,54,56,58','images'=>[$imgRoute2,$imgRoute]]);

        $make(['cat'=>'route','brand'=>'Time','name'=>'Time Alpe D\'Huez 01 Disc 105','name_de'=>'Time Alpe D\'Huez 01 Disc 105','slug'=>'time-alpe-d-huez-01-disc-105','description'=>'Le Time Alpe D\'Huez 01 est le vélo carbone entrée de gamme de la marque française. Malgré son positionnement accessible, il hérite des technologies de pointe de Time et offre une rigidité et un confort exceptionnels.','description_de'=>'Das Time Alpe D\'Huez 01 ist das günstige Carbon-Einstiegsmodell der französischen Marke. Trotz des günstigen Preises erbt es die Spitzentechnologie von Time.','price'=>3299.00,'sale_price'=>2799.00,'is_new'=>false,'is_featured'=>false,'bike_type'=>'Vélo de route','wheel_size'=>'700c','frame_material'=>'Carbone Time UHPC','number_of_speeds'=>'22 vitesses Shimano 105','suspension_type'=>'Rigide','brake_style'=>'Disque hydraulique Shimano 105','weight'=>'8,1 kg','warranty_type'=>'Garantie Time 3 ans','colors'=>'Noir,Gris','sizes'=>'XXS,XS,S,M,L,XL','images'=>[$imgRoute,$imgRoute3]]);

        $make(['cat'=>'route','brand'=>'Cervélo','name'=>'Cervélo R5 Ultegra Di2 2025','name_de'=>'Cervélo R5 Ultegra Di2 2025','slug'=>'cervelo-r5-ultegra-di2-2025','description'=>'Le Cervélo R5 est le vélo de route idéal pour les cyclistes qui cherchent la légèreté et la rigidité sans compromis. Favori des grimpeurs, il excelle sur les routes de montagne.','description_de'=>'Das Cervélo R5 ist das ideale Rennrad für Fahrer, die Leichtigkeit und Steifigkeit ohne Kompromisse suchen. Liebling der Kletterer auf Bergstraßen.','price'=>7499.00,'sale_price'=>null,'is_new'=>true,'is_featured'=>false,'bike_type'=>'Vélo de route grimpeur','wheel_size'=>'700c','frame_material'=>'Carbone carbo-HM','number_of_speeds'=>'22 vitesses Shimano Ultegra Di2','suspension_type'=>'Rigide','brake_style'=>'Disque hydraulique Shimano Ultegra','weight'=>'6,9 kg','warranty_type'=>'Garantie Cervélo 5 ans','colors'=>'Noir,Blanc,Bleu','sizes'=>'44,48,51,54,56,58,61','images'=>[$imgRoute3,$imgRoute]]);

        $make(['cat'=>'route','brand'=>'Wilier','name'=>'Wilier Filante SLR Dura-Ace Di2','name_de'=>'Wilier Filante SLR Dura-Ace Di2','slug'=>'wilier-filante-slr-dura-ace-di2','description'=>'Le Wilier Filante SLR est la réponse italienne aux vélos aéro les plus rapides du monde. Son tunnel aérodynamique exclusif et son cadre carbone ultra-rigide en font un monstre de vitesse sur le plat.','description_de'=>'Das Wilier Filante SLR ist die italienische Antwort auf die schnellsten Aero-Bikes der Welt. Exklusiver aerodynamischer Tunnel und ultra-steifer Carbon-Rahmen.','price'=>9499.00,'sale_price'=>null,'is_new'=>true,'is_featured'=>true,'bike_type'=>'Vélo de route aero','wheel_size'=>'700c','frame_material'=>'Carbone T800/T1000','number_of_speeds'=>'22 vitesses Shimano Dura-Ace Di2','suspension_type'=>'Rigide','brake_style'=>'Disque hydraulique Shimano Dura-Ace','weight'=>'7,1 kg','warranty_type'=>'Garantie Wilier 5 ans','colors'=>'Noir mat,Rouge,Blanc','sizes'=>'XS,S,M,L,XL','images'=>[$imgRoute2,$imgRoute3]]);

        $make(['cat'=>'route','brand'=>'BMC','name'=>'BMC Teammachine SLR 01 ONE 2025','name_de'=>'BMC Teammachine SLR 01 ONE 2025','slug'=>'bmc-teammachine-slr-01-one-2025','description'=>'Le BMC Teammachine SLR 01 ONE est le vélo de route ultime de la marque suisse. Utilisé par l\'équipe BMC Racing, il représente le meilleur de la technologie suisse appliquée au cyclisme de compétition.','description_de'=>'Das BMC Teammachine SLR 01 ONE ist das ultimative Rennrad der Schweizer Marke. Vom BMC Racing Team eingesetzt, repräsentiert es das Beste der Schweizer Technologie.','price'=>13499.00,'sale_price'=>null,'is_new'=>true,'is_featured'=>true,'bike_type'=>'Vélo de route pro','wheel_size'=>'700c','frame_material'=>'Carbone ACE (Advanced Composite Engineering)','number_of_speeds'=>'22 vitesses Shimano Dura-Ace Di2','suspension_type'=>'Rigide','brake_style'=>'Disque hydraulique Shimano Dura-Ace','weight'=>'6,7 kg','warranty_type'=>'Garantie BMC 5 ans','colors'=>'Rouge/Noir,Blanc/Bleu','sizes'=>'44,47,49,51,53,55,57,61','images'=>[$imgRoute,$imgRoute2]]);

        $make(['cat'=>'route','brand'=>'Ridley','name'=>'Ridley Helium SLX Disc 105 Di2','name_de'=>'Ridley Helium SLX Disc 105 Di2','slug'=>'ridley-helium-slx-disc-105-di2','description'=>'Le Ridley Helium SLX est le vélo belge léger par excellence. Conçu pour les cyclistes qui recherchent la légèreté maximale, il excelle dans les terrains montagneux et les courses en côte.','description_de'=>'Das Ridley Helium SLX ist das leichte belgische Bike schlechthin. Für maximale Leichtigkeit konzipiert, glänzt es in bergigem Terrain und Bergrennen.','price'=>4499.00,'sale_price'=>3999.00,'is_new'=>false,'is_featured'=>false,'bike_type'=>'Vélo de route léger','wheel_size'=>'700c','frame_material'=>'Carbone HM UD','number_of_speeds'=>'22 vitesses Shimano 105 Di2','suspension_type'=>'Rigide','brake_style'=>'Disque hydraulique Shimano 105','weight'=>'7,0 kg','warranty_type'=>'Garantie Ridley 5 ans','colors'=>'Noir/Vert,Blanc/Bleu','sizes'=>'XS,S,M,L,XL','images'=>[$imgRoute3,$imgRoute]]);

        // ═══════════════════════════════════════════════
        // ██ GRAVEL — 12 produits supplémentaires
        // ═══════════════════════════════════════════════

        $make(['cat'=>'gravel','brand'=>'Allied Cycle Works','name'=>'Allied Able Apex AXS Gravel','name_de'=>'Allied Able Apex AXS Gravel','slug'=>'allied-able-apex-axs-gravel','description'=>'L\'Allied Able est un vélo gravel américain fabriqué à la main dans l\'Arkansas. Son cadre carbone produit aux USA et son groupe SRAM Apex AXS en font un vélo gravel haut de gamme pour les aventuriers exigeants.','description_de'=>'Das Allied Able ist ein handgefertigtes amerikanisches Gravel-Bike aus Arkansas. US-gefertigter Carbon-Rahmen und SRAM Apex AXS für anspruchsvolle Abenteurer.','price'=>5499.00,'sale_price'=>null,'is_new'=>true,'is_featured'=>false,'bike_type'=>'Gravel Aventure','wheel_size'=>'700c','frame_material'=>'Carbone fabriqué aux USA','number_of_speeds'=>'12 vitesses SRAM Apex AXS','suspension_type'=>'Rigide IsoSpeed','brake_style'=>'Disque hydraulique SRAM Apex','weight'=>'8,4 kg','warranty_type'=>'Garantie Allied à vie','colors'=>'Vert,Noir,Blanc','sizes'=>'50,52,54,56,58,60','images'=>[$imgGravel,$imgRoute]]);

        $make(['cat'=>'gravel','brand'=>'Open Cycles','name'=>'Open WI.DE. GRX Di2 Gravel','name_de'=>'Open WI.DE. GRX Di2 Gravel','slug'=>'open-cycles-wide-grx-di2-gravel','description'=>'L\'Open WI.DE. est un vélo gravel suisse polyvalent conçu pour les longues aventures bikepacking. Ses passages de pneus généreux (jusqu\'à 50c) et son groupe GRX Di2 en font un explorateur hors du commun.','description_de'=>'Das Open WI.DE. ist ein vielseitiges Schweizer Gravel-Bike für lange Bikepacking-Abenteuer. Großzügige Reifenfreiheit (bis 50c) und GRX Di2 Gruppe.','price'=>6299.00,'sale_price'=>null,'is_new'=>false,'is_featured'=>true,'bike_type'=>'Gravel / Bikepacking','wheel_size'=>'700c / 650b','frame_material'=>'Carbone UD','number_of_speeds'=>'22 vitesses Shimano GRX Di2','suspension_type'=>'Rigide + passages 50c','brake_style'=>'Disque hydraulique Shimano GRX','weight'=>'8,9 kg','warranty_type'=>'Garantie Open 5 ans','colors'=>'Vert,Sable,Noir','sizes'=>'XS,S,M,L,XL','images'=>[$imgGravel,$imgRoute2]]);

        $make(['cat'=>'gravel','brand'=>'Salsa','name'=>'Salsa Warbird Carbon GRX 600 2x','name_de'=>'Salsa Warbird Carbon GRX 600 2x','slug'=>'salsa-warbird-carbon-grx-600','description'=>'Le Salsa Warbird est le vélo gravel américain pour les raids longue distance. Conçu pour les gravel races comme Unbound Gravel, il allie confort, performance et capacité de portage exceptionnels.','description_de'=>'Das Salsa Warbird ist das amerikanische Gravel-Bike für Langstreckenfahrten. Für Gravel-Rennen wie Unbound Gravel konzipiert, verbindet es Komfort, Leistung und Tragekapazität.','price'=>3799.00,'sale_price'=>3299.00,'is_new'=>false,'is_featured'=>false,'bike_type'=>'Gravel Race / Endurance','wheel_size'=>'700c','frame_material'=>'Carbone','number_of_speeds'=>'22 vitesses Shimano GRX 600','suspension_type'=>'Rigide carbone IFT','brake_style'=>'Disque hydraulique Shimano GRX','weight'=>'9,1 kg','warranty_type'=>'Garantie Salsa à vie','colors'=>'Rouge,Noir,Vert','sizes'=>'49,52,54,56,58,61','images'=>[$imgGravel,$imgRoute3]]);

        $make(['cat'=>'gravel','brand'=>'Ritchey','name'=>'Ritchey Outback V2 GRX 2025','name_de'=>'Ritchey Outback V2 GRX 2025','slug'=>'ritchey-outback-v2-grx-2025','description'=>'Le Ritchey Outback V2 est un vélo gravel aluminium de qualité premium à prix raisonnable. Son cadre acier chromoly légendaire offre un confort de route exceptionnel et une durabilité sans égale.','description_de'=>'Das Ritchey Outback V2 ist ein Premium-Aluminium-Gravel-Bike zu vernünftigem Preis. Legendärer Chromoly-Stahlrahmen für außergewöhnlichen Fahrkomfort und unübertroffene Haltbarkeit.','price'=>1899.00,'sale_price'=>null,'is_new'=>false,'is_featured'=>false,'bike_type'=>'Gravel / Aventure','wheel_size'=>'700c','frame_material'=>'Acier Ritchey Logic Chromoly','number_of_speeds'=>'22 vitesses Shimano GRX','suspension_type'=>'Rigide acier','brake_style'=>'Disque hydraulique Shimano GRX','weight'=>'10,2 kg','warranty_type'=>'Garantie Ritchey à vie','colors'=>'Sable,Noir,Vert','sizes'=>'47,49,51,54,56,59','images'=>[$imgGravel,$imgRoute]]);

        $make(['cat'=>'gravel','brand'=>'Niner','name'=>'Niner RLT 9 Steel 3-Star GRX','name_de'=>'Niner RLT 9 Steel 3-Star GRX','slug'=>'niner-rlt-9-steel-3-star-grx','description'=>'Le Niner RLT 9 Steel est le gravel bike en acier américain par excellence. Doux, polyvalent et indestructible, il est taillé pour les longues aventures sans se soucier du terrain.','description_de'=>'Das Niner RLT 9 Steel ist das amerikanische Stahl-Gravel-Bike schlechthin. Weich, vielseitig und unzerstörbar für lange Abenteuer ohne Rücksicht auf das Gelände.','price'=>2299.00,'sale_price'=>null,'is_new'=>false,'is_featured'=>false,'bike_type'=>'Gravel Acier','wheel_size'=>'700c','frame_material'=>'Acier RLT 853 Reynolds','number_of_speeds'=>'20 vitesses Shimano GRX 600','suspension_type'=>'Rigide acier','brake_style'=>'Disque hydraulique Shimano GRX','weight'=>'10,8 kg','warranty_type'=>'Garantie Niner à vie','colors'=>'Vert,Sable,Noir','sizes'=>'50,52,54,56,58,60','images'=>[$imgGravel,$imgRoute2]]);

        // ═══════════════════════════════════════════════
        // ██ VILLE — 10 produits supplémentaires
        // ═══════════════════════════════════════════════

        $make(['cat'=>'ville','brand'=>'Riese & Müller','name'=>'Riese & Müller Roadster 5 Mixte','name_de'=>'Riese & Müller Roadster 5 Mixte','slug'=>'riese-muller-roadster-5-mixte','description'=>'Le Riese & Müller Roadster 5 Mixte est un vélo urbain premium fabriqué en Allemagne. Son cadre step-through facilite la montée et sa finition irréprochable en fait un vélo de ville haut de gamme durable.','description_de'=>'Das Riese & Müller Roadster 5 Mixte ist ein in Deutschland gefertigtes Premium-Stadtrad. Der Step-Through-Rahmen erleichtert das Aufsteigen und die tadellose Verarbeitung macht es dauerhaft hochwertig.','price'=>1299.00,'sale_price'=>null,'is_new'=>false,'is_featured'=>false,'bike_type'=>'Vélo urbain mixte','wheel_size'=>'700c','frame_material'=>'Aluminium','number_of_speeds'=>'8 vitesses Shimano Nexus','suspension_type'=>'Rigide','brake_style'=>'Disque hydraulique Magura','weight'=>'14,2 kg','warranty_type'=>'Garantie R&M 2 ans','colors'=>'Noir,Blanc,Bleu','sizes'=>'XS,S,M,L','images'=>[$imgVille,$imgGravel]]);

        $make(['cat'=>'ville','brand'=>'Peugeot','name'=>'Peugeot LC01 7 Allure Ville','name_de'=>'Peugeot LC01 7 Allure Stadt','slug'=>'peugeot-lc01-7-allure-ville','description'=>'Le Peugeot LC01 7 Allure est un vélo de ville élégant à l\'image de la marque française historique. Son design épuré et son équipement complet en font le compagnon idéal des déplacements urbains quotidiens.','description_de'=>'Das Peugeot LC01 7 Allure ist ein elegantes Stadtrad im Stil der historischen französischen Marke. Klares Design und vollständige Ausstattung für den täglichen Stadtverkehr.','price'=>699.00,'sale_price'=>599.00,'is_new'=>false,'is_featured'=>false,'bike_type'=>'Vélo de ville','wheel_size'=>'700c','frame_material'=>'Aluminium 6061','number_of_speeds'=>'7 vitesses Shimano Altus','suspension_type'=>'Rigide','brake_style'=>'V-Brake','weight'=>'12,8 kg','warranty_type'=>'Garantie Peugeot 2 ans','colors'=>'Noir,Blanc crème,Bleu marine','sizes'=>'43,48,52,56','images'=>[$imgVille,$imgGravel]]);

        $make(['cat'=>'ville','brand'=>'Batavus','name'=>'Batavus Dinsdag 8D Pure Ego','name_de'=>'Batavus Dinsdag 8D Pure Ego','slug'=>'batavus-dinsdag-8d-pure-ego','description'=>'Le Batavus Dinsdag 8D est un vélo hollandais de qualité premium. Sa transmission interne 8 vitesses et son entretien minimal en font le vélo urbain parfait pour les adeptes de mobilité douce.','description_de'=>'Das Batavus Dinsdag 8D ist ein hochwertiges niederländisches Fahrrad. Interne 8-Gang-Schaltung und minimaler Wartungsaufwand machen es zum perfekten Stadtrad.','price'=>1099.00,'sale_price'=>null,'is_new'=>false,'is_featured'=>false,'bike_type'=>'Vélo hollandais','wheel_size'=>'28"','frame_material'=>'Aluminium','number_of_speeds'=>'8 vitesses Shimano Nexus interne','suspension_type'=>'Rigide','brake_style'=>'Frein à rétropédalage + frein à main','weight'=>'15,4 kg','warranty_type'=>'Garantie Batavus 2 ans','colors'=>'Noir,Anthracite,Bleu','sizes'=>'46,50,53,57','images'=>[$imgVille,$imgGravel]]);

        $make(['cat'=>'ville','brand'=>'Gazelle','name'=>'Gazelle Esprit C7 HMS Vélo Ville','name_de'=>'Gazelle Esprit C7 HMS Stadtrad','slug'=>'gazelle-esprit-c7-hms-ville','description'=>'Le Gazelle Esprit C7 HMS est un vélo de ville hollandais alliant style et praticité. Son cadre robuste et ses 7 vitesses internes Shimano en font un compagnon fiable pour tous vos déplacements.','description_de'=>'Das Gazelle Esprit C7 HMS ist ein niederländisches Stadtrad, das Stil und Praktikabilität vereint. Robuster Rahmen und 7-Gang Shimano Internalschaltung für zuverlässige Stadtfahrten.','price'=>849.00,'sale_price'=>null,'is_new'=>false,'is_featured'=>false,'bike_type'=>'Vélo de ville hollandais','wheel_size'=>'28"','frame_material'=>'Aluminium','number_of_speeds'=>'7 vitesses Shimano Nexus','suspension_type'=>'Rigide','brake_style'=>'Frein à rétropédalage + frein à main','weight'=>'16,1 kg','warranty_type'=>'Garantie Gazelle 2 ans','colors'=>'Noir,Blanc,Bronze','sizes'=>'49,53,57,61','images'=>[$imgVille,$imgGravel]]);

        $make(['cat'=>'ville','brand'=>'Votec','name'=>'Votec VC Comp Vélo Commuter','name_de'=>'Votec VC Comp Pendler Fahrrad','slug'=>'votec-vc-comp-commuter','description'=>'Le Votec VC Comp est le vélo commuter allemand parfait pour les cyclistes urbains exigeants. Léger, rapide et bien équipé, il permet de traverser la ville avec efficacité et style.','description_de'=>'Das Votec VC Comp ist das perfekte deutsche Pendlerrad für anspruchsvolle Stadtfahrer. Leicht, schnell und gut ausgestattet, um die Stadt effizient zu durchqueren.','price'=>1199.00,'sale_price'=>999.00,'is_new'=>true,'is_featured'=>false,'bike_type'=>'Vélo commuter','wheel_size'=>'700c','frame_material'=>'Aluminium 6061','number_of_speeds'=>'11 vitesses Shimano 105','suspension_type'=>'Rigide','brake_style'=>'Disque hydraulique Shimano 105','weight'=>'9,8 kg','warranty_type'=>'Garantie Votec 2 ans','colors'=>'Noir,Bleu,Gris','sizes'=>'48,52,56,60','images'=>[$imgVille,$imgGravel]]);

        // ═══════════════════════════════════════════════
        // ██ ÉLECTRIQUE — 20 produits supplémentaires
        // ═══════════════════════════════════════════════

        $make(['cat'=>'electrique','brand'=>'Riese & Müller','name'=>'Riese & Müller Supercharger GT Rohloff','name_de'=>'Riese & Müller Supercharger GT Rohloff','slug'=>'riese-muller-supercharger-gt-rohloff','description'=>'Le Riese & Müller Supercharger GT Rohloff est le roi des vélos électriques longue distance. Sa double batterie 1125 Wh et sa transmission Rohloff 14 vitesses en font le compagnon idéal pour des trajets de plus de 200 km.','description_de'=>'Das R&M Supercharger GT Rohloff ist der König der E-Bikes für Langstrecken. Doppelakku 1125 Wh und Rohloff 14-Gang-Schaltung für über 200 km Reichweite.','price'=>8499.00,'sale_price'=>null,'is_new'=>true,'is_featured'=>true,'bike_type'=>'E-Bike Trekking longue distance','wheel_size'=>'29"','frame_material'=>'Aluminium premium','number_of_speeds'=>'14 vitesses Rohloff E-14','suspension_type'=>'Fourche suspendue 63 mm','brake_style'=>'Disque hydraulique Magura MT5e','power_source'=>'Batterie lithium-ion double','motor_power'=>'Bosch Performance CX Smart System 250 W / 85 Nm','battery_capacity'=>'1125 Wh (2×562,5 Wh)','max_speed'=>'25 km/h','max_range'=>'200+ km en mode Eco','charging_time'=>'6h (charge complète)','weight'=>'33,5 kg','warranty_type'=>'Garantie R&M 2 ans + Bosch 2 ans','colors'=>'Noir,Gris,Bleu','sizes'=>'43,49,54','images'=>[$imgElec,$imgElec2]]);

        $make(['cat'=>'electrique','brand'=>'Stromer','name'=>'Stromer ST5 Sport 45 km/h Speed Pedelec','name_de'=>'Stromer ST5 Sport 45 km/h Speed-Pedelec','slug'=>'stromer-st5-sport-45-speed-pedelec','description'=>'Le Stromer ST5 Sport est un speed pedelec suisse de haute technologie. Assisté jusqu\'à 45 km/h, il transforme chaque trajet en aventure rapide. Son application myStromer permet de contrôler et sécuriser le vélo depuis votre smartphone.','description_de'=>'Das Stromer ST5 Sport ist ein High-Tech-Speed-Pedelec aus der Schweiz. Unterstützung bis 45 km/h verwandelt jede Fahrt in ein schnelles Abenteuer. Die myStromer App steuert und sichert das Bike.','price'=>7999.00,'sale_price'=>null,'is_new'=>true,'is_featured'=>true,'bike_type'=>'Speed Pedelec 45 km/h','wheel_size'=>'27.5"','frame_material'=>'Aluminium','number_of_speeds'=>'12 vitesses SRAM Red eTap AXS','suspension_type'=>'Rigide','brake_style'=>'Disque hydraulique Magura MT5e','power_source'=>'Batterie intégrée Li-Ion','motor_power'=>'Stromer SYNO Drive II 250 W / 48 Nm','battery_capacity'=>'983 Wh','max_speed'=>'45 km/h (assistance)','max_range'=>'150 km en mode Eco','charging_time'=>'4h30','weight'=>'26,5 kg','warranty_type'=>'Garantie Stromer 2 ans','colors'=>'Noir,Blanc','sizes'=>'42,48,54','images'=>[$imgElec2,$imgElec]]);

        $make(['cat'=>'electrique','brand'=>'Flyer','name'=>'Flyer Upstreet 5 7.23 E-Bike Urbain','name_de'=>'Flyer Upstreet 5 7.23 E-Bike Urban','slug'=>'flyer-upstreet-5-7-23-urbain','description'=>'Le Flyer Upstreet 5 est le vélo électrique urbain suisse parfait pour les déplacements quotidiens. Son design élégant et son équipement complet (éclairage intégré, garde-boues, porte-bagages) en font un vélo prêt à l\'emploi.','description_de'=>'Das Flyer Upstreet 5 ist das perfekte Schweizer E-Bike für den Alltag. Elegantes Design und vollständige Ausstattung (integrierte Beleuchtung, Schutzbleche, Gepäckträger) macht es sofort einsatzbereit.','price'=>3499.00,'sale_price'=>2999.00,'is_new'=>false,'is_featured'=>false,'bike_type'=>'E-Bike Urbain','wheel_size'=>'28"','frame_material'=>'Aluminium','number_of_speeds'=>'7 vitesses Shimano Nexus','suspension_type'=>'Fourche rigide','brake_style'=>'Disque hydraulique Shimano','power_source'=>'Batterie lithium-ion','motor_power'=>'Shimano EP6 250 W / 60 Nm','battery_capacity'=>'630 Wh','max_speed'=>'25 km/h','max_range'=>'100 km en mode Eco','charging_time'=>'4h','weight'=>'25,8 kg','warranty_type'=>'Garantie Flyer 2 ans + Shimano 2 ans','colors'=>'Noir,Gris,Bleu','sizes'=>'XS,S,M,L,XL','images'=>[$imgElec,$imgElec2]]);

        $make(['cat'=>'electrique','brand'=>'Haibike','name'=>'Haibike AllMtn 6 29" E-MTB 2025','name_de'=>'Haibike AllMtn 6 29" E-MTB 2025','slug'=>'haibike-allmtn-6-29-emtb-2025','description'=>'Le Haibike AllMtn 6 est le VTT électrique tout-terrain de la marque allemande pionnière des e-MTB. Son moteur Yamaha PW-X3 et sa batterie 630 Wh lui donnent l\'autonomie nécessaire pour conquérir les sentiers les plus exigeants.','description_de'=>'Das Haibike AllMtn 6 ist das E-MTB der deutschen Pioniermarke. Yamaha PW-X3 Motor und 630 Wh Akku für die Reichweite, die anspruchsvollste Trails bezwingt.','price'=>4499.00,'sale_price'=>3899.00,'is_new'=>false,'is_featured'=>false,'bike_type'=>'E-MTB Tout-suspendu','wheel_size'=>'29"','frame_material'=>'Aluminium 6061','number_of_speeds'=>'12 vitesses Shimano Deore','suspension_type'=>'Fox 36 Rhythm 150 mm / Fox Float DPS 150 mm','brake_style'=>'Hydraulique Shimano Deore XT 4 pistons','power_source'=>'Batterie Yamaha intégrée','motor_power'=>'Yamaha PW-X3 250 W / 85 Nm','battery_capacity'=>'630 Wh','max_speed'=>'25 km/h','max_range'=>'95 km en mode Eco','charging_time'=>'4h','weight'=>'24,8 kg','warranty_type'=>'Garantie Haibike 2 ans','colors'=>'Noir,Vert,Bleu','sizes'=>'S,M,L,XL','images'=>[$imgElec2,$imgElec]]);

        $make(['cat'=>'electrique','brand'=>'Orbea','name'=>'Orbea Rise LT M20 E-MTB Léger','name_de'=>'Orbea Rise LT M20 E-MTB Leicht','slug'=>'orbea-rise-lt-m20-emtb-leger','description'=>'L\'Orbea Rise LT M20 repousse les limites du VTT électrique léger. Avec seulement 19 kg et un moteur Shimano EP8 RS 85 Nm, il offre la sensation du VTT traditionnel avec l\'assistance électrique discrète.','description_de'=>'Das Orbea Rise LT M20 verschiebt die Grenzen des leichten E-MTBs. Mit nur 19 kg und Shimano EP8 RS 85 Nm bietet es das Gefühl eines traditionellen MTBs mit dezenter E-Unterstützung.','price'=>6499.00,'sale_price'=>null,'is_new'=>true,'is_featured'=>true,'bike_type'=>'E-MTB léger','wheel_size'=>'29"','frame_material'=>'Carbone OMX','number_of_speeds'=>'12 vitesses Shimano Deore XT','suspension_type'=>'Fox 34 Float 130 mm / Fox Float DPS 130 mm','brake_style'=>'Hydraulique Shimano XT','power_source'=>'Batterie lithium-ion','motor_power'=>'Shimano EP8 RS 250 W / 85 Nm','battery_capacity'=>'360 Wh + Range Extender possible','max_speed'=>'25 km/h','max_range'=>'100 km avec Range Extender','charging_time'=>'2h30','weight'=>'19,5 kg','warranty_type'=>'Garantie Orbea 5 ans','colors'=>'Bleu,Vert,Noir','sizes'=>'XS,S,M,L,XL','images'=>[$imgElec,$imgElec2]]);

        $make(['cat'=>'electrique','brand'=>'Coboc','name'=>'Coboc ONE Camden E-Bike Minimaliste','name_de'=>'Coboc ONE Camden E-Bike Minimalistisch','slug'=>'coboc-one-camden-e-bike-minimaliste','description'=>'Le Coboc ONE Camden est un vélo électrique minimaliste allemand d\'une beauté rare. Son design épuré cache une assistance électrique discrète et une batterie intégrée dans le cadre, pour un vélo urbain à la fois élégant et efficace.','description_de'=>'Das Coboc ONE Camden ist ein minimalistisches deutsches E-Bike von seltener Schönheit. Klares Design versteckt dezente E-Unterstützung und Rahmenakku für ein elegantes und effizientes Stadtrad.','price'=>3999.00,'sale_price'=>null,'is_new'=>true,'is_featured'=>false,'bike_type'=>'E-Bike urbain minimaliste','wheel_size'=>'28"','frame_material'=>'Aluminium','number_of_speeds'=>'1 vitesse (single speed)','suspension_type'=>'Rigide','brake_style'=>'Disque hydraulique Magura','power_source'=>'Batterie intégrée dans le tube diagonal','motor_power'=>'Moteur arrière Coboc 250 W / 40 Nm','battery_capacity'=>'252 Wh','max_speed'=>'25 km/h','max_range'=>'60 km','charging_time'=>'3h','weight'=>'16,8 kg','warranty_type'=>'Garantie Coboc 2 ans','colors'=>'Noir mat,Blanc,Kaki','sizes'=>'S,M,L','images'=>[$imgElec2,$imgVille]]);

        $make(['cat'=>'electrique','brand'=>'VanMoof','name'=>'VanMoof S5 E-Bike Connecté','name_de'=>'VanMoof S5 Vernetztes E-Bike','slug'=>'vanmoof-s5-e-bike-connecte','description'=>'Le VanMoof S5 est le vélo électrique hollandais ultra-connecté. Avec son antivol intégré, son suivi GPS, son application dédiée et son design iconique, il révolutionne le concept de vélo urbain.','description_de'=>'Das VanMoof S5 ist das ultra-vernetzte niederländische E-Bike. Integriertes Schloss, GPS-Tracking, dedizierte App und ikonisches Design revolutionieren das Stadtrad-Konzept.','price'=>2999.00,'sale_price'=>2499.00,'is_new'=>false,'is_featured'=>false,'bike_type'=>'E-Bike connecté','wheel_size'=>'28"','frame_material'=>'Aluminium','number_of_speeds'=>'4 vitesses automatiques','suspension_type'=>'Rigide','brake_style'=>'Disque hydraulique Tektro','power_source'=>'Batterie lithium-ion intégrée','motor_power'=>'Moteur avant VanMoof 250 W / 59 Nm','battery_capacity'=>'432 Wh','max_speed'=>'25 km/h','max_range'=>'60 km','charging_time'=>'4h','weight'=>'23,9 kg','warranty_type'=>'Garantie VanMoof 2 ans','colors'=>'Noir,Blanc','sizes'=>'S/M,M/L','images'=>[$imgElec,$imgVille]]);

        $make(['cat'=>'electrique','brand'=>'BMC','name'=>'BMC Roadmachine AMP ONE E-Route','name_de'=>'BMC Roadmachine AMP ONE E-Rennrad','slug'=>'bmc-roadmachine-amp-one-e-route','description'=>'Le BMC Roadmachine AMP ONE est le vélo de route électrique suisse ultime. Son moteur Fazua Ride 60 ultra-léger et sa batterie amovible lui confèrent les performances d\'un vélo de route classique avec l\'assistance électrique en bonus.','description_de'=>'Das BMC Roadmachine AMP ONE ist das ultimative Schweizer E-Rennrad. Ultra-leichter Fazua Ride 60 Motor und abnehmbarer Akku für klassische Rennrad-Performance mit E-Unterstützung.','price'=>8499.00,'sale_price'=>null,'is_new'=>true,'is_featured'=>true,'bike_type'=>'E-Route carbone','wheel_size'=>'700c','frame_material'=>'Carbone ACE (Advanced Composite Engineering)','number_of_speeds'=>'22 vitesses Shimano Ultegra Di2','suspension_type'=>'Rigide','brake_style'=>'Disque hydraulique Shimano Ultegra','power_source'=>'Batterie amovible Fazua','motor_power'=>'Fazua Ride 60 250 W / 60 Nm','battery_capacity'=>'430 Wh','max_speed'=>'25 km/h','max_range'=>'100 km en mode Breeze','charging_time'=>'3h','weight'=>'11,8 kg','warranty_type'=>'Garantie BMC 5 ans','colors'=>'Noir/Rouge,Gris/Bleu','sizes'=>'44,47,51,54,56','images'=>[$imgElec2,$imgRoute]]);

        $make(['cat'=>'electrique','brand'=>'Gazelle','name'=>'Gazelle Ultimate T10 HMB E-Trekking','name_de'=>'Gazelle Ultimate T10 HMB E-Trekking','slug'=>'gazelle-ultimate-t10-hmb-e-trekking','description'=>'Le Gazelle Ultimate T10 HMB est le vélo de trekking électrique hollandais de référence. Son moteur Bosch Performance Line Speed et sa transmission 10 vitesses internes offrent un confort et une fiabilité inégalés.','description_de'=>'Das Gazelle Ultimate T10 HMB ist das niederländische Referenz-E-Trekkingbike. Bosch Performance Line Speed Motor und 10-Gang-Internalschaltung für unübertroffenen Komfort.','price'=>4299.00,'sale_price'=>3799.00,'is_new'=>false,'is_featured'=>false,'bike_type'=>'E-Trekking','wheel_size'=>'28"','frame_material'=>'Aluminium renforcé','number_of_speeds'=>'10 vitesses Enviolo','suspension_type'=>'Fourche suspendue 63 mm','brake_style'=>'Disque hydraulique Shimano Deore','power_source'=>'Batterie Bosch intégrée','motor_power'=>'Bosch Performance Line Speed 250 W / 65 Nm','battery_capacity'=>'750 Wh','max_speed'=>'25 km/h','max_range'=>'140 km en mode Eco','charging_time'=>'5h','weight'=>'28,2 kg','warranty_type'=>'Garantie Gazelle 2 ans + Bosch 2 ans','colors'=>'Noir,Gris,Bleu','sizes'=>'49,54,57','images'=>[$imgElec,$imgVille]]);

        $make(['cat'=>'electrique','brand'=>'Moustache','name'=>'Moustache Samedi 28.7 Open E-Bike','name_de'=>'Moustache Samedi 28.7 Open E-Bike','slug'=>'moustache-samedi-28-7-open-e-bike','description'=>'Le Moustache Samedi 28.7 Open est le fleuron du fabricant français de vélos électriques. Fabriqué à Épinal, il représente le savoir-faire français avec un moteur Bosch Performance CX et une finition irréprochable.','description_de'=>'Das Moustache Samedi 28.7 Open ist das Flaggschiff des französischen E-Bike-Herstellers. In Épinal gefertigt, mit Bosch Performance CX Motor und tadelloser Verarbeitung.','price'=>3999.00,'sale_price'=>null,'is_new'=>true,'is_featured'=>false,'bike_type'=>'E-Bike Trekking','wheel_size'=>'28"','frame_material'=>'Aluminium','number_of_speeds'=>'11 vitesses Shimano Deore','suspension_type'=>'Fourche suspendue 63 mm','brake_style'=>'Disque hydraulique Shimano Deore','power_source'=>'Batterie Bosch intégrée','motor_power'=>'Bosch Performance CX 250 W / 85 Nm','battery_capacity'=>'625 Wh','max_speed'=>'25 km/h','max_range'=>'120 km en mode Eco','charging_time'=>'4h30','weight'=>'25,4 kg','warranty_type'=>'Garantie Moustache 2 ans + Bosch 2 ans','colors'=>'Vert,Gris,Noir','sizes'=>'40,44,48,52,56','images'=>[$imgElec2,$imgElec]]);

        // ═══════════════════════════════════════════════
        // ██ BMX — 5 produits supplémentaires
        // ═══════════════════════════════════════════════

        $make(['cat'=>'bmx','brand'=>'Colony','name'=>'Colony Apprentice 20" Freestyle','name_de'=>'Colony Apprentice 20" Freestyle','slug'=>'colony-apprentice-20-freestyle','description'=>'Le Colony Apprentice est un BMX freestyle australien robuste et abordable, parfait pour les débutants et riders intermédiaires. Son cadre acier Hi-Ten et ses composants durables lui permettent d\'encaisser tous les tricks.','description_de'=>'Das Colony Apprentice ist ein robustes und erschwingliches australisches Freestyle-BMX, perfekt für Anfänger und Fortgeschrittene. Hi-Ten Stahlrahmen und langlebige Komponenten.','price'=>449.00,'sale_price'=>369.00,'is_new'=>false,'is_featured'=>false,'bike_type'=>'BMX Freestyle','wheel_size'=>'20"','frame_material'=>'Acier Hi-Ten','number_of_speeds'=>'1 vitesse','suspension_type'=>'Rigide','brake_style'=>'Patins V-Brake arrière','weight'=>'12,1 kg','warranty_type'=>'Garantie 1 an','colors'=>'Noir,Rouge,Bleu,Argent','images'=>[$imgBMX]]);

        $make(['cat'=>'bmx','brand'=>'Subrosa','name'=>'Subrosa Salvador Park 20"','name_de'=>'Subrosa Salvador Park 20"','slug'=>'subrosa-salvador-park-20','description'=>'Le Subrosa Salvador Park est un BMX freestyle américain pour le skatepark. Sa géométrie park-optimisée et son cadre Chromoly léger en font le choix idéal pour les riders qui veulent performer dans les bowls et les rampes.','description_de'=>'Das Subrosa Salvador Park ist ein amerikanisches Freestyle-BMX für den Skatepark. Park-optimierte Geometrie und leichter Chromoly-Rahmen für Fahrer in Bowls und Rampen.','price'=>599.00,'sale_price'=>null,'is_new'=>true,'is_featured'=>false,'bike_type'=>'BMX Park','wheel_size'=>'20"','frame_material'=>'Acier Chromoly 4130','number_of_speeds'=>'1 vitesse','suspension_type'=>'Rigide','brake_style'=>'Patins arrière + rotor','weight'=>'10,8 kg','warranty_type'=>'Garantie Subrosa 1 an','colors'=>'Noir,Blanc,Vert','images'=>[$imgBMX]]);

        $make(['cat'=>'bmx','brand'=>'Haro','name'=>'Haro Leucadia DLX 26" Cruiser','name_de'=>'Haro Leucadia DLX 26" Cruiser','slug'=>'haro-leucadia-dlx-26-cruiser','description'=>'Le Haro Leucadia DLX est un BMX cruiser américain polyvalent. Ses grandes roues de 26" offrent confort et polyvalence pour rouler aussi bien au skatepark qu\'en extérieur sur des chemins.','description_de'=>'Das Haro Leucadia DLX ist ein vielseitiges amerikanisches BMX-Cruiser. Die großen 26"-Räder bieten Komfort und Vielseitigkeit für Skatepark und Außengelände.','price'=>549.00,'sale_price'=>null,'is_new'=>false,'is_featured'=>false,'bike_type'=>'BMX Cruiser','wheel_size'=>'26"','frame_material'=>'Acier Chromoly 4130','number_of_speeds'=>'1 vitesse','suspension_type'=>'Rigide','brake_style'=>'Patins avant et arrière','weight'=>'12,5 kg','warranty_type'=>'Garantie Haro 1 an','colors'=>'Noir,Chrome,Bleu','images'=>[$imgBMX]]);

        // ═══════════════════════════════════════════════
        // ██ ENFANT — 8 produits supplémentaires
        // ═══════════════════════════════════════════════

        $make(['cat'=>'enfant','brand'=>'Frog Bikes','name'=>'Frog 70 Vélo Enfant 26"','name_de'=>'Frog 70 Kinderfahrrad 26"','slug'=>'frog-bikes-frog-70-26','description'=>'Le Frog 70 est un vélo pour enfants de 10 à 14 ans conçu par la marque britannique spécialisée. Ultra-léger pour sa taille (seulement 8,6 kg), il permet aux jeunes cyclistes de progresser rapidement et en toute confiance.','description_de'=>'Das Frog 70 ist ein Kinderfahrrad für 10 bis 14-Jährige von der britischen Spezialmarke. Ultra-leicht (nur 8,6 kg) ermöglicht jungen Radfahrern schnellen Fortschritt.','price'=>649.00,'sale_price'=>549.00,'is_new'=>false,'is_featured'=>false,'bike_type'=>'Vélo enfant','wheel_size'=>'26"','age_range'=>'10 – 14 ans','frame_material'=>'Aluminium ultra-léger','number_of_speeds'=>'8 vitesses Shimano','suspension_type'=>'Rigide','brake_style'=>'Disque mécanique','weight'=>'8,6 kg','max_load'=>'75 kg','warranty_type'=>'Garantie Frog 2 ans','colors'=>'Rouge,Bleu,Vert,Noir','images'=>[$imgEnfant]]);

        $make(['cat'=>'enfant','brand'=>'woom','name'=>'woom 4 Vélo Enfant 20"','name_de'=>'woom 4 Kinderfahrrad 20"','slug'=>'woom-4-velo-enfant-20','description'=>'Le woom 4 est le vélo autrichien légendaire pour enfants de 6 à 9 ans. Conçu spécifiquement pour les enfants (composants adaptés à leur morphologie), il est reconnu mondialement comme le meilleur vélo enfant.','description_de'=>'Das woom 4 ist das legendäre österreichische Kinderfahrrad für 6 bis 9-Jährige. Speziell für Kinder entwickelt (angepasste Komponenten), weltweit als bestes Kinderrad anerkannt.','price'=>449.00,'sale_price'=>null,'is_new'=>false,'is_featured'=>true,'bike_type'=>'Vélo enfant','wheel_size'=>'20"','age_range'=>'6 – 9 ans','frame_material'=>'Aluminium léger','number_of_speeds'=>'7 vitesses Shimano','suspension_type'=>'Rigide','brake_style'=>'Patins avant/arrière ajustés enfant','weight'=>'6,9 kg','max_load'=>'50 kg','warranty_type'=>'Garantie woom 2 ans','colors'=>'Orange,Bleu,Rouge,Vert','images'=>[$imgEnfant]]);

        $make(['cat'=>'enfant','brand'=>'woom','name'=>'woom 5 Vélo Enfant 24"','name_de'=>'woom 5 Kinderfahrrad 24"','slug'=>'woom-5-velo-enfant-24','description'=>'Le woom 5 est le vélo pour enfants de 8 à 11 ans de la marque autrichienne. Avec sa transmission 8 vitesses et ses freins adaptés aux petites mains, il grandit avec l\'enfant et lui offre une expérience de conduite idéale.','description_de'=>'Das woom 5 ist das Kinderfahrrad für 8 bis 11-Jährige der österreichischen Marke. Mit 8-Gang-Schaltung und kinderhanden-angepassten Bremsen wächst es mit dem Kind.','price'=>499.00,'sale_price'=>null,'is_new'=>false,'is_featured'=>false,'bike_type'=>'Vélo enfant','wheel_size'=>'24"','age_range'=>'8 – 11 ans','frame_material'=>'Aluminium léger','number_of_speeds'=>'8 vitesses Shimano','suspension_type'=>'Rigide','brake_style'=>'Patins ajustés enfant','weight'=>'7,6 kg','max_load'=>'60 kg','warranty_type'=>'Garantie woom 2 ans','colors'=>'Orange,Bleu,Rouge,Vert,Blanc','images'=>[$imgEnfant]]);

        $make(['cat'=>'enfant','brand'=>'Orbea','name'=>'Orbea MX 24 XC Enfant VTT','name_de'=>'Orbea MX 24 XC Kinder-MTB','slug'=>'orbea-mx-24-xc-enfant-vtt','description'=>'L\'Orbea MX 24 XC est un VTT pour enfants de 9 à 13 ans de qualité premium. Avec sa fourche suspendue et ses composants Shimano, il offre une vraie expérience VTT pour les jeunes riders en herbe.','description_de'=>'Das Orbea MX 24 XC ist ein Premium-Kinder-MTB für 9 bis 13-Jährige. Mit Federgabel und Shimano-Komponenten bietet es ein echtes MTB-Erlebnis für junge Fahrer.','price'=>549.00,'sale_price'=>489.00,'is_new'=>false,'is_featured'=>false,'bike_type'=>'VTT enfant','wheel_size'=>'24"','age_range'=>'9 – 13 ans','frame_material'=>'Aluminium 6061','number_of_speeds'=>'8 vitesses Shimano Altus','suspension_type'=>'Fourche suspendue 50 mm','brake_style'=>'Disque mécanique','weight'=>'10,8 kg','max_load'=>'65 kg','warranty_type'=>'Garantie Orbea 5 ans','colors'=>'Rouge,Bleu,Noir','images'=>[$imgEnfant]]);

        $make(['cat'=>'enfant','brand'=>'Islabikes','name'=>'Islabikes Beinn 20 Small Vélo Enfant','name_de'=>'Islabikes Beinn 20 Small Kinderfahrrad','slug'=>'islabikes-beinn-20-small','description'=>'L\'Islabikes Beinn 20 Small est un vélo britannique de haute qualité conçu spécifiquement pour les enfants de 5 à 8 ans. Sa légèreté exceptionnelle et ses composants adaptés en font le choix des parents les plus exigeants.','description_de'=>'Das Islabikes Beinn 20 Small ist ein britisches Qualitäts-Kinderfahrrad für 5 bis 8-Jährige. Außergewöhnliche Leichtigkeit und angepasste Komponenten für anspruchsvolle Eltern.','price'=>399.00,'sale_price'=>null,'is_new'=>false,'is_featured'=>false,'bike_type'=>'Vélo enfant','wheel_size'=>'20"','age_range'=>'5 – 8 ans','frame_material'=>'Aluminium léger','number_of_speeds'=>'6 vitesses','suspension_type'=>'Rigide','brake_style'=>'Patins ajustés enfant','weight'=>'6,2 kg','max_load'=>'45 kg','warranty_type'=>'Garantie Islabikes 2 ans','colors'=>'Rouge,Bleu,Vert','images'=>[$imgEnfant]]);

        // ═══════════════════════════════════════════════
        // ██ RECONDITIONNÉ — 5 produits supplémentaires
        // ═══════════════════════════════════════════════

        $make(['cat'=>'reconditionne','brand'=>'Specialized','name'=>'Specialized Stumpjumper 29" Reconditionné Grade A','name_de'=>'Specialized Stumpjumper 29" Generalüberholt Klasse A','slug'=>'specialized-stumpjumper-29-reconditionne-a','description'=>'Ce Specialized Stumpjumper reconditionné Grade A a été entièrement révisé par nos techniciens certifiés. Transmission, freins et suspension fonctionnent comme neufs. Le cadre ne présente aucun défaut structurel. Une occasion exceptionnelle.','description_de'=>'Dieses generalüberholte Specialized Stumpjumper Klasse A wurde vollständig von unseren zertifizierten Technikern überholt. Antrieb, Bremsen und Federung funktionieren wie neu.','price'=>2299.00,'sale_price'=>1799.00,'is_new'=>false,'is_featured'=>false,'bike_type'=>'Trail Tout-suspendu (reconditionné)','wheel_size'=>'29"','frame_material'=>'Aluminium M5','number_of_speeds'=>'12 vitesses SRAM','suspension_type'=>'RockShox Pike 140 mm / Deluxe','brake_style'=>'Hydraulique SRAM G2','weight'=>'14,2 kg','warranty_type'=>'Garantie reconditionnement 6 mois','colors'=>'Bleu','images'=>[$imgRecon,$imgVTT]]);

        $make(['cat'=>'reconditionne','brand'=>'Trek','name'=>'Trek FX 3 Disc Reconditionné Grade B','name_de'=>'Trek FX 3 Disc Generalüberholt Klasse B','slug'=>'trek-fx3-disc-reconditionne-grade-b','description'=>'Ce Trek FX 3 Disc reconditionné Grade B présente des rayures légères sur le cadre mais est fonctionnellement parfait. Tous les composants ont été vérifiés et les pièces d\'usure remplacées. Un excellent rapport qualité/prix.','description_de'=>'Dieses generalüberholte Trek FX 3 Disc Klasse B weist leichte Kratzer am Rahmen auf, ist aber funktionell einwandfrei. Alle Komponenten geprüft, Verschleißteile ersetzt.','price'=>599.00,'sale_price'=>449.00,'is_new'=>false,'is_featured'=>false,'bike_type'=>'Vélo de ville/fitness (reconditionné)','wheel_size'=>'700c','frame_material'=>'Aluminium','number_of_speeds'=>'24 vitesses Shimano','suspension_type'=>'Fourche rigide','brake_style'=>'Disque hydraulique','weight'=>'11,1 kg','warranty_type'=>'Garantie reconditionnement 6 mois','colors'=>'Gris','images'=>[$imgRecon,$imgVille]]);

        $make(['cat'=>'reconditionne','brand'=>'Cannondale','name'=>'Cannondale SuperSix EVO Carbon Reconditionné A','name_de'=>'Cannondale SuperSix EVO Carbon Generalüberholt A','slug'=>'cannondale-supersix-evo-carbon-reconditionne-a','description'=>'Ce Cannondale SuperSix EVO carbone reconditionné Grade A est une occasion rare. Après révision complète, la transmission Shimano Ultegra et les freins à disque sont parfaitement fonctionnels. Le cadre carbone est intact.','description_de'=>'Dieses generalüberholte Cannondale SuperSix EVO Carbon Klasse A ist eine seltene Gelegenheit. Nach vollständiger Überholung funktionieren Shimano Ultegra und Scheibenbremsen perfekt.','price'=>2499.00,'sale_price'=>1999.00,'is_new'=>false,'is_featured'=>false,'bike_type'=>'Vélo de route carbone (reconditionné)','wheel_size'=>'700c','frame_material'=>'Carbone BallisTec','number_of_speeds'=>'22 vitesses Shimano Ultegra','suspension_type'=>'Rigide','brake_style'=>'Disque hydraulique Shimano Ultegra','weight'=>'7,8 kg','warranty_type'=>'Garantie reconditionnement 6 mois','colors'=>'Noir/Vert','images'=>[$imgRecon,$imgRoute]]);

        $make(['cat'=>'reconditionne','brand'=>'Giant','name'=>'Giant Explore E+ 1 Pro E-Bike Reconditionné B','name_de'=>'Giant Explore E+ 1 Pro E-Bike Generalüberholt B','slug'=>'giant-explore-e-plus-1-pro-reconditionne-b','description'=>'Ce Giant Explore E+ 1 Pro reconditionné Grade B présente quelques marques d\'utilisation visible mais la batterie conserve 92% de sa capacité d\'origine. Moteur et électronique en parfait état de fonctionnement.','description_de'=>'Dieses generalüberholte Giant Explore E+ 1 Pro Klasse B zeigt sichtbare Gebrauchsspuren, aber der Akku behält 92% seiner ursprünglichen Kapazität. Motor und Elektronik einwandfrei.','price'=>2499.00,'sale_price'=>1899.00,'is_new'=>false,'is_featured'=>false,'bike_type'=>'E-Bike trekking (reconditionné)','wheel_size'=>'700c','frame_material'=>'Aluminium','number_of_speeds'=>'11 vitesses Shimano','suspension_type'=>'Fourche suspendue','brake_style'=>'Disque hydraulique','power_source'=>'Batterie lithium-ion','motor_power'=>'Giant SyncDrive Pro2 250 W / 80 Nm','battery_capacity'=>'500 Wh (92% capacité)','max_speed'=>'25 km/h','max_range'=>'90 km en mode Eco','charging_time'=>'4h','weight'=>'22,5 kg','warranty_type'=>'Garantie reconditionnement 6 mois','colors'=>'Noir','images'=>[$imgRecon,$imgElec]]);

        $make(['cat'=>'reconditionne','brand'=>'BMX','name'=>'Mongoose Legion L80 20" Reconditionné','name_de'=>'Mongoose Legion L80 20" Generalüberholt','slug'=>'mongoose-legion-l80-reconditionne','description'=>'Ce Mongoose Legion L80 reconditionné est en excellent état cosmétique et mécanique. Tous les roulements ont été remplacés et les câbles refaits. Un BMX de qualité à prix réduit pour les riders soucieux de leur budget.','description_de'=>'Dieses generalüberholte Mongoose Legion L80 ist in ausgezeichnetem Zuststand. Alle Lager ersetzt und Kabel erneuert. Qualitäts-BMX zum günstigen Preis.','price'=>299.00,'sale_price'=>249.00,'is_new'=>false,'is_featured'=>false,'bike_type'=>'BMX Freestyle (reconditionné)','wheel_size'=>'20"','frame_material'=>'Acier Chromoly','number_of_speeds'=>'1 vitesse','suspension_type'=>'Rigide','brake_style'=>'Patins arrière','weight'=>'10,9 kg','warranty_type'=>'Garantie reconditionnement 3 mois','colors'=>'Noir/Rouge','images'=>[$imgRecon,$imgBMX]]);

        $count = Product::count();
        $imgs  = ProductImage::count();
        $this->command->info("✅ Seeder terminé !");
        $this->command->info("   🚲 Total produits en BDD : {$count}");
        $this->command->info("   🖼  Total images en BDD  : {$imgs}");
    }
}