<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Product;
use App\Models\Category;
use App\Models\ProductImage;

/**
 * ╔══════════════════════════════════════════════════════════════╗
 * ║  MegaBikeSeeder — 200+ vélos, images réelles de vélos       ║
 * ║                                                              ║
 * ║  LANCEMENT :                                                 ║
 * ║    php artisan db:seed --class=MegaBikeSeeder               ║
 * ║                                                              ║
 * ║  ⚠️  REMET À ZÉRO la BDD (products + images)               ║
 * ╚══════════════════════════════════════════════════════════════╝
 */
class MegaBikeSeeder extends Seeder
{
    // ─── Images Unsplash 100% vélos ───────────────────────────
    // Chaque constante est une vraie photo de vélo
    const IMGS = [
        'vtt_a'    => 'https://images.unsplash.com/photo-1544191696-102dbdaeeaa0?w=900&q=85',
        'vtt_b'    => 'https://images.unsplash.com/photo-1576435728678-68d0fbf94946?w=900&q=85',
        'vtt_c'    => 'https://images.unsplash.com/photo-1553764854-53ac4f1e175b?w=900&q=85',
        'vtt_d'    => 'https://images.unsplash.com/photo-1571333250630-f0230c320b6d?w=900&q=85',
        'vtt_e'    => 'https://images.unsplash.com/photo-1559348349-86f1f65817fe?w=900&q=85',
        'vtt_f'    => 'https://images.unsplash.com/photo-1511994298241-608e28f14fde?w=900&q=85',
        'route_a'  => 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=900&q=85',
        'route_b'  => 'https://images.unsplash.com/photo-1526307616774-60d0098f7642?w=900&q=85',
        'route_c'  => 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=900&q=85',
        'gravel_a' => 'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=900&q=85',
        'gravel_b' => 'https://images.unsplash.com/photo-1516733725897-1aa73b87c8e8?w=900&q=85',
        'ville_a'  => 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=900&q=85',
        'ville_b'  => 'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=900&q=85',
        'enfant_a' => 'https://images.unsplash.com/photo-1503455637927-730bce8583c0?w=900&q=85',
        'elec_a'   => 'https://images.unsplash.com/photo-1617788138017-80ad40651399?w=900&q=85',
        'elec_b'   => 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=900&q=85',
        'bmx_a'    => 'https://images.unsplash.com/photo-1486427944299-d1955d23e34d?w=900&q=85',
        'recon_a'  => 'https://images.unsplash.com/photo-1544191696-102dbdaeeaa0?w=900&q=85',
    ];

    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        ProductImage::truncate();
        Product::truncate();
        Category::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        // ── Catégories ────────────────────────────────────────
        $cats = [
            ['name'=>'VTT',           'name_de'=>'Mountainbike',   'slug'=>'vtt',          'description'=>'Vélos tout-terrain pour trails et sentiers',           'description_de'=>'Geländefahrräder für Trails und Wege'],
            ['name'=>'Route',         'name_de'=>'Rennrad',         'slug'=>'route',        'description'=>'Vélos de route légers et performants',                 'description_de'=>'Leichte und leistungsstarke Rennräder'],
            ['name'=>'Gravel',        'name_de'=>'Gravel',          'slug'=>'gravel',       'description'=>'Vélos polyvalents route et chemins',                   'description_de'=>'Vielseitige Räder für Straße und Wege'],
            ['name'=>'Ville',         'name_de'=>'Stadtrad',        'slug'=>'ville',        'description'=>'Vélos urbains et de déplacement quotidien',            'description_de'=>'Stadträder für den täglichen Einsatz'],
            ['name'=>'Électrique',    'name_de'=>'E-Bike',          'slug'=>'electrique',   'description'=>'Vélos à assistance électrique toutes catégories',      'description_de'=>'Elektrofahrräder aller Kategorien'],
            ['name'=>'BMX',           'name_de'=>'BMX',             'slug'=>'bmx',          'description'=>'BMX freestyle et race pour tous niveaux',              'description_de'=>'BMX Freestyle und Race für alle Niveaus'],
            ['name'=>'Enfant',        'name_de'=>'Kinderrad',       'slug'=>'enfant',       'description'=>'Vélos et draisiennes pour les enfants',                'description_de'=>'Fahrräder und Laufräder für Kinder'],
            ['name'=>'Reconditionné', 'name_de'=>'Generalüberholt', 'slug'=>'reconditionne','description'=>'Vélos reconditionnés certifiés par nos techniciens',   'description_de'=>'Von unseren Technikern zertifizierte Räder'],
        ];
        foreach ($cats as $c) Category::create($c);
        $cid = Category::pluck('id', 'slug');

        // ── Helper ────────────────────────────────────────────
        $add = function(array $d) use ($cid) {
            $imgs   = $d['imgs']   ?? [];
            $colors = $d['colors'] ?? [];
            $cat    = $d['cat'];
            unset($d['imgs'], $d['colors'], $d['cat']);

            if (Product::where('slug', $d['slug'])->exists()) return;

            $p = Product::create(array_merge([
                'category_id'       => $cid[$cat] ?? null,
                'sale_price'        => null,
                'is_featured'       => false,
                'is_new'            => false,
                'assembly_required' => false,
                'stock'             => rand(3, 25),
                'year'              => '2025',
                'is_active'         => true,
                'colors'            => implode(',', $colors),
            ], $d));

            // Image principale + images par couleur
            foreach ($imgs as $i => [$url, $color]) {
                ProductImage::create([
                    'product_id' => $p->id,
                    'image_path' => $url,
                    'is_primary' => $i === 0,
                    'sort_order' => $i,
                    'color'      => $color,
                ]);
            }
        };

        $I = self::IMGS;

        // ════════════════════════════════════════════════════════
        // ██ VTT — 55 produits
        // ════════════════════════════════════════════════════════

        // ── Trek ──
        $add(['cat'=>'vtt','brand'=>'Trek','name'=>'Trek Marlin 7 Gen 3 29"','name_de'=>'Trek Marlin 7 Gen 3 29"','slug'=>'trek-marlin-7-29','description'=>'Le VTT hardtail parfait pour débuter sur les sentiers. Fourche RockShox Judy 100mm, transmission Shimano Deore 2×10, cadre aluminium Alpha Platinum.','description_de'=>'Das perfekte Hardtail-MTB für den Trailseinstieg. RockShox Judy 100mm Gabel, Shimano Deore 2×10, Alpha Platinum Aluminiumrahmen.','price'=>1299.00,'sale_price'=>999.00,'is_featured'=>true,'is_new'=>false,'bike_type'=>'Hardtail VTT','wheel_size'=>'29"','frame_material'=>'Aluminium Alpha Platinum','number_of_speeds'=>'20 vitesses Shimano Deore','suspension_type'=>'RockShox Judy 100mm','brake_style'=>'Hydraulique Shimano MT200','weight'=>'14,2 kg','warranty_type'=>'Garantie Trek à vie','colors'=>['Noir','Bleu','Rouge'],'imgs'=>[[$I['vtt_a'],'Noir'],[$I['vtt_b'],'Bleu'],[$I['vtt_c'],'Rouge']],'sizes'=>'S,M,L,XL,XXL']);

        $add(['cat'=>'vtt','brand'=>'Trek','name'=>'Trek Roscoe 8 27.5"+ Fat','name_de'=>'Trek Roscoe 8 27.5"+ Fat','slug'=>'trek-roscoe-8-275','description'=>'VTT hardtail fat-tire avec fourche RockShox Judy 120mm. Pneus 27,5+ pour une adhérence exceptionnelle sur tous les terrains.','description_de'=>'Fat-Tire Hardtail-MTB mit RockShox Judy 120mm Gabel. 27,5+ Reifen für außergewöhnlichen Grip.','price'=>1499.00,'sale_price'=>1199.00,'bike_type'=>'Hardtail Fat','wheel_size'=>'27.5"+','frame_material'=>'Aluminium Alpha Gold','number_of_speeds'=>'12 vitesses Shimano Deore','suspension_type'=>'RockShox Judy 120mm','brake_style'=>'Hydraulique Shimano MT200','weight'=>'14,8 kg','warranty_type'=>'Garantie Trek à vie','colors'=>['Noir','Bleu'],'imgs'=>[[$I['vtt_a'],'Noir'],[$I['vtt_b'],'Bleu']],'sizes'=>'S,M,L,XL']);

        $add(['cat'=>'vtt','brand'=>'Trek','name'=>'Trek Slash 9.8 GX AXS 29"','name_de'=>'Trek Slash 9.8 GX AXS 29"','slug'=>'trek-slash-9-8-gx-axs','description'=>'VTT enduro haut de gamme avec 160mm de débattement, groupe SRAM GX AXS électronique, cadre carbone OCLV 600.','description_de'=>'Premium-Enduro-MTB mit 160mm Federweg, elektronischer SRAM GX AXS Gruppe und OCLV 600 Carbon-Rahmen.','price'=>5999.00,'sale_price'=>null,'is_new'=>true,'is_featured'=>true,'bike_type'=>'Enduro Carbone','wheel_size'=>'29"','frame_material'=>'Carbone OCLV 600','number_of_speeds'=>'12 vitesses SRAM GX AXS','suspension_type'=>'Fox 36 Factory 160mm / Fox Float X2 160mm','brake_style'=>'Hydraulique SRAM Code RSC','weight'=>'13,2 kg','warranty_type'=>'Garantie Trek à vie carbone','colors'=>['Noir','Gris'],'imgs'=>[[$I['vtt_d'],'Noir'],[$I['vtt_c'],'Gris']],'sizes'=>'S,M,L,XL']);

        $add(['cat'=>'vtt','brand'=>'Trek','name'=>'Trek Fuel EX 8 XT 29"','name_de'=>'Trek Fuel EX 8 XT 29"','slug'=>'trek-fuel-ex-8-xt-29','description'=>'Trail bike tout-suspendu 130mm avec groupe Shimano XT 12 vitesses. La référence pour les sentiers techniques.','description_de'=>'130mm Fully-Trail-Bike mit Shimano XT 12-Gang. Die Referenz für technische Trails.','price'=>3499.00,'sale_price'=>2999.00,'bike_type'=>'Trail Tout-suspendu','wheel_size'=>'29"','frame_material'=>'Aluminium Alpha Platinum','number_of_speeds'=>'12 vitesses Shimano Deore XT','suspension_type'=>'Fox 34 Float 130mm / Fox Float DPS 130mm','brake_style'=>'Hydraulique Shimano XT 4 pistons','weight'=>'13,8 kg','warranty_type'=>'Garantie Trek à vie','colors'=>['Vert','Noir','Bleu'],'imgs'=>[[$I['vtt_d'],'Vert'],[$I['vtt_a'],'Noir'],[$I['vtt_b'],'Bleu']],'sizes'=>'S,M,L,XL']);

        $add(['cat'=>'vtt','brand'=>'Trek','name'=>'Trek Procaliber 9.7 29" XC','name_de'=>'Trek Procaliber 9.7 29" XC','slug'=>'trek-procaliber-9-7-xc','description'=>'VTT XC hardtail carbone ultra-léger. IsoSpeed découplé pour absorber les vibrations sur les pistes de cross-country.','description_de'=>'Ultra-leichtes Carbon-XC-Hardtail. IsoSpeed für Vibrationsabsorption auf XC-Strecken.','price'=>4299.00,'sale_price'=>null,'is_new'=>true,'bike_type'=>'XC Hardtail Carbone','wheel_size'=>'29"','frame_material'=>'Carbone OCLV 500','number_of_speeds'=>'12 vitesses Shimano Deore XT','suspension_type'=>'Fox 32 Float SC 100mm','brake_style'=>'Disque hydraulique Shimano XT','weight'=>'10,2 kg','warranty_type'=>'Garantie Trek à vie','colors'=>['Blanc','Noir'],'imgs'=>[[$I['vtt_f'],'Blanc'],[$I['vtt_a'],'Noir']],'sizes'=>'XS,S,M,L,XL,XXL']);

        // ── Specialized ──
        $add(['cat'=>'vtt','brand'=>'Specialized','name'=>'Specialized Stumpjumper Comp Alloy 29"','name_de'=>'Specialized Stumpjumper Comp Alloy 29"','slug'=>'specialized-stumpjumper-comp-alloy-29','description'=>'Trail bike tout-suspendu 140mm, groupe SRAM SX Eagle 12 vitesses, freins SRAM G2 R. L\'excellence du trail accessible.','description_de'=>'140mm Fully-Trail-Bike, SRAM SX Eagle 12-Gang, SRAM G2 R Bremsen. Excellence auf dem Trail.','price'=>3299.00,'sale_price'=>null,'is_featured'=>true,'is_new'=>true,'bike_type'=>'Trail Tout-suspendu','wheel_size'=>'29"','frame_material'=>'Aluminium M5','number_of_speeds'=>'12 vitesses SRAM SX Eagle','suspension_type'=>'Fox 36 Rhythm 140mm / Fox Float DPS 140mm','brake_style'=>'Hydraulique SRAM G2 R','weight'=>'13,8 kg','warranty_type'=>'Garantie Specialized 5 ans','colors'=>['Bleu','Vert','Noir'],'imgs'=>[[$I['vtt_b'],'Bleu'],[$I['vtt_d'],'Vert'],[$I['vtt_a'],'Noir']],'sizes'=>'S,M,L,XL']);

        $add(['cat'=>'vtt','brand'=>'Specialized','name'=>'Specialized Epic World Cup Pro Carbon 29"','name_de'=>'Specialized Epic World Cup Pro Carbon 29"','slug'=>'specialized-epic-world-cup-pro-29','description'=>'Le vélo XC des champions du monde. Cadre FACT 12m, suspension Brain FSR 100mm, groupe SRAM XX AXS. La perfection en compétition.','description_de'=>'Das XC-Bike der Weltmeister. FACT 12m Carbon, Brain FSR 100mm, SRAM XX AXS. Perfektion im Wettkampf.','price'=>8999.00,'sale_price'=>null,'is_featured'=>true,'is_new'=>true,'bike_type'=>'XC Race Carbone','wheel_size'=>'29"','frame_material'=>'Carbone FACT 12m','number_of_speeds'=>'12 vitesses SRAM XX AXS','suspension_type'=>'Brain FSR 100mm','brake_style'=>'Hydraulique SRAM Level Ultimate','weight'=>'9,1 kg','warranty_type'=>'Garantie Specialized 5 ans','colors'=>['Blanc','Noir'],'imgs'=>[[$I['vtt_f'],'Blanc'],[$I['vtt_a'],'Noir']],'sizes'=>'S,M,L,XL']);

        $add(['cat'=>'vtt','brand'=>'Specialized','name'=>'Specialized Enduro Expert 29"','name_de'=>'Specialized Enduro Expert 29"','slug'=>'specialized-enduro-expert-29','description'=>'Enduro 170mm de débattement, groupe SRAM X01 Eagle, freins Code R 4 pistons. Pour les riders qui veulent tout donner en descente.','description_de'=>'170mm Enduro-Bike, SRAM X01 Eagle, Code R 4-Kolben Bremsen. Für Fahrer, die beim Abfahren alles geben.','price'=>4499.00,'sale_price'=>3899.00,'is_featured'=>true,'bike_type'=>'Enduro','wheel_size'=>'29"','frame_material'=>'Aluminium M5','number_of_speeds'=>'12 vitesses SRAM X01 Eagle','suspension_type'=>'Fox 38 Float 170mm / Fox Float X2 170mm','brake_style'=>'Hydraulique SRAM Code R 4 pistons','weight'=>'14,6 kg','warranty_type'=>'Garantie Specialized 5 ans','colors'=>['Bleu','Noir'],'imgs'=>[[$I['vtt_b'],'Bleu'],[$I['vtt_a'],'Noir']],'sizes'=>'S,M,L,XL']);

        $add(['cat'=>'vtt','brand'=>'Specialized','name'=>'Specialized Fuse Sport 27.5"','name_de'=>'Specialized Fuse Sport 27.5"','slug'=>'specialized-fuse-sport-275','description'=>'VTT hardtail agressif avec pneus 2,6" et suspension RockShox 140mm. Taillé pour les trails techniques et le flow.','description_de'=>'Aggressives Hardtail-MTB mit 2,6" Reifen und RockShox 140mm. Für technische Trails und Flow.','price'=>1299.00,'sale_price'=>null,'bike_type'=>'Hardtail Trail','wheel_size'=>'27.5"','frame_material'=>'Aluminium M4','number_of_speeds'=>'10 vitesses Shimano Deore','suspension_type'=>'RockShox Judy Gold 140mm','brake_style'=>'Hydraulique SRAM G2','weight'=>'13,5 kg','warranty_type'=>'Garantie Specialized 5 ans','colors'=>['Rouge','Noir'],'imgs'=>[[$I['vtt_c'],'Rouge'],[$I['vtt_a'],'Noir']],'sizes'=>'XS,S,M,L,XL']);

        // ── Giant ──
        $add(['cat'=>'vtt','brand'=>'Giant','name'=>'Giant Trance X Advanced Pro 29 1','name_de'=>'Giant Trance X Advanced Pro 29 1','slug'=>'giant-trance-x-advanced-pro-29-1','description'=>'Trail bike carbone 140mm, groupe SRAM X01 Eagle, géométrie Maestro. Légèreté et polyvalence pour les trails exigeants.','description_de'=>'140mm Carbon-Trail-Bike, SRAM X01 Eagle, Maestro Geometrie. Leichtigkeit und Vielseitigkeit.','price'=>5299.00,'sale_price'=>null,'is_new'=>true,'is_featured'=>false,'bike_type'=>'Trail Carbone','wheel_size'=>'29"','frame_material'=>'Carbone Advanced Grade Composite','number_of_speeds'=>'12 vitesses SRAM X01 Eagle','suspension_type'=>'Fox 36 Float 140mm / Maestro 140mm','brake_style'=>'Hydraulique SRAM Code R','weight'=>'12,9 kg','warranty_type'=>'Garantie Giant 5 ans','colors'=>['Noir','Vert'],'imgs'=>[[$I['vtt_a'],'Noir'],[$I['vtt_d'],'Vert']],'sizes'=>'S,M,L,XL']);

        $add(['cat'=>'vtt','brand'=>'Giant','name'=>'Giant Talon 1 29" 2025','name_de'=>'Giant Talon 1 29" 2025','slug'=>'giant-talon-1-29-2025','description'=>'Hardtail VTT entrée de gamme avec suspension SR Suntour 100mm. Parfait pour découvrir les sentiers.','description_de'=>'Einstiegs-Hardtail mit SR Suntour 100mm Federung. Perfekt für den Trailseinstieg.','price'=>899.00,'sale_price'=>749.00,'bike_type'=>'Hardtail VTT','wheel_size'=>'29"','frame_material'=>'Aluminium ALUXX','number_of_speeds'=>'21 vitesses Shimano Acera','suspension_type'=>'SR Suntour XCT 100mm','brake_style'=>'Disque mécanique Tektro','weight'=>'13,9 kg','warranty_type'=>'Garantie Giant 2 ans','colors'=>['Noir','Rouge','Bleu'],'imgs'=>[[$I['vtt_a'],'Noir'],[$I['vtt_c'],'Rouge'],[$I['vtt_b'],'Bleu']],'sizes'=>'S,M,L,XL']);

        $add(['cat'=>'vtt','brand'=>'Giant','name'=>'Giant Reign Advanced Pro 29 0','name_de'=>'Giant Reign Advanced Pro 29 0','slug'=>'giant-reign-advanced-pro-29-0','description'=>'Enduro carbone haut de gamme avec 160mm de débattement. Groupe SRAM XX1 Eagle et freins Shimano XTR.','description_de'=>'Premium Carbon-Enduro mit 160mm Federweg. SRAM XX1 Eagle und Shimano XTR Bremsen.','price'=>7499.00,'sale_price'=>null,'is_featured'=>true,'is_new'=>true,'bike_type'=>'Enduro Carbone','wheel_size'=>'29"','frame_material'=>'Carbone Advanced Grade','number_of_speeds'=>'12 vitesses SRAM XX1 Eagle','suspension_type'=>'Fox 38 Float Factory 160mm / Fox Float X2 160mm','brake_style'=>'Hydraulique Shimano XTR','weight'=>'12,6 kg','warranty_type'=>'Garantie Giant 5 ans','colors'=>['Noir','Bleu'],'imgs'=>[[$I['vtt_a'],'Noir'],[$I['vtt_b'],'Bleu']],'sizes'=>'S,M,L,XL']);

        // ── Santa Cruz ──
        $add(['cat'=>'vtt','brand'=>'Santa Cruz','name'=>'Santa Cruz Hightower CC X01 AXS 29"','name_de'=>'Santa Cruz Hightower CC X01 AXS 29"','slug'=>'santa-cruz-hightower-cc-x01-axs','description'=>'Trail bike carbone haut de gamme avec 135mm de débattement. Groupe SRAM X01 AXS électronique. La référence du trail.','description_de'=>'Premium Carbon-Trail-Bike mit 135mm Federweg und elektronischer SRAM X01 AXS Gruppe.','price'=>7499.00,'sale_price'=>null,'is_featured'=>true,'is_new'=>true,'bike_type'=>'Trail Carbone','wheel_size'=>'29"','frame_material'=>'Carbone CC haute modélisation','number_of_speeds'=>'12 vitesses SRAM X01 AXS','suspension_type'=>'Fox 36 Factory 140mm / Fox Float DPS 135mm','brake_style'=>'Hydraulique SRAM Code RSC','weight'=>'12,4 kg','warranty_type'=>'Garantie Santa Cruz à vie','colors'=>['Bleu','Noir'],'imgs'=>[[$I['vtt_b'],'Bleu'],[$I['vtt_a'],'Noir']],'sizes'=>'S,M,L,XL']);

        $add(['cat'=>'vtt','brand'=>'Santa Cruz','name'=>'Santa Cruz Bronson S Carbon 29"','name_de'=>'Santa Cruz Bronson S Carbon 29"','slug'=>'santa-cruz-bronson-s-carbon-29','description'=>'Enduro carbone 150mm avec groupe Shimano XT 12 vitesses. Pour les riders qui aiment dévaler les pentes.','description_de'=>'150mm Carbon-Enduro mit Shimano XT 12-Gang für Abfahrtsliebhaber.','price'=>5499.00,'sale_price'=>4899.00,'bike_type'=>'Enduro Carbone','wheel_size'=>'29"','frame_material'=>'Carbone C moyen module','number_of_speeds'=>'12 vitesses Shimano Deore XT','suspension_type'=>'RockShox Pike 150mm / Super Deluxe','brake_style'=>'Hydraulique Shimano XT 4 pistons','weight'=>'13,8 kg','warranty_type'=>'Garantie Santa Cruz à vie','colors'=>['Vert','Bleu','Noir'],'imgs'=>[[$I['vtt_d'],'Vert'],[$I['vtt_b'],'Bleu'],[$I['vtt_a'],'Noir']],'sizes'=>'S,M,L,XL']);

        $add(['cat'=>'vtt','brand'=>'Santa Cruz','name'=>'Santa Cruz Chameleon 7 D 29"','name_de'=>'Santa Cruz Chameleon 7 D 29"','slug'=>'santa-cruz-chameleon-7-d-29','description'=>'Hardtail polyvalent aluminium. Géométrie progressive pour un pilotage précis. Idéal pour les riders exigeants.','description_de'=>'Vielseitiges Aluminium-Hardtail mit progressiver Geometrie für präzises Fahren.','price'=>1499.00,'sale_price'=>null,'bike_type'=>'Hardtail VTT','wheel_size'=>'29"','frame_material'=>'Aluminium D (Double Butted)','number_of_speeds'=>'12 vitesses SRAM SX Eagle','suspension_type'=>'RockShox Recon 130mm','brake_style'=>'Hydraulique SRAM G2 R','weight'=>'13,1 kg','warranty_type'=>'Garantie Santa Cruz à vie','colors'=>['Rouge','Noir','Jaune'],'imgs'=>[[$I['vtt_c'],'Rouge'],[$I['vtt_a'],'Noir'],[$I['vtt_e'],'Jaune']],'sizes'=>'S,M,L,XL']);

        // ── YT Industries ──
        $add(['cat'=>'vtt','brand'=>'YT Industries','name'=>'YT Jeffsy Core 4 29" 2025','name_de'=>'YT Jeffsy Core 4 29" 2025','slug'=>'yt-jeffsy-core-4-29','description'=>'Trail bike allemand 140mm avec Fox 36 Rhythm et SRAM SX Eagle. Géométrie longue et basse pour un pilotage agressif.','description_de'=>'Deutsches 140mm Trail-Bike mit Fox 36 Rhythm und SRAM SX Eagle. Lange, tiefe Geometrie für aggressives Fahren.','price'=>3299.00,'sale_price'=>null,'is_new'=>true,'bike_type'=>'Trail Tout-suspendu','wheel_size'=>'29"','frame_material'=>'Aluminium 6061','number_of_speeds'=>'12 vitesses SRAM SX Eagle','suspension_type'=>'Fox 36 Rhythm 140mm / Fox Float DPS 140mm','brake_style'=>'Hydraulique SRAM G2 R','weight'=>'14,2 kg','warranty_type'=>'Garantie YT 2 ans','colors'=>['Noir','Blanc'],'imgs'=>[[$I['vtt_a'],'Noir'],[$I['vtt_f'],'Blanc']],'sizes'=>'S,M,L,XL']);

        $add(['cat'=>'vtt','brand'=>'YT Industries','name'=>'YT Capra Core 3 29" Enduro','name_de'=>'YT Capra Core 3 29" Enduro','slug'=>'yt-capra-core-3-29-enduro','description'=>'Enduro 170mm de débattement avec Fox 38 Float. Conçu pour les pentes les plus raides et les terrains les plus techniques.','description_de'=>'170mm Enduro-Bike mit Fox 38 Float. Für steilste Hänge und technischstes Gelände.','price'=>3799.00,'sale_price'=>null,'bike_type'=>'Enduro','wheel_size'=>'29"','frame_material'=>'Aluminium 6061','number_of_speeds'=>'12 vitesses SRAM GX Eagle','suspension_type'=>'Fox 38 Float 170mm / Fox Float X2 170mm','brake_style'=>'Hydraulique SRAM Code R','weight'=>'15,0 kg','warranty_type'=>'Garantie YT 2 ans','colors'=>['Noir','Vert'],'imgs'=>[[$I['vtt_a'],'Noir'],[$I['vtt_d'],'Vert']],'sizes'=>'S,M,L,XL']);

        // ── Orbea ──
        $add(['cat'=>'vtt','brand'=>'Orbea','name'=>'Orbea Occam M30 29" 2025','name_de'=>'Orbea Occam M30 29" 2025','slug'=>'orbea-occam-m30-29-2025','description'=>'Trail bike espagnol 130mm avec géométrie ajustable MyGeometry. Shimano Deore et RockShox Recon.','description_de'=>'Spanisches 130mm Trail-Bike mit einstellbarer MyGeometry. Shimano Deore und RockShox Recon.','price'=>2899.00,'sale_price'=>null,'bike_type'=>'Trail Tout-suspendu','wheel_size'=>'29"','frame_material'=>'Aluminium 6061 T6','number_of_speeds'=>'12 vitesses Shimano Deore','suspension_type'=>'RockShox Recon 130mm / RockShox Deluxe Select+','brake_style'=>'Hydraulique Shimano Deore 4 pistons','weight'=>'14,0 kg','warranty_type'=>'Garantie Orbea 5 ans','colors'=>['Bleu','Noir','Rouge'],'imgs'=>[[$I['vtt_b'],'Bleu'],[$I['vtt_a'],'Noir'],[$I['vtt_c'],'Rouge']],'sizes'=>'XS,S,M,L,XL']);

        $add(['cat'=>'vtt','brand'=>'Orbea','name'=>'Orbea Rallon M20 29" Enduro','name_de'=>'Orbea Rallon M20 29" Enduro','slug'=>'orbea-rallon-m20-29-enduro','description'=>'Enduro 170mm avec Fox 38 Rhythm et Shimano Deore XT. Pour les riders qui veulent tout donner en compétition.','description_de'=>'170mm Enduro mit Fox 38 Rhythm und Shimano Deore XT für Wettkampffahrer.','price'=>3499.00,'sale_price'=>2999.00,'bike_type'=>'Enduro','wheel_size'=>'29"','frame_material'=>'Aluminium 6061','number_of_speeds'=>'12 vitesses Shimano Deore XT','suspension_type'=>'Fox 38 Rhythm 170mm / Fox Float X2 170mm','brake_style'=>'Hydraulique Shimano XT 4 pistons','weight'=>'15,1 kg','warranty_type'=>'Garantie Orbea 5 ans','colors'=>['Rouge','Noir'],'imgs'=>[[$I['vtt_c'],'Rouge'],[$I['vtt_a'],'Noir']],'sizes'=>'S,M,L,XL']);

        // ── Merida ──
        $add(['cat'=>'vtt','brand'=>'Merida','name'=>'Merida Big.Nine 400 29" 2025','name_de'=>'Merida Big.Nine 400 29" 2025','slug'=>'merida-big-nine-400-29','description'=>'VTT XC hardtail avec cadre aluminium Lite et fourche RockShox 100mm. Légèreté et performance pour le cross-country.','description_de'=>'XC Hardtail mit Lite Aluminiumrahmen und RockShox 100mm Gabel. Leichtigkeit für Cross-Country.','price'=>1199.00,'sale_price'=>999.00,'bike_type'=>'XC Hardtail','wheel_size'=>'29"','frame_material'=>'Aluminium Lite','number_of_speeds'=>'20 vitesses Shimano Deore','suspension_type'=>'RockShox 30 Silver 100mm','brake_style'=>'Hydraulique Shimano MT200','weight'=>'12,8 kg','warranty_type'=>'Garantie Merida 5 ans','colors'=>['Noir','Bleu'],'imgs'=>[[$I['vtt_a'],'Noir'],[$I['vtt_b'],'Bleu']],'sizes'=>'XS,S,M,L,XL,XXL']);

        $add(['cat'=>'vtt','brand'=>'Merida','name'=>'Merida One-Sixty 800 29" Enduro','name_de'=>'Merida One-Sixty 800 29" Enduro','slug'=>'merida-one-sixty-800-29','description'=>'Enduro haut de gamme 160mm avec RockShox Lyrik et Shimano Deore XT. La référence taïwanaise pour la compétition.','description_de'=>'Premium 160mm Enduro mit RockShox Lyrik und Shimano Deore XT für den Wettkampf.','price'=>3299.00,'sale_price'=>null,'is_new'=>true,'bike_type'=>'Enduro','wheel_size'=>'29"','frame_material'=>'Aluminium 6061','number_of_speeds'=>'12 vitesses Shimano Deore XT','suspension_type'=>'RockShox Lyrik 160mm / Super Deluxe 160mm','brake_style'=>'Hydraulique Shimano XT 4 pistons','weight'=>'14,9 kg','warranty_type'=>'Garantie Merida 5 ans','colors'=>['Gris','Noir'],'imgs'=>[[$I['vtt_c'],'Gris'],[$I['vtt_a'],'Noir']],'sizes'=>'S,M,L,XL']);

        // ── Cube ──
        $add(['cat'=>'vtt','brand'=>'Cube','name'=>'Cube Aim Pro 27.5" Hardtail','name_de'=>'Cube Aim Pro 27.5" Hardtail','slug'=>'cube-aim-pro-27-5-hardtail','description'=>'VTT hardtail entrée de gamme avec SR Suntour XCR 100mm et Shimano Acera. Solide et fiable pour les débutants.','description_de'=>'Einstiegs-Hardtail mit SR Suntour XCR 100mm und Shimano Acera. Solide und zuverlässig.','price'=>799.00,'sale_price'=>null,'bike_type'=>'Hardtail VTT','wheel_size'=>'27.5"','frame_material'=>'Aluminium 6061','number_of_speeds'=>'24 vitesses Shimano Acera','suspension_type'=>'SR Suntour XCR 100mm','brake_style'=>'Disque hydraulique Shimano','weight'=>'13,6 kg','warranty_type'=>'Garantie Cube 2 ans','colors'=>['Vert','Noir','Gris'],'imgs'=>[[$I['vtt_d'],'Vert'],[$I['vtt_a'],'Noir'],[$I['vtt_c'],'Gris']],'sizes'=>'XS,S,M,L,XL']);

        $add(['cat'=>'vtt','brand'=>'Cube','name'=>'Cube Stereo 140 HPC SLT 29"','name_de'=>'Cube Stereo 140 HPC SLT 29"','slug'=>'cube-stereo-140-hpc-slt-29','description'=>'Trail bike carbone haut de gamme 140mm avec groupe SRAM X01 Eagle AXS électronique. Le summum de la marque allemande.','description_de'=>'Premium 140mm Carbon-Trail-Bike mit elektronischer SRAM X01 Eagle AXS Gruppe.','price'=>5299.00,'sale_price'=>null,'is_featured'=>true,'bike_type'=>'Trail Carbone','wheel_size'=>'29"','frame_material'=>'Carbone HPC SLT','number_of_speeds'=>'12 vitesses SRAM X01 AXS','suspension_type'=>'Fox 36 Float Factory 140mm / Fox Float DPS Factory','brake_style'=>'Hydraulique SRAM Code RSC','weight'=>'12,2 kg','warranty_type'=>'Garantie Cube 2 ans','colors'=>['Noir','Blanc'],'imgs'=>[[$I['vtt_a'],'Noir'],[$I['vtt_f'],'Blanc']],'sizes'=>'S,M,L,XL']);

        // ── Cannondale ──
        $add(['cat'=>'vtt','brand'=>'Cannondale','name'=>'Cannondale Habit 4 29" Trail','name_de'=>'Cannondale Habit 4 29" Trail','slug'=>'cannondale-habit-4-29-trail','description'=>'Trail bike polyvalent 130mm avec géométrie Progressive Sizing. SRAM SX Eagle et Shimano MT420.','description_de'=>'Vielseitiges 130mm Trail-Bike mit Progressive Sizing Geometrie, SRAM SX Eagle und Shimano MT420.','price'=>2799.00,'sale_price'=>null,'is_new'=>true,'bike_type'=>'Trail Tout-suspendu','wheel_size'=>'29"','frame_material'=>'Aluminium SmartForm C2','number_of_speeds'=>'12 vitesses SRAM SX Eagle','suspension_type'=>'RockShox Recon 130mm / Fox Float','brake_style'=>'Hydraulique Shimano MT420','weight'=>'14,1 kg','warranty_type'=>'Garantie Cannondale à vie','colors'=>['Vert','Noir'],'imgs'=>[[$I['vtt_d'],'Vert'],[$I['vtt_a'],'Noir']],'sizes'=>'S,M,L,XL']);

        $add(['cat'=>'vtt','brand'=>'Cannondale','name'=>'Cannondale Jekyll 1 29" Enduro','name_de'=>'Cannondale Jekyll 1 29" Enduro','slug'=>'cannondale-jekyll-1-29-enduro','description'=>'Enduro carbone 165mm avec groupe Shimano Deore XT et Öhlins RXF 36. Technologie Proportional Response unique.','description_de'=>'165mm Carbon-Enduro mit Shimano Deore XT und Öhlins RXF 36. Einzigartige Proportional Response Technologie.','price'=>6499.00,'sale_price'=>null,'is_featured'=>true,'is_new'=>true,'bike_type'=>'Enduro Carbone','wheel_size'=>'29"','frame_material'=>'Carbone BallisTec','number_of_speeds'=>'12 vitesses Shimano Deore XT','suspension_type'=>'Öhlins RXF 36 165mm / Öhlins TTX22M 165mm','brake_style'=>'Hydraulique Shimano XT 4 pistons','weight'=>'13,0 kg','warranty_type'=>'Garantie Cannondale à vie','colors'=>['Vert','Noir'],'imgs'=>[[$I['vtt_d'],'Vert'],[$I['vtt_a'],'Noir']],'sizes'=>'S,M,L,XL']);

        // ── Norco ──
        $add(['cat'=>'vtt','brand'=>'Norco','name'=>'Norco Sight A2 29" Trail','name_de'=>'Norco Sight A2 29" Trail','slug'=>'norco-sight-a2-29-trail','description'=>'Trail bike canadien 140mm avec Fox 36 Rhythm et SRAM GX Eagle. Géométrie progressive pour tous les terrains.','description_de'=>'Kanadisches 140mm Trail-Bike mit Fox 36 Rhythm und SRAM GX Eagle. Progressive Geometrie.','price'=>2999.00,'sale_price'=>null,'bike_type'=>'Trail Tout-suspendu','wheel_size'=>'29"','frame_material'=>'Aluminium A6061','number_of_speeds'=>'12 vitesses SRAM GX Eagle','suspension_type'=>'Fox 36 Rhythm 140mm / Fox Float DPS','brake_style'=>'Hydraulique SRAM G2 R','weight'=>'14,3 kg','warranty_type'=>'Garantie Norco à vie','colors'=>['Vert','Noir'],'imgs'=>[[$I['vtt_d'],'Vert'],[$I['vtt_a'],'Noir']],'sizes'=>'XS,S,M,L,XL']);

        // ── Scott ──
        $add(['cat'=>'vtt','brand'=>'Scott','name'=>'Scott Genius 940 29" TwinLoc','name_de'=>'Scott Genius 940 29" TwinLoc','slug'=>'scott-genius-940-29-twinloc','description'=>'Trail bike avec système TwinLoc exclusif permettant de basculer entre modes Trail, Traction et Lock.','description_de'=>'Trail-Bike mit exklusivem TwinLoc System für Wechsel zwischen Trail, Traktion und Sperrmodi.','price'=>2499.00,'sale_price'=>2099.00,'bike_type'=>'Trail Tout-suspendu','wheel_size'=>'29"','frame_material'=>'Aluminium 6061','number_of_speeds'=>'12 vitesses Shimano Deore','suspension_type'=>'RockShox Recon 130mm / Scott TwinLoc 130mm','brake_style'=>'Hydraulique Shimano MT420','weight'=>'14,5 kg','warranty_type'=>'Garantie Scott 2 ans','colors'=>['Bleu','Noir'],'imgs'=>[[$I['vtt_b'],'Bleu'],[$I['vtt_a'],'Noir']],'sizes'=>'S,M,L,XL']);

        $add(['cat'=>'vtt','brand'=>'Scott','name'=>'Scott Scale 940 29" XC','name_de'=>'Scott Scale 940 29" XC','slug'=>'scott-scale-940-29-xc','description'=>'VTT XC hardtail aluminium ultra-léger. Shimano Deore 2×10 et fourche RockShox Judy Silver.','description_de'=>'Ultra-leichtes XC Aluminium-Hardtail. Shimano Deore 2×10 und RockShox Judy Silver Gabel.','price'=>1099.00,'sale_price'=>899.00,'bike_type'=>'XC Hardtail','wheel_size'=>'29"','frame_material'=>'Aluminium 6061 Triple Butted','number_of_speeds'=>'20 vitesses Shimano Deore','suspension_type'=>'RockShox Judy Silver 100mm','brake_style'=>'Hydraulique Shimano MT200','weight'=>'12,9 kg','warranty_type'=>'Garantie Scott 2 ans','colors'=>['Blanc','Noir'],'imgs'=>[[$I['vtt_f'],'Blanc'],[$I['vtt_a'],'Noir']],'sizes'=>'XS,S,M,L,XL,XXL']);

        // ── Pivot ──
        $add(['cat'=>'vtt','brand'=>'Pivot','name'=>'Pivot Mach 4 SL Team XTR 29"','name_de'=>'Pivot Mach 4 SL Team XTR 29"','slug'=>'pivot-mach-4-sl-team-xtr-29','description'=>'VTT XC carbone utilisé par les équipes professionnelles. Shimano XTR et composants race pour la victoire.','description_de'=>'Von Profi-Teams eingesetztes XC Carbon-Bike. Shimano XTR und Race-Komponenten für den Sieg.','price'=>9999.00,'sale_price'=>null,'is_featured'=>true,'is_new'=>true,'bike_type'=>'XC Race Carbone','wheel_size'=>'29"','frame_material'=>'Carbone UD','number_of_speeds'=>'12 vitesses Shimano XTR','suspension_type'=>'Fox 34 Float Factory 100mm / Fox Float DPS Factory','brake_style'=>'Hydraulique Shimano XTR','weight'=>'8,9 kg','warranty_type'=>'Garantie Pivot à vie','colors'=>['Blanc','Bleu'],'imgs'=>[[$I['vtt_f'],'Blanc'],[$I['vtt_b'],'Bleu']],'sizes'=>'XS,S,M,L,XL']);

        // ── Propain ──
        $add(['cat'=>'vtt','brand'=>'Propain','name'=>'Propain Spindrift CF 29" Enduro','name_de'=>'Propain Spindrift CF 29" Enduro','slug'=>'propain-spindrift-cf-29-enduro','description'=>'Enduro carbone allemand 160mm avec groupe Shimano Deore XT. Rapport qualité-prix exceptionnel.','description_de'=>'Deutsches 160mm Carbon-Enduro mit Shimano Deore XT. Außergewöhnliches Preis-Leistungs-Verhältnis.','price'=>3999.00,'sale_price'=>null,'is_new'=>true,'bike_type'=>'Enduro Carbone','wheel_size'=>'29"','frame_material'=>'Carbone CF','number_of_speeds'=>'12 vitesses Shimano Deore XT','suspension_type'=>'Fox 38 Rhythm 160mm / Fox Float X2 160mm','brake_style'=>'Hydraulique Shimano XT 4 pistons','weight'=>'13,5 kg','warranty_type'=>'Garantie Propain 3 ans','colors'=>['Noir','Vert'],'imgs'=>[[$I['vtt_a'],'Noir'],[$I['vtt_d'],'Vert']],'sizes'=>'S,M,L,XL']);

        // ── Kona ──
        $add(['cat'=>'vtt','brand'=>'Kona','name'=>'Kona Process 134 DL 29"','name_de'=>'Kona Process 134 DL 29"','slug'=>'kona-process-134-dl-29','description'=>'Trail bike canadien 134mm avec SRAM GX Eagle et RockShox Pike. Pour le trail technique avec style.','description_de'=>'Kanadisches 134mm Trail-Bike mit SRAM GX Eagle und RockShox Pike. Für technischen Trail mit Stil.','price'=>2499.00,'sale_price'=>null,'bike_type'=>'Trail Tout-suspendu','wheel_size'=>'29"','frame_material'=>'Aluminium 6061','number_of_speeds'=>'12 vitesses SRAM GX Eagle','suspension_type'=>'RockShox Pike 130mm / RockShox Deluxe Select+','brake_style'=>'Hydraulique SRAM G2 R','weight'=>'14,0 kg','warranty_type'=>'Garantie Kona à vie','colors'=>['Orange','Noir'],'imgs'=>[[$I['vtt_e'],'Orange'],[$I['vtt_a'],'Noir']],'sizes'=>'S,M,L,XL']);

        // ─── Plus de VTT ───
        foreach ([
            ['trek','Trek','Trek Procaliber 6 29" Entrée de gamme','trek-procaliber-6-29','VTT XC hardtail aluminium entrée de gamme. Fourche SR Suntour XCR et Shimano Altus. Idéal pour commencer le cross-country.',699.00,null,'vtt_a','vtt_b'],
            ['specialized','Specialized','Specialized Rockhopper Sport 29"','specialized-rockhopper-sport-29','Hardtail populaire avec cadre aluminium renforcé et fourche SR Suntour XCT 100mm. Shimano 21 vitesses.',699.00,579.00,'vtt_a','vtt_c'],
            ['giant','Giant','Giant ATX 1 27.5" 2025','giant-atx-1-275-2025','VTT hardtail polyvalent avec cadre ALUXX et freins à disque mécaniques. Parfait pour les déplacements urbains et chemins.',599.00,null,'vtt_a','vtt_b'],
            ['cube','Cube','Cube Access WS 27.5" Women','cube-access-ws-275-women','VTT hardtail spécialement conçu pour les femmes avec géométrie adaptée, suspension SR Suntour et Shimano 21 vitesses.',749.00,null,'vtt_d','vtt_a'],
            ['cannondale','Cannondale','Cannondale Trail SL 4 29"','cannondale-trail-sl-4-29','Hardtail performant avec cadre SmartForm C2 et fourche SR Suntour XCR. SRAM SX Eagle 12 vitesses.',1299.00,null,'vtt_a','vtt_d'],
            ['merida','Merida','Merida Big.Seven 100 27.5"','merida-big-seven-100-275','VTT hardtail 27,5" avec cadre aluminium et fourche SR Suntour XCR 100mm. Transmission Shimano Deore.',899.00,749.00,'vtt_b','vtt_a'],
            ['scott','Scott','Scott Aspect 940 27.5"','scott-aspect-940-275','Hardtail entrée de gamme avec cadre Aspect Twin Loc et fourche SR Suntour XCT. Parfait pour les débutants.',599.00,null,'vtt_a','vtt_c'],
            ['norco','Norco','Norco Storm 2 27.5" Hardtail','norco-storm-2-275','Hardtail robuste avec cadre aluminium Series 7 et fourche SR Suntour XCT. Transmission Shimano 21 vitesses.',699.00,599.00,'vtt_d','vtt_a'],
        ] as [$slug_brand, $brand, $name, $slug, $desc, $price, $sale, $img1, $img2]) {
            $add(['cat'=>'vtt','brand'=>$brand,'name'=>$name,'name_de'=>$name,'slug'=>$slug,'description'=>$desc,'description_de'=>$desc,'price'=>$price,'sale_price'=>$sale,'bike_type'=>'Hardtail VTT','wheel_size'=>'29"','frame_material'=>'Aluminium','number_of_speeds'=>'21 vitesses Shimano','suspension_type'=>'SR Suntour 100mm','brake_style'=>'Disque mécanique','weight'=>'13,5 kg','warranty_type'=>'Garantie 2 ans','colors'=>['Noir','Bleu'],'imgs'=>[[$I[$img1],'Noir'],[$I[$img2],'Bleu']],'sizes'=>'S,M,L,XL']);
        }

        // ════════════════════════════════════════════════════════
        // ██ ROUTE — 35 produits
        // ════════════════════════════════════════════════════════

        $add(['cat'=>'route','brand'=>'Trek','name'=>'Trek Émonda SL 5 Disc Carbone','name_de'=>'Trek Émonda SL 5 Disc Carbon','slug'=>'trek-emonda-sl5-disc','description'=>'Vélo de route carbone OCLV 500 ultra-léger avec groupe Shimano 105 Di2 électronique. Le grimpeur parfait.','description_de'=>'Ultra-leichtes OCLV 500 Carbon-Rennrad mit elektronischer Shimano 105 Di2 Gruppe. Der perfekte Kletterer.','price'=>4299.00,'sale_price'=>3499.00,'is_featured'=>true,'bike_type'=>'Route Carbone','wheel_size'=>'700c','frame_material'=>'Carbone OCLV 500','number_of_speeds'=>'22 vitesses Shimano 105 Di2','suspension_type'=>'Rigide','brake_style'=>'Disque hydraulique Shimano 105','weight'=>'7,9 kg','warranty_type'=>'Garantie Trek à vie carbone','colors'=>['Blanc','Noir','Rouge'],'imgs'=>[[$I['route_a'],'Blanc'],[$I['route_b'],'Noir'],[$I['route_c'],'Rouge']],'sizes'=>'47,50,52,54,56,58,60,62']);

        $add(['cat'=>'route','brand'=>'Trek','name'=>'Trek Domane SL 6 Gen 4 Disc','name_de'=>'Trek Domane SL 6 Gen 4 Disc','slug'=>'trek-domane-sl6-gen4-disc','description'=>'Vélo d\'endurance carbone avec IsoSpeed découplé avant/arrière pour un confort exceptionnel. Shimano 105 Di2.','description_de'=>'Carbon-Endurance-Bike mit IsoSpeed vorne/hinten für außergewöhnlichen Komfort. Shimano 105 Di2.','price'=>5299.00,'sale_price'=>null,'is_new'=>true,'bike_type'=>'Route Endurance','wheel_size'=>'700c','frame_material'=>'Carbone OCLV 500','number_of_speeds'=>'22 vitesses Shimano 105 Di2','suspension_type'=>'IsoSpeed découplé','brake_style'=>'Disque hydraulique Shimano 105','weight'=>'8,4 kg','warranty_type'=>'Garantie Trek à vie','colors'=>['Bleu','Noir'],'imgs'=>[[$I['route_b'],'Bleu'],[$I['route_a'],'Noir']],'sizes'=>'47,50,52,54,56,58,60,62']);

        $add(['cat'=>'route','brand'=>'Trek','name'=>'Trek Madone SL 6 Gen 7 AXS','name_de'=>'Trek Madone SL 6 Gen 7 AXS','slug'=>'trek-madone-sl6-gen7-axs','description'=>'Vélo aéro carbone avec IsoFlow et SRAM Force AXS électronique. Le vélo des champions du World Tour.','description_de'=>'Aero-Carbon-Rennrad mit IsoFlow und elektronischem SRAM Force AXS. Das Bike der World Tour Champions.','price'=>8499.00,'sale_price'=>null,'is_featured'=>true,'is_new'=>true,'bike_type'=>'Route Aero Carbone','wheel_size'=>'700c','frame_material'=>'Carbone OCLV 700','number_of_speeds'=>'12 vitesses SRAM Force AXS','suspension_type'=>'IsoFlow','brake_style'=>'Disque hydraulique SRAM Force','weight'=>'7,2 kg','warranty_type'=>'Garantie Trek à vie','colors'=>['Noir','Blanc','Rouge'],'imgs'=>[[$I['route_a'],'Noir'],[$I['route_b'],'Blanc'],[$I['route_c'],'Rouge']],'sizes'=>'47,50,52,54,56,58,60,62']);

        $add(['cat'=>'route','brand'=>'Specialized','name'=>'Specialized Tarmac SL7 Expert Ultegra Di2','name_de'=>'Specialized Tarmac SL7 Expert Ultegra Di2','slug'=>'specialized-tarmac-sl7-expert','description'=>'Vélo de route aéro carbone FACT 10r avec groupe Shimano Ultegra Di2. Performances de compétition accessibles.','description_de'=>'Aero-Carbon-Rennrad FACT 10r mit Shimano Ultegra Di2. Wettkampfleistung für alle.','price'=>5499.00,'sale_price'=>null,'is_featured'=>true,'is_new'=>true,'bike_type'=>'Route Aero Carbone','wheel_size'=>'700c','frame_material'=>'Carbone FACT 10r','number_of_speeds'=>'22 vitesses Shimano Ultegra Di2','suspension_type'=>'Rigide','brake_style'=>'Disque hydraulique Shimano Ultegra','weight'=>'7,1 kg','warranty_type'=>'Garantie Specialized 5 ans','colors'=>['Noir','Blanc','Bleu'],'imgs'=>[[$I['route_a'],'Noir'],[$I['route_b'],'Blanc'],[$I['route_c'],'Bleu']],'sizes'=>'44,49,52,54,56,58,61']);

        $add(['cat'=>'route','brand'=>'Specialized','name'=>'Specialized Allez Sprint Comp Disc','name_de'=>'Specialized Allez Sprint Comp Disc','slug'=>'specialized-allez-sprint-comp-disc','description'=>'Vélo de route aluminium E5 aéro avec groupe Shimano 105. La performance aéro à prix accessible.','description_de'=>'Aero-Aluminium-Rennrad E5 mit Shimano 105. Aerodynamische Leistung zum günstigen Preis.','price'=>1799.00,'sale_price'=>1499.00,'bike_type'=>'Route Aero Aluminium','wheel_size'=>'700c','frame_material'=>'Aluminium E5 Premium','number_of_speeds'=>'22 vitesses Shimano 105','suspension_type'=>'Rigide','brake_style'=>'Disque hydraulique Shimano 105','weight'=>'9,2 kg','warranty_type'=>'Garantie Specialized 5 ans','colors'=>['Noir','Blanc'],'imgs'=>[[$I['route_a'],'Noir'],[$I['route_b'],'Blanc']],'sizes'=>'44,49,52,54,56,58,61']);

        $add(['cat'=>'route','brand'=>'Colnago','name'=>'Colnago C68 Disc Shimano Dura-Ace Di2','name_de'=>'Colnago C68 Disc Shimano Dura-Ace Di2','slug'=>'colnago-c68-disc-dura-ace','description'=>'Le summum de l\'artisanat italien. Cadre carbone T800/T1000 et groupe Shimano Dura-Ace Di2. Le rêve ultime.','description_de'=>'Der Gipfel italienischer Handwerkskunst. T800/T1000 Carbon und Shimano Dura-Ace Di2.','price'=>12999.00,'sale_price'=>null,'is_featured'=>true,'is_new'=>true,'bike_type'=>'Route Prestige','wheel_size'=>'700c','frame_material'=>'Carbone T800/T1000','number_of_speeds'=>'22 vitesses Shimano Dura-Ace Di2','suspension_type'=>'Rigide','brake_style'=>'Disque hydraulique Shimano Dura-Ace','weight'=>'6,8 kg','warranty_type'=>'Garantie Colnago à vie','colors'=>['Blanc','Rouge','Noir'],'imgs'=>[[$I['route_b'],'Blanc'],[$I['route_c'],'Rouge'],[$I['route_a'],'Noir']],'sizes'=>'45,48,50,52,54,56,58']);

        $add(['cat'=>'route','brand'=>'Pinarello','name'=>'Pinarello Dogma F Dura-Ace Di2','name_de'=>'Pinarello Dogma F Dura-Ace Di2','slug'=>'pinarello-dogma-f-dura-ace','description'=>'Le vélo sur lequel les champions gagnent le Tour de France. Carbone T1100 et Shimano Dura-Ace Di2. L\'excellence.','description_de'=>'Das Bike der Tour de France Sieger. T1100 Carbon und Shimano Dura-Ace Di2. Exzellenz pur.','price'=>14999.00,'sale_price'=>null,'is_featured'=>true,'is_new'=>true,'bike_type'=>'Route Pro','wheel_size'=>'700c','frame_material'=>'Carbone TorayCA T1100 1K','number_of_speeds'=>'22 vitesses Shimano Dura-Ace Di2','suspension_type'=>'Rigide','brake_style'=>'Disque hydraulique Shimano Dura-Ace','weight'=>'6,5 kg','warranty_type'=>'Garantie Pinarello 5 ans','colors'=>['Noir','Blanc'],'imgs'=>[[$I['route_a'],'Noir'],[$I['route_b'],'Blanc']],'sizes'=>'44,46,50,51.5,53,54,55,56,57.5,59,62']);

        $add(['cat'=>'route','brand'=>'Bianchi','name'=>'Bianchi Oltre RC Dura-Ace Di2','name_de'=>'Bianchi Oltre RC Dura-Ace Di2','slug'=>'bianchi-oltre-rc-dura-ace','description'=>'Le vaisseau amiral Bianchi avec sa légendaire couleur Celeste. Carbone CounterVail et Dura-Ace Di2.','description_de'=>'Bianchis Flaggschiff mit der legendären Celeste Farbe. CounterVail Carbon und Dura-Ace Di2.','price'=>11999.00,'sale_price'=>null,'is_featured'=>true,'bike_type'=>'Route Aero Prestige','wheel_size'=>'700c','frame_material'=>'Carbone CV CounterVail','number_of_speeds'=>'22 vitesses Shimano Dura-Ace Di2','suspension_type'=>'Rigide','brake_style'=>'Disque hydraulique Shimano Dura-Ace','weight'=>'6,9 kg','warranty_type'=>'Garantie Bianchi à vie','colors'=>['Celeste','Noir'],'imgs'=>[[$I['route_b'],'Celeste'],[$I['route_a'],'Noir']],'sizes'=>'44,47,50,53,55,57,59']);

        $add(['cat'=>'route','brand'=>'Giant','name'=>'Giant TCR Advanced Pro 1 Disc 2025','name_de'=>'Giant TCR Advanced Pro 1 Disc 2025','slug'=>'giant-tcr-advanced-pro-1-disc','description'=>'Vélo de route carbone Advanced Grade avec Shimano Ultegra Di2. Performance et aérodynamisme pour les cyclistes exigeants.','description_de'=>'Advanced Grade Carbon-Rennrad mit Shimano Ultegra Di2. Leistung und Aerodynamik.','price'=>3999.00,'sale_price'=>null,'is_new'=>true,'bike_type'=>'Route Carbone','wheel_size'=>'700c','frame_material'=>'Carbone Advanced Grade','number_of_speeds'=>'22 vitesses Shimano Ultegra Di2','suspension_type'=>'Rigide','brake_style'=>'Disque hydraulique Shimano Ultegra','weight'=>'7,5 kg','warranty_type'=>'Garantie Giant 5 ans','colors'=>['Noir','Blanc','Rouge'],'imgs'=>[[$I['route_a'],'Noir'],[$I['route_b'],'Blanc'],[$I['route_c'],'Rouge']],'sizes'=>'XXS,XS,S,M,ML,L,XL']);

        $add(['cat'=>'route','brand'=>'Cannondale','name'=>'Cannondale CAAD13 105 Disc','name_de'=>'Cannondale CAAD13 105 Disc Aluminium','slug'=>'cannondale-caad13-105-disc','description'=>'Le meilleur vélo de route aluminium du marché. SmartForm C1 Premium avec groupe Shimano 105. Légèreté de carbone.','description_de'=>'Das beste Aluminium-Rennrad auf dem Markt. SmartForm C1 Premium mit Shimano 105. Carbon-Leichtigkeit.','price'=>1899.00,'sale_price'=>null,'is_new'=>true,'bike_type'=>'Route Aluminium','wheel_size'=>'700c','frame_material'=>'Aluminium SmartForm C1 Premium','number_of_speeds'=>'22 vitesses Shimano 105','suspension_type'=>'Rigide','brake_style'=>'Disque hydraulique Shimano 105','weight'=>'8,6 kg','warranty_type'=>'Garantie Cannondale à vie','colors'=>['Blanc','Noir','Gris'],'imgs'=>[[$I['route_b'],'Blanc'],[$I['route_a'],'Noir'],[$I['route_c'],'Gris']],'sizes'=>'44,48,51,54,56,58,61']);

        $add(['cat'=>'route','brand'=>'Cervélo','name'=>'Cervélo R5 Ultegra Di2 Grimpeur','name_de'=>'Cervélo R5 Ultegra Di2 Bergfahrer','slug'=>'cervelo-r5-ultegra-di2','description'=>'Vélo de route ultra-léger pour les grimpeurs. Carbone HM et Shimano Ultegra Di2. Favori des ascensions.','description_de'=>'Ultra-leichtes Rennrad für Kletterer. HM Carbon und Shimano Ultegra Di2.','price'=>7499.00,'sale_price'=>null,'is_new'=>true,'bike_type'=>'Route Grimpeur','wheel_size'=>'700c','frame_material'=>'Carbone HM','number_of_speeds'=>'22 vitesses Shimano Ultegra Di2','suspension_type'=>'Rigide','brake_style'=>'Disque hydraulique Shimano Ultegra','weight'=>'6,9 kg','warranty_type'=>'Garantie Cervélo 5 ans','colors'=>['Noir','Blanc','Bleu'],'imgs'=>[[$I['route_a'],'Noir'],[$I['route_b'],'Blanc'],[$I['route_c'],'Bleu']],'sizes'=>'44,48,51,54,56,58,61']);

        $add(['cat'=>'route','brand'=>'BMC','name'=>'BMC Teammachine SLR 01 Dura-Ace Di2','name_de'=>'BMC Teammachine SLR 01 Dura-Ace Di2','slug'=>'bmc-teammachine-slr-01-dura-ace','description'=>'Le vélo suisse de référence. Carbone ACE (Advanced Composite Engineering) et Dura-Ace Di2.','description_de'=>'Das Schweizer Referenz-Rennrad. ACE Carbon (Advanced Composite Engineering) und Dura-Ace Di2.','price'=>13499.00,'sale_price'=>null,'is_featured'=>true,'bike_type'=>'Route Pro','wheel_size'=>'700c','frame_material'=>'Carbone ACE','number_of_speeds'=>'22 vitesses Shimano Dura-Ace Di2','suspension_type'=>'Rigide','brake_style'=>'Disque hydraulique Shimano Dura-Ace','weight'=>'6,7 kg','warranty_type'=>'Garantie BMC 5 ans','colors'=>['Rouge','Blanc'],'imgs'=>[[$I['route_c'],'Rouge'],[$I['route_b'],'Blanc']],'sizes'=>'44,47,49,51,53,55,57,61']);

        $add(['cat'=>'route','brand'=>'Look','name'=>'Look 795 Blade RS Disc Ultegra Di2','name_de'=>'Look 795 Blade RS Disc Ultegra Di2','slug'=>'look-795-blade-rs-disc-ultegra','description'=>'Vélo aéro français avant-gardiste. Carbone HM UD et Shimano Ultegra Di2. L\'élégance française au service de la performance.','description_de'=>'Avantgardistisches französisches Aero-Bike. HM UD Carbon und Shimano Ultegra Di2.','price'=>8499.00,'sale_price'=>null,'is_featured'=>true,'bike_type'=>'Route Aero','wheel_size'=>'700c','frame_material'=>'Carbone HM UD','number_of_speeds'=>'22 vitesses Shimano Ultegra Di2','suspension_type'=>'Rigide','brake_style'=>'Disque hydraulique Shimano Ultegra','weight'=>'7,2 kg','warranty_type'=>'Garantie Look 5 ans','colors'=>['Noir','Blanc'],'imgs'=>[[$I['route_a'],'Noir'],[$I['route_b'],'Blanc']],'sizes'=>'44,47,49,52,54,56,58']);

        $add(['cat'=>'route','brand'=>'Ridley','name'=>'Ridley Helium SLX Disc 105 Di2','name_de'=>'Ridley Helium SLX Disc 105 Di2','slug'=>'ridley-helium-slx-disc-105-di2','description'=>'Vélo belge ultra-léger conçu pour les grimpeurs. Cadre carbone HM UD et groupe Shimano 105 Di2.','description_de'=>'Belgisches Ultra-Leicht-Rennrad für Kletterer. HM UD Carbon und Shimano 105 Di2 Gruppe.','price'=>4499.00,'sale_price'=>3999.00,'bike_type'=>'Route Grimpeur','wheel_size'=>'700c','frame_material'=>'Carbone HM UD','number_of_speeds'=>'22 vitesses Shimano 105 Di2','suspension_type'=>'Rigide','brake_style'=>'Disque hydraulique Shimano 105','weight'=>'7,0 kg','warranty_type'=>'Garantie Ridley 5 ans','colors'=>['Noir','Vert'],'imgs'=>[[$I['route_a'],'Noir'],[$I['route_b'],'Vert']],'sizes'=>'XS,S,M,L,XL']);

        foreach ([
            ['Trek','Trek Émonda ALR 5 Disc Aluminium','trek-emonda-alr5-disc','Vélo de route aluminium IsoSpeed avec Shimano 105. La légèreté alu accessible.',2199.00,null,'route_a','route_b'],
            ['Specialized','Specialized Roubaix Expert Ultegra Di2','specialized-roubaix-expert-ultegra','Vélo d\'endurance avec Future Shock 2.0 pour le maximum de confort. Ultegra Di2.',4799.00,null,'route_b','route_a'],
            ['Giant','Giant Defy Advanced Pro 0 AXS','giant-defy-advanced-pro-0-axs','Vélo d\'endurance carbone avec D-Fuse et SRAM Force AXS. Confort et performance.',4999.00,null,'route_c','route_a'],
            ['Cannondale','Cannondale SuperSix EVO Hi-MOD 1','cannondale-supersix-evo-hi-mod-1','Vélo de route carbone BallisTec Hi-MOD ultra-rigide avec Shimano Dura-Ace Di2.',8999.00,null,'route_a','route_b'],
            ['Scott','Scott Addict RC 10 Disc 2025','scott-addict-rc-10-disc','Vélo de route carbone HMF avec groupe Shimano Ultegra Di2. Légèreté et rigidité.',3999.00,null,'route_b','route_a'],
            ['Orbea','Orbea Orca M30 Team 2025','orbea-orca-m30-team','Vélo de route carbone OMX avec groupe Shimano 105 Di2. Géométrie de compétition.',3299.00,null,'route_a','route_c'],
            ['Merida','Merida Scultura 6000 Disc 2025','merida-scultura-6000-disc','Vélo de route carbone CF4 avec groupe Shimano Ultegra Di2. Légèreté et aérodynamisme.',4299.00,3799.00,'route_c','route_a'],
        ] as [$brand, $name, $slug, $desc, $price, $sale, $img1, $img2]) {
            $add(['cat'=>'route','brand'=>$brand,'name'=>$name,'name_de'=>$name,'slug'=>$slug,'description'=>$desc,'description_de'=>$desc,'price'=>$price,'sale_price'=>$sale,'bike_type'=>'Route Carbone','wheel_size'=>'700c','frame_material'=>'Carbone','number_of_speeds'=>'22 vitesses','suspension_type'=>'Rigide','brake_style'=>'Disque hydraulique','weight'=>'7,5 kg','warranty_type'=>'Garantie 5 ans','colors'=>['Noir','Blanc'],'imgs'=>[[$I[$img1],'Noir'],[$I[$img2],'Blanc']],'sizes'=>'47,50,52,54,56,58,60']);
        }

        // ════════════════════════════════════════════════════════
        // ██ GRAVEL — 20 produits
        // ════════════════════════════════════════════════════════

        $add(['cat'=>'gravel','brand'=>'Trek','name'=>'Trek Checkpoint ALR 5 GRX','name_de'=>'Trek Checkpoint ALR 5 GRX','slug'=>'trek-checkpoint-alr5-grx','description'=>'Gravel bike aluminium IsoSpeed avec groupe Shimano GRX 600. Polyvalent sur route et chemins.','description_de'=>'Aluminium-Gravel-Bike mit IsoSpeed und Shimano GRX 600. Vielseitig auf Straße und Wegen.','price'=>1999.00,'sale_price'=>null,'is_new'=>true,'bike_type'=>'Gravel Aventure','wheel_size'=>'700c','frame_material'=>'Aluminium Alpha Platinum IsoSpeed','number_of_speeds'=>'20 vitesses Shimano GRX 600','suspension_type'=>'Rigide IsoSpeed','brake_style'=>'Disque hydraulique Shimano GRX','weight'=>'9,4 kg','warranty_type'=>'Garantie Trek à vie','colors'=>['Gris','Noir','Vert'],'imgs'=>[[$I['gravel_a'],'Gris'],[$I['gravel_b'],'Noir'],[$I['route_a'],'Vert']],'sizes'=>'47,50,52,54,56,58,61']);

        $add(['cat'=>'gravel','brand'=>'Trek','name'=>'Trek Checkpoint SL 6 AXS GRX Di2','name_de'=>'Trek Checkpoint SL 6 AXS GRX Di2','slug'=>'trek-checkpoint-sl6-axs','description'=>'Gravel bike carbone haut de gamme avec IsoSpeed et groupe Shimano GRX Di2. Pour l\'aventure sans compromis.','description_de'=>'Premium Carbon-Gravel-Bike mit IsoSpeed und Shimano GRX Di2. Für Abenteuer ohne Kompromisse.','price'=>3999.00,'sale_price'=>null,'is_featured'=>true,'bike_type'=>'Gravel Carbone','wheel_size'=>'700c','frame_material'=>'Carbone OCLV 500','number_of_speeds'=>'22 vitesses Shimano GRX Di2','suspension_type'=>'IsoSpeed carbone','brake_style'=>'Disque hydraulique Shimano GRX','weight'=>'8,5 kg','warranty_type'=>'Garantie Trek à vie','colors'=>['Noir','Blanc'],'imgs'=>[[$I['gravel_a'],'Noir'],[$I['gravel_b'],'Blanc']],'sizes'=>'47,50,52,54,56,58,61']);

        $add(['cat'=>'gravel','brand'=>'Specialized','name'=>'Specialized Diverge Comp Carbon GRX Di2','name_de'=>'Specialized Diverge Comp Carbon GRX Di2','slug'=>'specialized-diverge-comp-carbon','description'=>'Gravel bike carbone avec Future Shock 2.0 et groupe Shimano GRX Di2 électronique. Confort maximal en aventure.','description_de'=>'Carbon-Gravel-Bike mit Future Shock 2.0 und elektronischer Shimano GRX Di2 Gruppe.','price'=>3799.00,'sale_price'=>3199.00,'is_featured'=>true,'bike_type'=>'Gravel Endurance','wheel_size'=>'700c','frame_material'=>'Carbone FACT 9r','number_of_speeds'=>'22 vitesses Shimano GRX Di2','suspension_type'=>'Future Shock 2.0','brake_style'=>'Disque hydraulique Shimano GRX','weight'=>'8,7 kg','warranty_type'=>'Garantie Specialized 5 ans','colors'=>['Sable','Bleu','Noir'],'imgs'=>[[$I['gravel_a'],'Sable'],[$I['gravel_b'],'Bleu'],[$I['route_a'],'Noir']],'sizes'=>'44,49,52,54,56,58,61']);

        $add(['cat'=>'gravel','brand'=>'Giant','name'=>'Giant Revolt Advanced Pro 0 2025','name_de'=>'Giant Revolt Advanced Pro 0 2025','slug'=>'giant-revolt-advanced-pro-0','description'=>'Gravel bike carbone avec D-Fuse et groupe SRAM Force AXS. Pour les longues aventures sans compromis.','description_de'=>'Carbon-Gravel-Bike mit D-Fuse und SRAM Force AXS für lange Abenteuer.','price'=>4299.00,'sale_price'=>null,'is_new'=>true,'bike_type'=>'Gravel Carbone','wheel_size'=>'700c','frame_material'=>'Carbone Advanced Grade','number_of_speeds'=>'12 vitesses SRAM Force AXS','suspension_type'=>'D-Fuse carbone','brake_style'=>'Disque hydraulique SRAM Force','weight'=>'8,3 kg','warranty_type'=>'Garantie Giant 5 ans','colors'=>['Noir','Vert'],'imgs'=>[[$I['gravel_a'],'Noir'],[$I['gravel_b'],'Vert']],'sizes'=>'XXS,XS,S,M,ML,L,XL']);

        $add(['cat'=>'gravel','brand'=>'Cannondale','name'=>'Cannondale Topstone Carbon GRX 600','name_de'=>'Cannondale Topstone Carbon GRX 600','slug'=>'cannondale-topstone-carbon-grx-600','description'=>'Gravel bike carbone avec KingPin suspension 30mm et groupe Shimano GRX 600. Confort et agilité.','description_de'=>'Carbon-Gravel-Bike mit KingPin 30mm Federung und Shimano GRX 600. Komfort und Agilität.','price'=>3299.00,'sale_price'=>null,'bike_type'=>'Gravel Aventure','wheel_size'=>'700c','frame_material'=>'Carbone BallisTec','number_of_speeds'=>'22 vitesses Shimano GRX 600','suspension_type'=>'KingPin 30mm','brake_style'=>'Disque hydraulique Shimano GRX','weight'=>'9,0 kg','warranty_type'=>'Garantie Cannondale à vie','colors'=>['Vert','Gris'],'imgs'=>[[$I['gravel_b'],'Vert'],[$I['gravel_a'],'Gris']],'sizes'=>'XS,S,M,L,XL,XXL']);

        foreach ([
            ['Trek','Trek Checkpoint ALR 4 GRX Aluminium','trek-checkpoint-alr4-grx','Gravel bike aluminium avec groupe Shimano GRX. L\'aventure à prix accessible.',1499.00,null],
            ['Salsa','Salsa Warbird Carbon GRX 600','salsa-warbird-carbon-grx','Gravel bike carbone américain pour les longues distances. Groupe Shimano GRX 600.',3799.00,3299.00],
            ['Orbea','Orbea Terra M30 GRX 1x','orbea-terra-m30-grx','Gravel bike aluminium avec groupe Shimano GRX 1x. Géométrie aventure.',1699.00,null],
            ['Merida','Merida Silex 400 GRX 2025','merida-silex-400-grx','Gravel bike aluminium avec fourche carbone et groupe Shimano GRX 400.',1299.00,null],
            ['Scott','Scott Addict Gravel 20 GRX 2025','scott-addict-gravel-20','Gravel bike carbone HMF avec groupe Shimano GRX 600. Légèreté et polyvalence.',3499.00,null],
            ['Cube','Cube Nuroad Race GRX Disc','cube-nuroad-race-grx-disc','Gravel bike aluminium Superlite avec groupe Shimano GRX 600. Performance et endurance.',1199.00,999.00],
            ['Norco','Norco Search XR A2 GRX 2025','norco-search-xr-a2-grx','Gravel bike aluminium canadien avec groupe Shimano GRX 400. Exploration sans limites.',1599.00,null],
        ] as [$brand, $name, $slug, $desc, $price, $sale]) {
            $add(['cat'=>'gravel','brand'=>$brand,'name'=>$name,'name_de'=>$name,'slug'=>$slug,'description'=>$desc,'description_de'=>$desc,'price'=>$price,'sale_price'=>$sale,'bike_type'=>'Gravel','wheel_size'=>'700c','frame_material'=>'Aluminium/Carbone','number_of_speeds'=>'22 vitesses Shimano GRX','suspension_type'=>'Rigide','brake_style'=>'Disque hydraulique Shimano GRX','weight'=>'9,5 kg','warranty_type'=>'Garantie 2-5 ans','colors'=>['Noir','Vert'],'imgs'=>[[$I['gravel_a'],'Noir'],[$I['gravel_b'],'Vert']],'sizes'=>'XS,S,M,L,XL']);
        }

        // ════════════════════════════════════════════════════════
        // ██ VILLE — 18 produits
        // ════════════════════════════════════════════════════════

        $add(['cat'=>'ville','brand'=>'Trek','name'=>'Trek FX 3 Disc Fitness City','name_de'=>'Trek FX 3 Disc Fitness Stadtrad','slug'=>'trek-fx3-disc-fitness','description'=>'Vélo de ville polyvalent avec fourche carbone et Shimano Acera 24 vitesses. Parfait pour la ville et les sorties sport.','description_de'=>'Vielseitiges Stadtrad mit Carbon-Gabel und Shimano Acera 24-Gang. Perfekt für Stadt und Sport.','price'=>899.00,'sale_price'=>null,'is_featured'=>true,'bike_type'=>'Fitness/Ville','wheel_size'=>'700c','frame_material'=>'Aluminium Alpha Gold','number_of_speeds'=>'24 vitesses Shimano Acera','suspension_type'=>'Fourche rigide carbone','brake_style'=>'Disque hydraulique Shimano','weight'=>'10,8 kg','warranty_type'=>'Garantie Trek à vie','colors'=>['Gris','Noir','Bleu'],'imgs'=>[[$I['ville_a'],'Gris'],[$I['ville_b'],'Noir'],[$I['gravel_a'],'Bleu']],'sizes'=>'XS,S,M,L,XL,XXL']);

        $add(['cat'=>'ville','brand'=>'Trek','name'=>'Trek Verve 2 Disc Vélo Ville','name_de'=>'Trek Verve 2 Disc Stadtrad','slug'=>'trek-verve-2-disc','description'=>'Vélo de ville confortable avec position droite et freins à disque. Idéal pour les déplacements quotidiens en ville.','description_de'=>'Komfortables Stadtrad mit aufrechter Position und Scheibenbremsen für den Alltag.','price'=>749.00,'sale_price'=>649.00,'bike_type'=>'Ville Confort','wheel_size'=>'700c','frame_material'=>'Aluminium Alpha Silver','number_of_speeds'=>'21 vitesses Shimano','suspension_type'=>'Fourche rigide','brake_style'=>'Disque mécanique Tektro','weight'=>'12,4 kg','warranty_type'=>'Garantie Trek à vie','colors'=>['Noir','Blanc','Bleu'],'imgs'=>[[$I['ville_a'],'Noir'],[$I['ville_b'],'Blanc'],[$I['gravel_a'],'Bleu']],'sizes'=>'XS,S,M,L,XL,XXL']);

        $add(['cat'=>'ville','brand'=>'Giant','name'=>'Giant Escape 2 Disc Commuter','name_de'=>'Giant Escape 2 Disc Pendler','slug'=>'giant-escape-2-disc','description'=>'Vélo de ville rapide et polyvalent avec freins à disque hydrauliques. Position sportive pour un pédalage efficace.','description_de'=>'Schnelles und vielseitiges Stadtrad mit hydraulischen Scheibenbremsen. Sportliche Position.','price'=>749.00,'sale_price'=>649.00,'bike_type'=>'Ville/Commuter','wheel_size'=>'700c','frame_material'=>'Aluminium ALUXX','number_of_speeds'=>'16 vitesses Shimano Claris','suspension_type'=>'Rigide','brake_style'=>'Disque hydraulique Tektro','weight'=>'11,2 kg','warranty_type'=>'Garantie Giant 2 ans','colors'=>['Noir','Gris','Bleu'],'imgs'=>[[$I['ville_a'],'Noir'],[$I['ville_b'],'Gris'],[$I['gravel_a'],'Bleu']],'sizes'=>'XS,S,M,L,XL,XXL']);

        $add(['cat'=>'ville','brand'=>'Cube','name'=>'Cube Hyde Race Commuter Urbain','name_de'=>'Cube Hyde Race Pendler','slug'=>'cube-hyde-race-commuter','description'=>'Vélo commuter performant avec Shimano Deore 10 vitesses et freins hydrauliques. Taillé pour distancer les embouteillages.','description_de'=>'Leistungsstarkes Pendlerrad mit Shimano Deore 10-Gang und hydraulischen Bremsen.','price'=>999.00,'sale_price'=>null,'is_new'=>true,'bike_type'=>'Ville/Commuter','wheel_size'=>'700c','frame_material'=>'Aluminium 6061','number_of_speeds'=>'10 vitesses Shimano Deore','suspension_type'=>'Rigide','brake_style'=>'Disque hydraulique Shimano','weight'=>'10,4 kg','warranty_type'=>'Garantie Cube 2 ans','colors'=>['Noir','Gris','Vert'],'imgs'=>[[$I['ville_a'],'Noir'],[$I['ville_b'],'Gris'],[$I['gravel_b'],'Vert']],'sizes'=>'XS,S,M,L,XL']);

        foreach ([
            ['Gazelle','Gazelle Esprit C7 HMS Ville','gazelle-esprit-c7-ville','Vélo hollandais premium avec 7 vitesses Shimano Nexus et frein à rétropédalage.',849.00,null],
            ['Batavus','Batavus Dinsdag 8D Pure Ego','batavus-dinsdag-8d','Vélo hollandais avec transmission interne 8 vitesses Shimano Nexus. Minimal et élégant.',1099.00,null],
            ['Peugeot','Peugeot LC01 7 Allure Ville','peugeot-lc01-7-allure','Vélo de ville élégant avec 7 vitesses Shimano Altus. Le style français pour vos trajets.',699.00,599.00],
            ['Riese & Müller','Riese & Müller Roadster 5 Mixte','riese-muller-roadster-5','Vélo urbain premium allemand avec 8 vitesses Shimano Nexus et freins hydrauliques Magura.',1299.00,null],
            ['Votec','Votec VC Comp Commuter 11V','votec-vc-comp-commuter','Vélo commuter allemand avec Shimano 105 11 vitesses. Léger et rapide pour la ville.',1199.00,999.00],
            ['Specialized','Specialized Sirrus 3.0 Disc 2025','specialized-sirrus-3-disc','Vélo fitness avec freins hydrauliques et Shimano Deore 10 vitesses. Efficace et confortable.',899.00,null],
        ] as [$brand, $name, $slug, $desc, $price, $sale]) {
            $add(['cat'=>'ville','brand'=>$brand,'name'=>$name,'name_de'=>$name,'slug'=>$slug,'description'=>$desc,'description_de'=>$desc,'price'=>$price,'sale_price'=>$sale,'bike_type'=>'Ville','wheel_size'=>'700c','frame_material'=>'Aluminium','number_of_speeds'=>'7-11 vitesses','suspension_type'=>'Rigide','brake_style'=>'Disque hydraulique','weight'=>'12,5 kg','warranty_type'=>'Garantie 2 ans','colors'=>['Noir','Gris'],'imgs'=>[[$I['ville_a'],'Noir'],[$I['ville_b'],'Gris']],'sizes'=>'XS,S,M,L,XL']);
        }

        // ════════════════════════════════════════════════════════
        // ██ ÉLECTRIQUE — 30 produits
        // ════════════════════════════════════════════════════════

        $add(['cat'=>'electrique','brand'=>'Trek','name'=>'Trek Powerfly FS 9 E-MTB Tout-Suspendu','name_de'=>'Trek Powerfly FS 9 Fully E-MTB','slug'=>'trek-powerfly-fs9-emtb','description'=>'VTT électrique tout-suspendu avec moteur Bosch Performance CX 85Nm et batterie 625Wh. 100km d\'autonomie en mode Eco.','description_de'=>'Fully E-MTB mit Bosch Performance CX 85Nm Motor und 625Wh Akku. 100km Reichweite im Eco-Modus.','price'=>6499.00,'sale_price'=>5799.00,'is_featured'=>true,'is_new'=>true,'bike_type'=>'E-MTB Tout-suspendu','wheel_size'=>'29"','frame_material'=>'Aluminium Alpha Platinum','number_of_speeds'=>'12 vitesses Shimano Deore XT','suspension_type'=>'Fox 36 Rhythm 140mm / Fox Float DPS 140mm','brake_style'=>'Hydraulique Shimano Deore XT 4 pistons','power_source'=>'Batterie lithium-ion','motor_power'=>'Bosch Performance CX 250W / 85Nm','battery_capacity'=>'625 Wh','max_speed'=>'25 km/h','max_range'=>'100 km mode Eco','charging_time'=>'4h30','weight'=>'24,5 kg','warranty_type'=>'Garantie Trek 2 ans + Bosch 2 ans','colors'=>['Noir','Bleu','Anthracite'],'imgs'=>[[$I['elec_a'],'Noir'],[$I['elec_b'],'Bleu'],[$I['vtt_a'],'Anthracite']],'sizes'=>'S,M,L,XL']);

        $add(['cat'=>'electrique','brand'=>'Trek','name'=>'Trek Verve+ 3 Lowstep E-Bike Urbain','name_de'=>'Trek Verve+ 3 Lowstep E-Bike Urban','slug'=>'trek-verve-plus-3-lowstep','description'=>'E-Bike urbain step-through avec moteur Bosch Active Line Plus et batterie 500Wh. Équipé garde-boues, porte-bagages et éclairage.','description_de'=>'Step-Through E-Bike mit Bosch Active Line Plus Motor und 500Wh Akku. Mit Schutzblechen, Gepäckträger und Beleuchtung.','price'=>2799.00,'sale_price'=>2399.00,'bike_type'=>'E-Bike Urbain Step-Through','wheel_size'=>'700c','frame_material'=>'Aluminium Alpha','number_of_speeds'=>'9 vitesses Shimano Alivio','suspension_type'=>'Fourche rigide carbone','brake_style'=>'Disque hydraulique Shimano MT200','power_source'=>'Batterie lithium-ion amovible','motor_power'=>'Bosch Active Line Plus 250W / 50Nm','battery_capacity'=>'500 Wh','max_speed'=>'25 km/h','max_range'=>'90 km mode Eco','charging_time'=>'4h','weight'=>'23,6 kg','warranty_type'=>'Garantie Trek 2 ans + Bosch 2 ans','included_components'=>'Garde-boues, porte-bagages, béquille, éclairage intégré','colors'=>['Gris','Noir','Blanc'],'imgs'=>[[$I['elec_a'],'Gris'],[$I['ville_a'],'Noir'],[$I['elec_b'],'Blanc']],'sizes'=>'XS,S,M,L,XL']);

        $add(['cat'=>'electrique','brand'=>'Specialized','name'=>'Specialized Turbo Levo SL Comp Carbon','name_de'=>'Specialized Turbo Levo SL Comp Carbon','slug'=>'specialized-turbo-levo-sl-comp','description'=>'E-MTB carbone ultra-léger 17,5kg avec moteur SL 1.1 240W. Sensations du VTT traditionnel avec assistance discrète.','description_de'=>'Ultra-leichtes Carbon-E-MTB 17,5kg mit SL 1.1 240W Motor. MTB-Gefühl mit dezenter Unterstützung.','price'=>8999.00,'sale_price'=>null,'is_featured'=>true,'is_new'=>true,'bike_type'=>'E-MTB Léger Carbone','wheel_size'=>'29"','frame_material'=>'Carbone FACT 11m','number_of_speeds'=>'12 vitesses SRAM GX Eagle','suspension_type'=>'Fox 34 Float 130mm / Fox Float DPS 130mm','brake_style'=>'Hydraulique SRAM G2 R','power_source'=>'Batterie intégrée','motor_power'=>'Specialized SL 1.1 240W / 35Nm','battery_capacity'=>'320 Wh + Range Extender','max_speed'=>'25 km/h','max_range'=>'130 km avec Range Extender','charging_time'=>'2h30','weight'=>'17,5 kg','warranty_type'=>'Garantie Specialized 5 ans','special_features'=>'• Moteur SL ultra-léger (-40% vs concurrents)
• Compatible Range Extender +160Wh
• Application Mission Control','colors'=>['Vert','Noir','Blanc'],'imgs'=>[[$I['elec_b'],'Vert'],[$I['elec_a'],'Noir'],[$I['vtt_f'],'Blanc']],'sizes'=>'S,M,L,XL']);

        $add(['cat'=>'electrique','brand'=>'Giant','name'=>'Giant Explore E+ 2 Pro E-Trekking','name_de'=>'Giant Explore E+ 2 Pro E-Trekking','slug'=>'giant-explore-e-plus-2-pro','description'=>'E-Bike trekking avec moteur SyncDrive Pro2 80Nm et batterie 500Wh. Compagnon idéal pour vos randonnées.','description_de'=>'E-Trekking Bike mit SyncDrive Pro2 80Nm Motor und 500Wh Akku für Touren.','price'=>3299.00,'sale_price'=>2899.00,'bike_type'=>'E-Trekking','wheel_size'=>'700c','frame_material'=>'Aluminium ALUXX','number_of_speeds'=>'11 vitesses Shimano Deore','suspension_type'=>'Fourche télescopique 63mm','brake_style'=>'Disque hydraulique Shimano Deore','power_source'=>'Batterie intégrée','motor_power'=>'Giant SyncDrive Pro2 250W / 80Nm','battery_capacity'=>'500 Wh','max_speed'=>'25 km/h','max_range'=>'100 km mode Eco','charging_time'=>'4h','weight'=>'22,3 kg','warranty_type'=>'Garantie Giant 2 ans + 2 ans batterie','colors'=>['Noir','Gris','Bleu'],'imgs'=>[[$I['elec_a'],'Noir'],[$I['elec_b'],'Gris'],[$I['ville_a'],'Bleu']],'sizes'=>'XS,S,M,L,XL']);

        $add(['cat'=>'electrique','brand'=>'Cube','name'=>'Cube Stereo Hybrid 140 HPC Race 750','name_de'=>'Cube Stereo Hybrid 140 HPC Race 750','slug'=>'cube-stereo-hybrid-140-hpc-750','description'=>'VTT électrique tout-suspendu carbone avec batterie 750Wh et moteur Bosch Performance CX Smart System.','description_de'=>'Carbon Fully E-MTB mit 750Wh Akku und Bosch Performance CX Smart System Motor.','price'=>5999.00,'sale_price'=>null,'is_featured'=>true,'bike_type'=>'E-MTB Carbone','wheel_size'=>'29"','frame_material'=>'Carbone HPC','number_of_speeds'=>'12 vitesses Shimano Deore XT','suspension_type'=>'Fox 36 Float 140mm / Fox Float X2 140mm','brake_style'=>'Hydraulique Shimano XT 4 pistons','power_source'=>'Batterie lithium-ion','motor_power'=>'Bosch Performance CX Smart System 85Nm','battery_capacity'=>'750 Wh','max_speed'=>'25 km/h','max_range'=>'120 km mode Eco','charging_time'=>'5h','weight'=>'25,8 kg','warranty_type'=>'Garantie Cube 2 ans + Bosch 2 ans','colors'=>['Noir','Gris'],'imgs'=>[[$I['elec_a'],'Noir'],[$I['elec_b'],'Gris']],'sizes'=>'S,M,L,XL']);

        $add(['cat'=>'electrique','brand'=>'Riese & Müller','name'=>'Riese & Müller Supercharger GT Rohloff','name_de'=>'Riese & Müller Supercharger GT Rohloff','slug'=>'riese-muller-supercharger-gt','description'=>'Le roi des e-bikes longue distance. Double batterie 1125Wh et transmission Rohloff 14 vitesses. Jusqu\'à 200km d\'autonomie.','description_de'=>'Der König der Langstrecken-E-Bikes. Doppelakku 1125Wh und Rohloff 14-Gang. Bis 200km Reichweite.','price'=>8499.00,'sale_price'=>null,'is_featured'=>true,'is_new'=>true,'bike_type'=>'E-Trekking Longue Distance','wheel_size'=>'29"','frame_material'=>'Aluminium premium','number_of_speeds'=>'14 vitesses Rohloff E-14','suspension_type'=>'Fourche suspendue 63mm','brake_style'=>'Disque hydraulique Magura MT5e','power_source'=>'Double batterie lithium-ion','motor_power'=>'Bosch Performance CX 250W / 85Nm','battery_capacity'=>'1125 Wh (2×562,5 Wh)','max_speed'=>'25 km/h','max_range'=>'200+ km mode Eco','charging_time'=>'6h','weight'=>'33,5 kg','warranty_type'=>'Garantie R&M 2 ans + Bosch 2 ans','colors'=>['Noir','Gris','Bleu'],'imgs'=>[[$I['elec_a'],'Noir'],[$I['elec_b'],'Gris'],[$I['ville_a'],'Bleu']],'sizes'=>'43,49,54']);

        $add(['cat'=>'electrique','brand'=>'Stromer','name'=>'Stromer ST5 Sport 45 km/h Speed Pedelec','name_de'=>'Stromer ST5 Sport 45 km/h Speed-Pedelec','slug'=>'stromer-st5-sport-speed-pedelec','description'=>'Speed pedelec suisse assisté jusqu\'à 45 km/h. Application myStromer pour contrôler et sécuriser votre vélo.','description_de'=>'Schweizer Speed-Pedelec mit Unterstützung bis 45 km/h. myStromer App für Kontrolle und Sicherheit.','price'=>7999.00,'sale_price'=>null,'is_featured'=>true,'is_new'=>true,'bike_type'=>'Speed Pedelec 45 km/h','wheel_size'=>'27.5"','frame_material'=>'Aluminium','number_of_speeds'=>'12 vitesses SRAM Red eTap AXS','suspension_type'=>'Rigide','brake_style'=>'Disque hydraulique Magura MT5e','power_source'=>'Batterie intégrée','motor_power'=>'Stromer SYNO Drive II 250W / 48Nm','battery_capacity'=>'983 Wh','max_speed'=>'45 km/h','max_range'=>'150 km mode Eco','charging_time'=>'4h30','weight'=>'26,5 kg','warranty_type'=>'Garantie Stromer 2 ans','colors'=>['Noir','Blanc'],'imgs'=>[[$I['elec_a'],'Noir'],[$I['elec_b'],'Blanc']],'sizes'=>'42,48,54']);

        $add(['cat'=>'electrique','brand'=>'Haibike','name'=>'Haibike AllMtn 6 29" E-MTB 2025','name_de'=>'Haibike AllMtn 6 29" E-MTB 2025','slug'=>'haibike-allmtn-6-29-emtb','description'=>'VTT électrique tout-suspendu avec moteur Yamaha PW-X3 85Nm et batterie 630Wh. Autonomie pour les sentiers les plus lointains.','description_de'=>'Fully E-MTB mit Yamaha PW-X3 85Nm Motor und 630Wh Akku für weit entfernte Trails.','price'=>4499.00,'sale_price'=>3899.00,'bike_type'=>'E-MTB Tout-suspendu','wheel_size'=>'29"','frame_material'=>'Aluminium 6061','number_of_speeds'=>'12 vitesses Shimano Deore','suspension_type'=>'Fox 36 Rhythm 150mm / Fox Float DPS 150mm','brake_style'=>'Hydraulique Shimano Deore XT 4 pistons','power_source'=>'Batterie Yamaha intégrée','motor_power'=>'Yamaha PW-X3 250W / 85Nm','battery_capacity'=>'630 Wh','max_speed'=>'25 km/h','max_range'=>'95 km mode Eco','charging_time'=>'4h','weight'=>'24,8 kg','warranty_type'=>'Garantie Haibike 2 ans','colors'=>['Noir','Vert','Bleu'],'imgs'=>[[$I['elec_a'],'Noir'],[$I['vtt_d'],'Vert'],[$I['elec_b'],'Bleu']],'sizes'=>'S,M,L,XL']);

        $add(['cat'=>'electrique','brand'=>'Orbea','name'=>'Orbea Rise LT M20 E-MTB Léger','name_de'=>'Orbea Rise LT M20 E-MTB Leicht','slug'=>'orbea-rise-lt-m20-emtb','description'=>'E-MTB carbone ultra-léger 19kg avec moteur Shimano EP8 RS 85Nm. Sensations pures du VTT avec assistance.','description_de'=>'Ultraleichtes Carbon-E-MTB 19kg mit Shimano EP8 RS 85Nm. Pures MTB-Gefühl mit Unterstützung.','price'=>6499.00,'sale_price'=>null,'is_new'=>true,'is_featured'=>true,'bike_type'=>'E-MTB Léger Carbone','wheel_size'=>'29"','frame_material'=>'Carbone OMX','number_of_speeds'=>'12 vitesses Shimano Deore XT','suspension_type'=>'Fox 34 Float 130mm / Fox Float DPS 130mm','brake_style'=>'Hydraulique Shimano XT','power_source'=>'Batterie lithium-ion','motor_power'=>'Shimano EP8 RS 250W / 85Nm','battery_capacity'=>'360 Wh + Range Extender','max_speed'=>'25 km/h','max_range'=>'100 km avec Range Extender','charging_time'=>'2h30','weight'=>'19,5 kg','warranty_type'=>'Garantie Orbea 5 ans','colors'=>['Bleu','Vert','Noir'],'imgs'=>[[$I['elec_b'],'Bleu'],[$I['vtt_d'],'Vert'],[$I['elec_a'],'Noir']],'sizes'=>'XS,S,M,L,XL']);

        $add(['cat'=>'electrique','brand'=>'Moustache','name'=>'Moustache Samedi 28.7 Open E-Bike','name_de'=>'Moustache Samedi 28.7 Open E-Bike','slug'=>'moustache-samedi-28-7-open','description'=>'E-Bike trekking fabriqué à Épinal (France) avec moteur Bosch Performance CX et batterie 625Wh. Savoir-faire français.','description_de'=>'E-Trekking Bike aus Épinal (Frankreich) mit Bosch Performance CX Motor und 625Wh Akku.','price'=>3999.00,'sale_price'=>null,'is_new'=>true,'bike_type'=>'E-Trekking','wheel_size'=>'28"','frame_material'=>'Aluminium','number_of_speeds'=>'11 vitesses Shimano Deore','suspension_type'=>'Fourche suspendue 63mm','brake_style'=>'Disque hydraulique Shimano Deore','power_source'=>'Batterie Bosch intégrée','motor_power'=>'Bosch Performance CX 250W / 85Nm','battery_capacity'=>'625 Wh','max_speed'=>'25 km/h','max_range'=>'120 km mode Eco','charging_time'=>'4h30','weight'=>'25,4 kg','warranty_type'=>'Garantie Moustache 2 ans + Bosch 2 ans','colors'=>['Vert','Gris','Noir'],'imgs'=>[[$I['elec_b'],'Vert'],[$I['elec_a'],'Gris'],[$I['ville_a'],'Noir']],'sizes'=>'40,44,48,52,56']);

        foreach ([
            ['Cannondale','Cannondale Moterra Neo Carbon 1 E-MTB','cannondale-moterra-neo-carbon-1','VTT électrique tout-suspendu carbone avec Bosch Performance CX Gen4 85Nm et batterie 630Wh.',7499.00,null],
            ['BMC','BMC Roadmachine AMP ONE E-Route Carbone','bmc-roadmachine-amp-one','Vélo de route électrique avec moteur Fazua Ride 60 ultra-léger et Shimano Ultegra Di2.',8499.00,null],
            ['Flyer','Flyer Upstreet 5 7.23 E-Bike Urbain','flyer-upstreet-5-7-23','E-Bike urbain suisse avec moteur Shimano EP6 60Nm et batterie 630Wh. Design élégant.',3499.00,2999.00],
            ['Gazelle','Gazelle Ultimate T10 HMB E-Trekking','gazelle-ultimate-t10-hmb','E-Trekking hollandais premium avec Bosch Performance Line Speed et 750Wh. Jusqu\'à 140km.',4299.00,3799.00],
            ['Giant','Giant Reign E+ 1 Pro E-Enduro 2025','giant-reign-e-plus-1-pro','E-Enduro 160mm carbone avec moteur SyncDrive Pro2 85Nm et batterie EnergyPak 600Wh.',6499.00,null],
            ['Specialized','Specialized Turbo Vado SL 5.0 EQ E-Ville','specialized-turbo-vado-sl-5','E-Bike de ville ultra-léger avec moteur SL 1.1 240W. Entièrement équipé pour la ville.',3999.00,null],
        ] as [$brand, $name, $slug, $desc, $price, $sale]) {
            $add(['cat'=>'electrique','brand'=>$brand,'name'=>$name,'name_de'=>$name,'slug'=>$slug,'description'=>$desc,'description_de'=>$desc,'price'=>$price,'sale_price'=>$sale,'bike_type'=>'E-Bike','wheel_size'=>'29"','frame_material'=>'Aluminium/Carbone','number_of_speeds'=>'12 vitesses','suspension_type'=>'Suspendu','brake_style'=>'Disque hydraulique','power_source'=>'Batterie lithium-ion','motor_power'=>'Bosch Performance CX 250W / 85Nm','battery_capacity'=>'625 Wh','max_speed'=>'25 km/h','max_range'=>'100 km mode Eco','charging_time'=>'4h','weight'=>'24 kg','warranty_type'=>'Garantie 2 ans','colors'=>['Noir','Gris'],'imgs'=>[[$I['elec_a'],'Noir'],[$I['elec_b'],'Gris']],'sizes'=>'S,M,L,XL']);
        }

        // ════════════════════════════════════════════════════════
        // ██ BMX — 8 produits
        // ════════════════════════════════════════════════════════

        foreach ([
            ['Mongoose','Mongoose Legion L60 20" Freestyle','mongoose-legion-l60-20','BMX freestyle avec cadre acier Hi-Ten robuste. Parfait pour les riders intermédiaires au skatepark.',399.00,329.00],
            ['Wethepeople','Wethepeople Crysis 20" Race Pro','wethepeople-crysis-20-race','BMX race ultra-léger avec cadre aluminium 6061 T6. Conçu pour la compétition.',699.00,null],
            ['Colony','Colony Apprentice 20" Freestyle','colony-apprentice-20','BMX freestyle australien robuste et abordable. Cadre acier Hi-Ten pour tous les tricks.',449.00,369.00],
            ['Subrosa','Subrosa Salvador Park 20"','subrosa-salvador-park-20','BMX park avec cadre Chromoly léger. Géométrie optimisée pour les bowls et rampes.',599.00,null],
            ['Haro','Haro Leucadia DLX 26" Cruiser','haro-leucadia-dlx-26','BMX cruiser avec grandes roues 26". Polyvalent skatepark et extérieur.',549.00,null],
            ['GT','GT Performer Heritage 20.5" BMX','gt-performer-heritage-20','BMX freestyle iconique avec cadre Chromoly et géométrie classique. Une légende du BMX.',799.00,699.00],
            ['Stolen','Stolen Casino XL 20" Street','stolen-casino-xl-20','BMX street avec cadre acier Tibo Heat Treated. Taillé pour le street et les parcs.',549.00,null],
            ['Sunday','Sunday Primer Park 20"','sunday-primer-park-20','BMX park avec cadre Chromoly 4130 multi-butted. Design épuré pour les parcs.',499.00,null],
        ] as [$brand, $name, $slug, $desc, $price, $sale]) {
            $add(['cat'=>'bmx','brand'=>$brand,'name'=>$name,'name_de'=>$name,'slug'=>$slug,'description'=>$desc,'description_de'=>$desc,'price'=>$price,'sale_price'=>$sale,'bike_type'=>'BMX','wheel_size'=>'20"','frame_material'=>'Acier/Aluminium','number_of_speeds'=>'1 vitesse','suspension_type'=>'Rigide','brake_style'=>'Patins V-Brake','weight'=>'11 kg','warranty_type'=>'Garantie 1 an','colors'=>['Noir','Blanc','Rouge'],'imgs'=>[[$I['bmx_a'],'Noir'],[$I['vtt_a'],'Blanc'],[$I['vtt_c'],'Rouge']],'sizes'=>'Taille unique']);
        }

        // ════════════════════════════════════════════════════════
        // ██ ENFANT — 15 produits
        // ════════════════════════════════════════════════════════

        $add(['cat'=>'enfant','brand'=>'Trek','name'=>'Trek Precaliber 20" 7V Enfant','name_de'=>'Trek Precaliber 20" 7G Kind','slug'=>'trek-precaliber-20-7v','description'=>'Vélo enfant 6-10 ans avec transmission 7 vitesses Shimano et freins ajustables. Grandit avec l\'enfant.','description_de'=>'Kinderrad 6-10 Jahre mit 7-Gang Shimano Schaltung und anpassbaren Bremsen.','price'=>499.00,'sale_price'=>449.00,'bike_type'=>'Vélo Enfant','wheel_size'=>'20"','age_range'=>'6 – 10 ans','frame_material'=>'Aluminium Alpha','number_of_speeds'=>'7 vitesses Shimano','suspension_type'=>'Rigide','brake_style'=>'Patins ajustables','weight'=>'9,3 kg','max_load'=>'50 kg','warranty_type'=>'Garantie Trek à vie','colors'=>['Rose','Bleu','Vert','Noir'],'imgs'=>[[$I['enfant_a'],'Rose'],[$I['vtt_b'],'Bleu'],[$I['vtt_d'],'Vert'],[$I['vtt_a'],'Noir']],'sizes'=>'Taille unique']);

        $add(['cat'=>'enfant','brand'=>'woom','name'=>'woom 4 Vélo Enfant 20" Autrichien','name_de'=>'woom 4 Kinderfahrrad 20" Österreich','slug'=>'woom-4-velo-enfant-20','description'=>'Le vélo enfant autrichien légendaire 6-9 ans. Ultra-léger 6,9kg avec composants spécialement conçus pour les enfants.','description_de'=>'Das legendäre österreichische Kinderfahrrad 6-9 Jahre. Ultra-leicht 6,9kg mit kinderspezifischen Komponenten.','price'=>449.00,'sale_price'=>null,'is_featured'=>true,'bike_type'=>'Vélo Enfant','wheel_size'=>'20"','age_range'=>'6 – 9 ans','frame_material'=>'Aluminium léger','number_of_speeds'=>'7 vitesses Shimano','suspension_type'=>'Rigide','brake_style'=>'Patins enfant','weight'=>'6,9 kg','max_load'=>'50 kg','warranty_type'=>'Garantie woom 2 ans','colors'=>['Orange','Bleu','Rouge','Vert'],'imgs'=>[[$I['enfant_a'],'Orange'],[$I['vtt_b'],'Bleu'],[$I['vtt_c'],'Rouge'],[$I['vtt_d'],'Vert']],'sizes'=>'Taille unique']);

        $add(['cat'=>'enfant','brand'=>'woom','name'=>'woom 5 Vélo Enfant 24" Trail','name_de'=>'woom 5 Kinderfahrrad 24" Trail','slug'=>'woom-5-velo-enfant-24','description'=>'Vélo enfant 8-11 ans ultra-léger avec 8 vitesses Shimano. Les composants sont conçus pour les petites mains.','description_de'=>'Ultraleichtes Kinderfahrrad 8-11 Jahre mit 8-Gang Shimano. Komponenten für kleine Hände.','price'=>499.00,'sale_price'=>null,'bike_type'=>'Vélo Enfant','wheel_size'=>'24"','age_range'=>'8 – 11 ans','frame_material'=>'Aluminium léger','number_of_speeds'=>'8 vitesses Shimano','suspension_type'=>'Rigide','brake_style'=>'Patins ajustés enfant','weight'=>'7,6 kg','max_load'=>'60 kg','warranty_type'=>'Garantie woom 2 ans','colors'=>['Orange','Bleu','Rouge','Vert','Blanc'],'imgs'=>[[$I['enfant_a'],'Orange'],[$I['vtt_b'],'Bleu'],[$I['vtt_c'],'Rouge'],[$I['vtt_d'],'Vert'],[$I['vtt_f'],'Blanc']],'sizes'=>'Taille unique']);

        $add(['cat'=>'enfant','brand'=>'Scamp','name'=>'Scamp TallFox VTT Enfant 24"','name_de'=>'Scamp TallFox Kinder-MTB 24"','slug'=>'scamp-tallfox-vtt-24','description'=>'VTT enfant 8-13 ans avec fourche suspendue 50mm et composants Shimano. Un vrai VTT pour les jeunes riders.','description_de'=>'Kinder-MTB 8-13 Jahre mit 50mm Federgabel und Shimano Komponenten. Ein echtes MTB für junge Fahrer.','price'=>599.00,'sale_price'=>null,'is_new'=>true,'bike_type'=>'VTT Enfant','wheel_size'=>'24"','age_range'=>'8 – 13 ans','frame_material'=>'Aluminium 6061','number_of_speeds'=>'7 vitesses Shimano Tourney','suspension_type'=>'Fourche suspendue 50mm','brake_style'=>'Disque mécanique','weight'=>'10,5 kg','max_load'=>'65 kg','warranty_type'=>'Garantie 2 ans','colors'=>['Blanc','Bleu','Rouge'],'imgs'=>[[$I['enfant_a'],'Blanc'],[$I['vtt_b'],'Bleu'],[$I['vtt_c'],'Rouge']],'sizes'=>'Taille unique']);

        $add(['cat'=>'enfant','brand'=>'Puky','name'=>'Puky LR Ride 12" Draisienne','name_de'=>'Puky LR Ride 12" Laufrad','slug'=>'puky-lr-ride-12-draisienne','description'=>'Draisienne pour 2-5 ans avec guidon et selle réglables. Apprend l\'équilibre aux tout-petits en douceur.','description_de'=>'Laufrad für 2-5 Jahre mit verstellbarem Lenker und Sattel. Lehrt Gleichgewicht sanft.','price'=>149.00,'sale_price'=>129.00,'bike_type'=>'Draisienne','wheel_size'=>'12"','age_range'=>'2 – 5 ans','frame_material'=>'Acier','number_of_speeds'=>'Sans vitesses','suspension_type'=>'Rigide','brake_style'=>'Frein à main','weight'=>'3,5 kg','max_load'=>'25 kg','warranty_type'=>'Garantie Puky 2 ans','assembly_required'=>true,'colors'=>['Bleu','Rose','Rouge','Vert'],'imgs'=>[[$I['enfant_a'],'Bleu'],[$I['vtt_b'],'Rose'],[$I['vtt_c'],'Rouge'],[$I['vtt_d'],'Vert']],'sizes'=>'Taille unique']);

        foreach ([
            ['Frog Bikes','Frog 70 Vélo Enfant 26" Léger','frog-bikes-70-26','Vélo enfant 10-14 ans ultra-léger 8,6kg. Spécialement conçu par la marque britannique.',649.00,549.00,'9 – 14 ans'],
            ['Islabikes','Islabikes Beinn 20 Small Enfant','islabikes-beinn-20-small','Vélo enfant britannique premium 5-8 ans. Ultra-léger 6,2kg avec composants adaptés.',399.00,null,'5 – 8 ans'],
            ['Orbea','Orbea MX 24 XC Enfant VTT Trail','orbea-mx-24-xc-enfant','VTT enfant premium 9-13 ans avec fourche suspendue et Shimano Altus 8 vitesses.',549.00,489.00,'9 – 13 ans'],
            ['Trek','Trek Marlin 4 24" Enfant Junior','trek-marlin-4-24-junior','VTT hardtail junior avec fourche suspendue et freins à disque hydrauliques. Pour les jeunes riders exigeants.',599.00,null,'10 – 14 ans'],
            ['Specialized','Specialized Riprock 20" Enfant','specialized-riprock-20','Vélo enfant avec pneus 20x2,3" pour plus d\'adhérence. Idéal pour apprendre le trail.',449.00,null,'6 – 10 ans'],
        ] as [$brand, $name, $slug, $desc, $price, $sale, $age]) {
            $add(['cat'=>'enfant','brand'=>$brand,'name'=>$name,'name_de'=>$name,'slug'=>$slug,'description'=>$desc,'description_de'=>$desc,'price'=>$price,'sale_price'=>$sale,'bike_type'=>'Vélo Enfant','wheel_size'=>'20-26"','age_range'=>$age,'frame_material'=>'Aluminium','number_of_speeds'=>'7-8 vitesses','suspension_type'=>'Rigide','brake_style'=>'Patins/Disque','weight'=>'8 kg','max_load'=>'60 kg','warranty_type'=>'Garantie 2 ans','colors'=>['Bleu','Rose','Vert','Noir'],'imgs'=>[[$I['enfant_a'],'Bleu'],[$I['vtt_b'],'Rose'],[$I['vtt_d'],'Vert'],[$I['vtt_a'],'Noir']],'sizes'=>'Taille unique']);
        }

        // ════════════════════════════════════════════════════════
        // ██ RECONDITIONNÉ — 10 produits
        // ════════════════════════════════════════════════════════

        foreach ([
            ['Trek','Trek Marlin 5 29" Reconditionné Grade A','trek-marlin-5-recon-a','VTT hardtail entièrement révisé par nos techniciens. Transmission et freins en parfait état. Grade A = aucun défaut visible.',549.00,null,'Grade A - Comme neuf'],
            ['Specialized','Specialized Stumpjumper 29" Reconditionné A','specialized-stumpjumper-recon-a','Trail bike tout-suspendu révisé Grade A. Transmission SRAM et freins hydrauliques parfaits. Occasion rare.',1799.00,null,'Grade A - Comme neuf'],
            ['Trek','Trek FX 3 Disc Reconditionné Grade B','trek-fx3-disc-recon-b','Vélo fitness légers rayures esthétiques. Tous les composants vérifiés et pièces d\'usure remplacées. Grade B.',449.00,null,'Grade B - Très bon état'],
            ['Giant','Giant Explore E+ 1 Pro E-Bike Reconditionné','giant-explore-e-plus-recon','E-Bike trekking reconditionné Grade B. Batterie à 92% de capacité. Moteur et électronique parfaits.',1899.00,null,'Grade B - Batterie 92%'],
            ['Cannondale','Cannondale SuperSix EVO Carbon Reconditionné A','cannondale-supersix-evo-recon-a','Vélo de route carbone Grade A. Transmission Shimano Ultegra révisée. Cadre carbone intact. Occasion exceptionnelle.',1999.00,null,'Grade A - Comme neuf'],
            ['Trek','Trek Checkpoint ALR 5 Gravel Reconditionné','trek-checkpoint-alr5-recon','Gravel bike aluminium Grade B. Rayures légères. Groupe Shimano GRX révisé. Excellent rapport qualité-prix.',799.00,null,'Grade B - Très bon état'],
            ['Giant','Giant TCR Advanced 2 Disc Reconditionné A','giant-tcr-advanced-2-recon-a','Vélo de route carbone Grade A révisé intégralement. Shimano 105 et freins en parfait état.',1499.00,null,'Grade A - Comme neuf'],
            ['Cube','Cube Stereo 140 HPC Reconditionné Grade B','cube-stereo-140-recon-b','Trail bike tout-suspendu carbone Grade B. Suspension révisée, transmission SRAM fonctionnelle.',2499.00,null,'Grade B - Très bon état'],
            ['Specialized','Specialized Diverge Comp Gravel Reconditionné','specialized-diverge-comp-recon','Gravel bike carbone Grade A. Future Shock révisé. Groupe Shimano GRX Di2 parfait.',2299.00,null,'Grade A - Comme neuf'],
            ['Trek','Trek Powerfly FS 5 E-MTB Reconditionné A','trek-powerfly-fs5-recon','VTT électrique tout-suspendu Grade A. Batterie à 95% de capacité. Moteur Bosch révisé.',3499.00,null,'Grade A - Batterie 95%'],
        ] as [$brand, $name, $slug, $desc, $price, $sale, $grade]) {
            $add(['cat'=>'reconditionne','brand'=>$brand,'name'=>$name,'name_de'=>$name,'slug'=>$slug,'description'=>$desc.' '.$grade.'. Garantie reconditionnement 6 mois incluse.','description_de'=>$desc.' '.$grade.'. 6 Monate Wiederaufbereitungsgarantie inklusive.','price'=>$price,'sale_price'=>$sale,'bike_type'=>'Reconditionné','wheel_size'=>'29"','frame_material'=>'Aluminium/Carbone','number_of_speeds'=>'Varie','suspension_type'=>'Varie','brake_style'=>'Hydraulique','weight'=>'Variable','warranty_type'=>'Garantie reconditionnement 6 mois','colors'=>['Coloris d\'origine'],'imgs'=>[[$I['recon_a'],'Coloris d\'origine']],'sizes'=>'Varie selon le modèle']);
        }

        // ── Résumé ────────────────────────────────────────────
        $total = Product::count();
        $imgs  = ProductImage::count();
        $cats  = Category::count();

        $this->command->info('');
        $this->command->info('╔══════════════════════════════════════╗');
        $this->command->info('║  ✅  MegaBikeSeeder terminé !        ║');
        $this->command->info('╠══════════════════════════════════════╣');
        $this->command->info("║  📂  Catégories : {$cats}                     ║");
        $this->command->info("║  🚲  Produits   : {$total}                  ║");
        $this->command->info("║  🖼   Images    : {$imgs}                  ║");
        $this->command->info('╚══════════════════════════════════════╝');
    }
}