<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Product;
use App\Models\Category;
use App\Models\ProductImage;

/**
 * MegaBikeSeeder — 160+ vélos avec images réelles de vélos Unsplash
 *
 * LANCEMENT : php artisan db:seed --class=MegaBikeSeeder
 * ⚠️  Remet à zéro products + images (catégories conservées si existantes)
 */
class MegaBikeSeeder extends Seeder
{
    // ── URLs Unsplash : UNIQUEMENT des photos de vélos ────────
    const I = [
        // VTT hardtail (vue côté, fond blanc/studio)
        'h1' => 'https://images.unsplash.com/photo-1544191696-102dbdaeeaa0?w=900&q=85',
        'h2' => 'https://images.unsplash.com/photo-1576435728678-68d0fbf94946?w=900&q=85',
        'h3' => 'https://images.unsplash.com/photo-1553764854-53ac4f1e175b?w=900&q=85',
        // VTT tout-suspendu / enduro
        'fs1'=> 'https://images.unsplash.com/photo-1571333250630-f0230c320b6d?w=900&q=85',
        'fs2'=> 'https://images.unsplash.com/photo-1559348349-86f1f65817fe?w=900&q=85',
        // VTT en action / trail
        'tr1'=> 'https://images.unsplash.com/photo-1511994298241-608e28f14fde?w=900&q=85',
        // Route (vélo de route classique)
        'r1' => 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=900&q=85',
        'r2' => 'https://images.unsplash.com/photo-1526307616774-60d0098f7642?w=900&q=85',
        'r3' => 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=900&q=85',
        // Gravel
        'g1' => 'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=900&q=85',
        'g2' => 'https://images.unsplash.com/photo-1512428813834-c702c7702b78?w=900&q=85',
        // Ville / urban
        'v1' => 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=900&q=85',
        'v2' => 'https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?w=900&q=85',
        // E-bike
        'e1' => 'https://images.unsplash.com/photo-1617788138017-80ad40651399?w=900&q=85',
        'e2' => 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=900&q=85',
        // BMX
        'b1' => 'https://images.unsplash.com/photo-1486427944299-d1955d23e34d?w=900&q=85',
        // Enfant
        'k1' => 'https://images.unsplash.com/photo-1503455637927-730bce8583c0?w=900&q=85',
        // Photo générique vélo studio
        's1' => 'https://images.unsplash.com/photo-1507035895480-2b3156c31fc8?w=900&q=85',
        's2' => 'https://images.unsplash.com/photo-1505705694340-019e1e335916?w=900&q=85',
    ];

    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        ProductImage::truncate();
        Product::truncate();
        Category::truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        // Catégories
        $cats = [
            ['name'=>'VTT',           'name_de'=>'Mountainbike',   'slug'=>'vtt',          'description'=>'Vélos tout-terrain','description_de'=>'Geländefahrräder'],
            ['name'=>'Route',         'name_de'=>'Rennrad',         'slug'=>'route',        'description'=>'Vélos de route',   'description_de'=>'Rennräder'],
            ['name'=>'Gravel',        'name_de'=>'Gravel',          'slug'=>'gravel',       'description'=>'Vélos gravel',     'description_de'=>'Gravel-Bikes'],
            ['name'=>'Ville',         'name_de'=>'Stadtrad',        'slug'=>'ville',        'description'=>'Vélos urbains',    'description_de'=>'Stadträder'],
            ['name'=>'Électrique',    'name_de'=>'E-Bike',          'slug'=>'electrique',   'description'=>'E-Bikes',          'description_de'=>'Elektrofahrräder'],
            ['name'=>'BMX',           'name_de'=>'BMX',             'slug'=>'bmx',          'description'=>'BMX',              'description_de'=>'BMX'],
            ['name'=>'Enfant',        'name_de'=>'Kinderrad',       'slug'=>'enfant',       'description'=>'Vélos enfant',     'description_de'=>'Kinderräder'],
            ['name'=>'Reconditionné', 'name_de'=>'Generalüberholt', 'slug'=>'reconditionne','description'=>'Vélos reconditionnés','description_de'=>'Generalüberholte Räder'],
        ];
        foreach ($cats as $c) Category::create($c);
        $cid = Category::pluck('id', 'slug');

        $add = function(array $d) use ($cid) {
            $imgs   = $d['imgs']   ?? [];
            $colors = $d['colors'] ?? [];
            $cat    = $d['cat'];
            unset($d['imgs'], $d['colors'], $d['cat']);
            if (Product::where('slug', $d['slug'])->exists()) return;
            $p = Product::create(array_merge([
                'category_id'  => $cid[$cat] ?? null,
                'sale_price'   => null, 'is_featured' => false,
                'is_new'       => false, 'assembly_required' => false,
                'stock'        => rand(3,25), 'year' => '2025',
                'is_active'    => true,
                'colors'       => implode(',', $colors),
            ], $d));
            foreach ($imgs as $i => [$url, $color]) {
                ProductImage::create([
                    'product_id' => $p->id, 'image_path' => $url,
                    'is_primary' => $i === 0, 'sort_order' => $i, 'color' => $color,
                ]);
            }
        };

        $I = self::I;

        // ════ VTT ════════════════════════════════════════════════
        $add(['cat'=>'vtt','brand'=>'Trek','name'=>'Trek Marlin 7 Gen 3 29" Hardtail','name_de'=>'Trek Marlin 7 Gen 3 29" Hardtail','slug'=>'trek-marlin-7-gen3-29','description'=>'VTT hardtail taillé pour débuter sur les sentiers. Fourche RockShox Judy 100mm, transmission Shimano Deore 2×10, cadre aluminium Alpha Platinum. Freins hydrauliques Shimano MT200.','description_de'=>'Hardtail-MTB für den Trailseinstieg. RockShox Judy 100mm Gabel, Shimano Deore 2×10, Alpha Platinum Aluminiumrahmen.','price'=>1299.00,'sale_price'=>999.00,'is_featured'=>true,'bike_type'=>'Hardtail VTT','wheel_size'=>'29"','frame_material'=>'Aluminium Alpha Platinum','number_of_speeds'=>'20 vitesses Shimano Deore','suspension_type'=>'RockShox Judy 100mm','brake_style'=>'Hydraulique Shimano MT200','weight'=>'14,2 kg','warranty_type'=>'Garantie Trek à vie cadre','colors'=>['Noir','Bleu','Rouge'],'imgs'=>[[$I['h1'],'Noir'],[$I['h2'],'Bleu'],[$I['h3'],'Rouge']],'sizes'=>'S,M,L,XL,XXL']);

        $add(['cat'=>'vtt','brand'=>'Trek','name'=>'Trek Roscoe 8 27.5"+ Fat Hardtail','name_de'=>'Trek Roscoe 8 27.5"+ Fat Hardtail','slug'=>'trek-roscoe-8-275plus','description'=>'VTT hardtail fat-tire avec pneus 27,5"+ pour une adhérence exceptionnelle. RockShox Judy 120mm, SRAM SX Eagle 12 vitesses, freins hydrauliques.','description_de'=>'Fat-Tire Hardtail mit 27,5"+ Reifen für außergewöhnlichen Grip. RockShox Judy 120mm, SRAM SX Eagle 12-Gang.','price'=>1499.00,'sale_price'=>1199.00,'bike_type'=>'Hardtail Fat Bike','wheel_size'=>'27.5"+','frame_material'=>'Aluminium Alpha Gold','number_of_speeds'=>'12 vitesses SRAM SX Eagle','suspension_type'=>'RockShox Judy 120mm','brake_style'=>'Hydraulique Shimano MT200','weight'=>'14,8 kg','warranty_type'=>'Garantie Trek à vie','colors'=>['Noir','Bleu'],'imgs'=>[[$I['h1'],'Noir'],[$I['h2'],'Bleu']],'sizes'=>'S,M,L,XL']);

        $add(['cat'=>'vtt','brand'=>'Trek','name'=>'Trek Slash 9.8 GX AXS 29" Enduro Carbone','name_de'=>'Trek Slash 9.8 GX AXS 29" Enduro Carbon','slug'=>'trek-slash-9-8-gx-axs-29','description'=>'VTT enduro carbone OCLV 600 avec 160mm de débattement. Groupe SRAM GX AXS électronique, Fox 36 Factory, freins SRAM Code RSC. Le trail extrême.','description_de'=>'Carbon-Enduro OCLV 600 mit 160mm Federweg. SRAM GX AXS elektronisch, Fox 36 Factory, SRAM Code RSC Bremsen.','price'=>5999.00,'sale_price'=>null,'is_new'=>true,'is_featured'=>true,'bike_type'=>'Enduro Carbone','wheel_size'=>'29"','frame_material'=>'Carbone OCLV 600','number_of_speeds'=>'12 vitesses SRAM GX AXS','suspension_type'=>'Fox 36 Factory 160mm / Fox Float X2 160mm','brake_style'=>'Hydraulique SRAM Code RSC 4 pistons','weight'=>'13,2 kg','warranty_type'=>'Garantie Trek à vie carbone','colors'=>['Noir','Gris'],'imgs'=>[[$I['fs1'],'Noir'],[$I['fs2'],'Gris']],'sizes'=>'S,M,L,XL']);

        $add(['cat'=>'vtt','brand'=>'Trek','name'=>'Trek Fuel EX 8 XT 29" Trail','name_de'=>'Trek Fuel EX 8 XT 29" Trail','slug'=>'trek-fuel-ex-8-xt-29','description'=>'Trail bike tout-suspendu 130mm avec groupe Shimano XT 12V et Fox 34 Float. Géométrie progressée pour le trail technique. Incontournable.','description_de'=>'130mm Fully-Trail-Bike mit Shimano XT 12-Gang und Fox 34 Float. Progressive Geometrie für technische Trails.','price'=>3499.00,'sale_price'=>2999.00,'bike_type'=>'Trail Tout-suspendu','wheel_size'=>'29"','frame_material'=>'Aluminium Alpha Platinum','number_of_speeds'=>'12 vitesses Shimano Deore XT','suspension_type'=>'Fox 34 Float 130mm / Fox Float DPS 130mm','brake_style'=>'Hydraulique Shimano XT 4 pistons','weight'=>'13,8 kg','warranty_type'=>'Garantie Trek à vie','colors'=>['Vert','Noir','Bleu'],'imgs'=>[[$I['fs1'],'Vert'],[$I['h1'],'Noir'],[$I['h2'],'Bleu']],'sizes'=>'S,M,L,XL']);

        $add(['cat'=>'vtt','brand'=>'Trek','name'=>'Trek Procaliber 9.7 29" XC Carbone','name_de'=>'Trek Procaliber 9.7 29" XC Carbon','slug'=>'trek-procaliber-9-7-xc-carbone','description'=>'VTT XC hardtail carbone OCLV 500 ultra-léger avec IsoSpeed. Fox 32 Float SC 100mm, Shimano Deore XT 12V. Le VTT des champions de cross-country.','description_de'=>'Ultra-leichtes XC Hardtail OCLV 500 Carbon mit IsoSpeed. Fox 32 Float SC 100mm, Shimano Deore XT 12-Gang.','price'=>4299.00,'sale_price'=>null,'is_new'=>true,'bike_type'=>'XC Hardtail Carbone','wheel_size'=>'29"','frame_material'=>'Carbone OCLV 500','number_of_speeds'=>'12 vitesses Shimano Deore XT','suspension_type'=>'Fox 32 Float SC 100mm','brake_style'=>'Disque hydraulique Shimano XT','weight'=>'10,2 kg','warranty_type'=>'Garantie Trek à vie carbone','colors'=>['Blanc','Noir'],'imgs'=>[[$I['tr1'],'Blanc'],[$I['h1'],'Noir']],'sizes'=>'XS,S,M,L,XL,XXL']);

        $add(['cat'=>'vtt','brand'=>'Specialized','name'=>'Specialized Stumpjumper Comp Alloy 29" Trail','name_de'=>'Specialized Stumpjumper Comp Alloy 29" Trail','slug'=>'specialized-stumpjumper-comp-alloy-29','description'=>'Trail bike tout-suspendu 140mm, Fox 36 Rhythm, SRAM SX Eagle 12V, freins SRAM G2 R. L\'excellence du trail à prix accessible. Géométrie S-Sizing.','description_de'=>'140mm Fully-Trail-Bike, Fox 36 Rhythm, SRAM SX Eagle 12-Gang, SRAM G2 R Bremsen. Trail-Exzellenz zum zugänglichen Preis.','price'=>3299.00,'sale_price'=>null,'is_featured'=>true,'is_new'=>true,'bike_type'=>'Trail Tout-suspendu','wheel_size'=>'29"','frame_material'=>'Aluminium M5','number_of_speeds'=>'12 vitesses SRAM SX Eagle','suspension_type'=>'Fox 36 Rhythm 140mm / Fox Float DPS 140mm','brake_style'=>'Hydraulique SRAM G2 R','weight'=>'13,8 kg','warranty_type'=>'Garantie Specialized 5 ans','colors'=>['Bleu','Vert','Noir'],'imgs'=>[[$I['h2'],'Bleu'],[$I['fs1'],'Vert'],[$I['h1'],'Noir']],'sizes'=>'S,M,L,XL']);

        $add(['cat'=>'vtt','brand'=>'Specialized','name'=>'Specialized Epic World Cup Pro Carbon 29" XC','name_de'=>'Specialized Epic World Cup Pro Carbon 29" XC','slug'=>'specialized-epic-world-cup-pro-29','description'=>'LE vélo de XC des champions du monde. Cadre FACT 12m ultra-léger, suspension Brain FSR 100mm auto-bloquant, groupe SRAM XX AXS électronique. Perfection absolue.','description_de'=>'DAS XC-Bike der Weltmeister. FACT 12m ultraleichter Rahmen, selbstsperrendes Brain FSR 100mm, SRAM XX AXS elektronische Gruppe.','price'=>8999.00,'sale_price'=>null,'is_featured'=>true,'is_new'=>true,'bike_type'=>'XC Race Carbone','wheel_size'=>'29"','frame_material'=>'Carbone FACT 12m','number_of_speeds'=>'12 vitesses SRAM XX AXS','suspension_type'=>'Brain FSR 100mm (auto-lock)','brake_style'=>'Hydraulique SRAM Level Ultimate','weight'=>'9,1 kg','warranty_type'=>'Garantie Specialized 5 ans cadre','colors'=>['Blanc','Noir'],'imgs'=>[[$I['tr1'],'Blanc'],[$I['h1'],'Noir']],'sizes'=>'S,M,L,XL']);

        $add(['cat'=>'vtt','brand'=>'Specialized','name'=>'Specialized Enduro Expert 29" 170mm','name_de'=>'Specialized Enduro Expert 29" 170mm','slug'=>'specialized-enduro-expert-29-170mm','description'=>'Enduro 170mm de débattement. Fox 38 Float 170mm, SRAM X01 Eagle, freins Code R 4 pistons. Pour les riders qui veulent tout donner en descente technique.','description_de'=>'170mm Enduro-Bike. Fox 38 Float 170mm, SRAM X01 Eagle, Code R 4-Kolben Bremsen. Für Fahrer, die auf technischen Abfahrten alles geben.','price'=>4499.00,'sale_price'=>3899.00,'is_featured'=>true,'bike_type'=>'Enduro','wheel_size'=>'29"','frame_material'=>'Aluminium M5','number_of_speeds'=>'12 vitesses SRAM X01 Eagle','suspension_type'=>'Fox 38 Float 170mm / Fox Float X2 170mm','brake_style'=>'Hydraulique SRAM Code R 4 pistons','weight'=>'14,6 kg','warranty_type'=>'Garantie Specialized 5 ans','colors'=>['Bleu','Noir'],'imgs'=>[[$I['h2'],'Bleu'],[$I['h1'],'Noir']],'sizes'=>'S,M,L,XL']);

        $add(['cat'=>'vtt','brand'=>'Specialized','name'=>'Specialized Fuse Sport 27.5" Trail','name_de'=>'Specialized Fuse Sport 27.5" Trail','slug'=>'specialized-fuse-sport-275','description'=>'VTT hardtail agressif pneus 2,6" et RockShox Judy Gold 140mm. Shimano Deore 10V, SRAM G2. Taillé pour le flow et le trail technique.','description_de'=>'Aggressives Hardtail mit 2,6" Reifen und RockShox Judy Gold 140mm. Shimano Deore 10-Gang, SRAM G2.','price'=>1299.00,'sale_price'=>null,'bike_type'=>'Hardtail Trail','wheel_size'=>'27.5"','frame_material'=>'Aluminium M4','number_of_speeds'=>'10 vitesses Shimano Deore','suspension_type'=>'RockShox Judy Gold 140mm','brake_style'=>'Hydraulique SRAM G2','weight'=>'13,5 kg','warranty_type'=>'Garantie Specialized 5 ans','colors'=>['Rouge','Noir'],'imgs'=>[[$I['h3'],'Rouge'],[$I['h1'],'Noir']],'sizes'=>'XS,S,M,L,XL']);

        $add(['cat'=>'vtt','brand'=>'Giant','name'=>'Giant Trance X Advanced Pro 29 1 Carbone','name_de'=>'Giant Trance X Advanced Pro 29 1 Carbon','slug'=>'giant-trance-x-advanced-pro-29','description'=>'Trail bike carbone 140mm. SRAM X01 Eagle, Fox 36 Float Factory, géométrie Maestro. Légèreté et précision pour les riders exigeants.','description_de'=>'140mm Carbon-Trail-Bike. SRAM X01 Eagle, Fox 36 Float Factory, Maestro-Geometrie. Leichtigkeit und Präzision.','price'=>5299.00,'sale_price'=>null,'is_new'=>true,'bike_type'=>'Trail Carbone','wheel_size'=>'29"','frame_material'=>'Carbone Advanced Grade Composite','number_of_speeds'=>'12 vitesses SRAM X01 Eagle','suspension_type'=>'Fox 36 Float Factory 140mm / Maestro 140mm','brake_style'=>'Hydraulique SRAM Code R','weight'=>'12,9 kg','warranty_type'=>'Garantie Giant 5 ans','colors'=>['Noir','Vert'],'imgs'=>[[$I['h1'],'Noir'],[$I['fs1'],'Vert']],'sizes'=>'S,M,L,XL']);

        $add(['cat'=>'vtt','brand'=>'Giant','name'=>'Giant Talon 1 29" 2025 Hardtail','name_de'=>'Giant Talon 1 29" 2025 Hardtail','slug'=>'giant-talon-1-29-2025','description'=>'Hardtail VTT avec cadre ALUXX et suspension SR Suntour XCT 100mm. Shimano 21V, freins à disque mécaniques. Parfait pour découvrir les sentiers.','description_de'=>'Hardtail-MTB mit ALUXX Rahmen und SR Suntour XCT 100mm Federung. Shimano 21-Gang, mechanische Scheibenbremsen.','price'=>899.00,'sale_price'=>749.00,'bike_type'=>'Hardtail VTT','wheel_size'=>'29"','frame_material'=>'Aluminium ALUXX','number_of_speeds'=>'21 vitesses Shimano Acera','suspension_type'=>'SR Suntour XCT 100mm','brake_style'=>'Disque mécanique Tektro','weight'=>'13,9 kg','warranty_type'=>'Garantie Giant 2 ans','colors'=>['Noir','Rouge','Bleu'],'imgs'=>[[$I['h1'],'Noir'],[$I['h3'],'Rouge'],[$I['h2'],'Bleu']],'sizes'=>'S,M,L,XL']);

        $add(['cat'=>'vtt','brand'=>'Giant','name'=>'Giant Reign Advanced Pro 29 0 Enduro Carbone','name_de'=>'Giant Reign Advanced Pro 29 0 Enduro Carbon','slug'=>'giant-reign-advanced-pro-29-0','description'=>'Enduro carbone haut de gamme 160mm. SRAM XX1 Eagle, Fox 38 Float Factory, Shimano XTR. Le summum de la marque taïwanaise pour le terrain extrême.','description_de'=>'Premium 160mm Carbon-Enduro. SRAM XX1 Eagle, Fox 38 Float Factory, Shimano XTR. Das Beste der taiwanesischen Marke.','price'=>7499.00,'sale_price'=>null,'is_featured'=>true,'is_new'=>true,'bike_type'=>'Enduro Carbone','wheel_size'=>'29"','frame_material'=>'Carbone Advanced Grade','number_of_speeds'=>'12 vitesses SRAM XX1 Eagle','suspension_type'=>'Fox 38 Float Factory 160mm / Fox Float X2 160mm','brake_style'=>'Hydraulique Shimano XTR','weight'=>'12,6 kg','warranty_type'=>'Garantie Giant 5 ans','colors'=>['Noir','Bleu'],'imgs'=>[[$I['h1'],'Noir'],[$I['h2'],'Bleu']],'sizes'=>'S,M,L,XL']);

        $add(['cat'=>'vtt','brand'=>'Santa Cruz','name'=>'Santa Cruz Hightower CC X01 AXS 29" Trail','name_de'=>'Santa Cruz Hightower CC X01 AXS 29" Trail','slug'=>'santa-cruz-hightower-cc-x01-axs','description'=>'Trail bike carbone haute modélisation 135mm. SRAM X01 AXS électronique, Fox 36 Factory, SRAM Code RSC. La référence américaine du trail.','description_de'=>'Hochmodularer Carbon-Trail-Bike 135mm. Elektronische SRAM X01 AXS, Fox 36 Factory, SRAM Code RSC.','price'=>7499.00,'sale_price'=>null,'is_featured'=>true,'is_new'=>true,'bike_type'=>'Trail Carbone','wheel_size'=>'29"','frame_material'=>'Carbone CC haute modélisation','number_of_speeds'=>'12 vitesses SRAM X01 AXS','suspension_type'=>'Fox 36 Factory 140mm / Fox Float DPS 135mm','brake_style'=>'Hydraulique SRAM Code RSC','weight'=>'12,4 kg','warranty_type'=>'Garantie Santa Cruz à vie','colors'=>['Bleu','Noir'],'imgs'=>[[$I['h2'],'Bleu'],[$I['h1'],'Noir']],'sizes'=>'S,M,L,XL']);

        $add(['cat'=>'vtt','brand'=>'Santa Cruz','name'=>'Santa Cruz Bronson S Carbon 29" Enduro','name_de'=>'Santa Cruz Bronson S Carbon 29" Enduro','slug'=>'santa-cruz-bronson-s-carbon-29','description'=>'Enduro carbone C 150mm avec Shimano XT 12V et RockShox Pike. Pour les riders qui aiment dévaler les pentes avec style et puissance.','description_de'=>'C-Carbon-Enduro 150mm mit Shimano XT 12-Gang und RockShox Pike. Für Fahrer, die Hänge mit Stil bezwingen.','price'=>5499.00,'sale_price'=>4899.00,'bike_type'=>'Enduro Carbone','wheel_size'=>'29"','frame_material'=>'Carbone C (moyen module)','number_of_speeds'=>'12 vitesses Shimano Deore XT','suspension_type'=>'RockShox Pike 150mm / Super Deluxe','brake_style'=>'Hydraulique Shimano XT 4 pistons','weight'=>'13,8 kg','warranty_type'=>'Garantie Santa Cruz à vie','colors'=>['Vert','Bleu','Noir'],'imgs'=>[[$I['fs1'],'Vert'],[$I['h2'],'Bleu'],[$I['h1'],'Noir']],'sizes'=>'S,M,L,XL']);

        $add(['cat'=>'vtt','brand'=>'Santa Cruz','name'=>'Santa Cruz Chameleon 7 D 29" Hardtail','name_de'=>'Santa Cruz Chameleon 7 D 29" Hardtail','slug'=>'santa-cruz-chameleon-7-d-29','description'=>'Hardtail aluminium polyvalent avec SRAM SX Eagle 12V et RockShox Recon 130mm. Géométrie progressive pour un pilotage précis.','description_de'=>'Vielseitiges Aluminium-Hardtail mit SRAM SX Eagle 12-Gang und RockShox Recon 130mm.','price'=>1499.00,'sale_price'=>null,'bike_type'=>'Hardtail VTT','wheel_size'=>'29"','frame_material'=>'Aluminium D (Double Butted)','number_of_speeds'=>'12 vitesses SRAM SX Eagle','suspension_type'=>'RockShox Recon 130mm','brake_style'=>'Hydraulique SRAM G2 R','weight'=>'13,1 kg','warranty_type'=>'Garantie Santa Cruz à vie','colors'=>['Rouge','Noir','Jaune'],'imgs'=>[[$I['h3'],'Rouge'],[$I['h1'],'Noir'],[$I['tr1'],'Jaune']],'sizes'=>'S,M,L,XL']);

        $add(['cat'=>'vtt','brand'=>'YT Industries','name'=>'YT Jeffsy Core 4 29" Trail 2025','name_de'=>'YT Jeffsy Core 4 29" Trail 2025','slug'=>'yt-jeffsy-core-4-29-2025','description'=>'Trail bike allemand 140mm géométrie longue et basse. Fox 36 Rhythm, SRAM SX Eagle, SRAM G2 R. Aggressif et polyvalent pour le trail moderne.','description_de'=>'Deutsches 140mm Trail-Bike mit langer, niedriger Geometrie. Fox 36 Rhythm, SRAM SX Eagle, SRAM G2 R.','price'=>3299.00,'sale_price'=>null,'is_new'=>true,'bike_type'=>'Trail Tout-suspendu','wheel_size'=>'29"','frame_material'=>'Aluminium 6061','number_of_speeds'=>'12 vitesses SRAM SX Eagle','suspension_type'=>'Fox 36 Rhythm 140mm / Fox Float DPS 140mm','brake_style'=>'Hydraulique SRAM G2 R','weight'=>'14,2 kg','warranty_type'=>'Garantie YT 2 ans','colors'=>['Noir','Blanc'],'imgs'=>[[$I['h1'],'Noir'],[$I['tr1'],'Blanc']],'sizes'=>'S,M,L,XL']);

        $add(['cat'=>'vtt','brand'=>'YT Industries','name'=>'YT Capra Core 3 29" Enduro 170mm','name_de'=>'YT Capra Core 3 29" Enduro 170mm','slug'=>'yt-capra-core-3-29-enduro','description'=>'Enduro 170mm avec Fox 38 Float. SRAM GX Eagle, freins SRAM Code R. Pour les pentes les plus raides et les terrains les plus techniques.','description_de'=>'170mm Enduro mit Fox 38 Float. SRAM GX Eagle, SRAM Code R Bremsen. Für steilste Hänge und technischstes Gelände.','price'=>3799.00,'sale_price'=>null,'bike_type'=>'Enduro','wheel_size'=>'29"','frame_material'=>'Aluminium 6061','number_of_speeds'=>'12 vitesses SRAM GX Eagle','suspension_type'=>'Fox 38 Float 170mm / Fox Float X2 170mm','brake_style'=>'Hydraulique SRAM Code R','weight'=>'15,0 kg','warranty_type'=>'Garantie YT 2 ans','colors'=>['Noir','Vert'],'imgs'=>[[$I['h1'],'Noir'],[$I['fs1'],'Vert']],'sizes'=>'S,M,L,XL']);

        $add(['cat'=>'vtt','brand'=>'Orbea','name'=>'Orbea Occam M30 29" Trail 2025','name_de'=>'Orbea Occam M30 29" Trail 2025','slug'=>'orbea-occam-m30-29-2025','description'=>'Trail bike espagnol 130mm géométrie MyGeometry ajustable. Shimano Deore 12V, RockShox Recon, freins 4 pistons. Polyvalence espagnole.','description_de'=>'Spanisches 130mm Trail-Bike mit einstellbarer MyGeometry. Shimano Deore 12-Gang, RockShox Recon.','price'=>2899.00,'sale_price'=>null,'bike_type'=>'Trail Tout-suspendu','wheel_size'=>'29"','frame_material'=>'Aluminium 6061 T6','number_of_speeds'=>'12 vitesses Shimano Deore','suspension_type'=>'RockShox Recon 130mm / RockShox Deluxe Select+','brake_style'=>'Hydraulique Shimano Deore 4 pistons','weight'=>'14,0 kg','warranty_type'=>'Garantie Orbea 5 ans','colors'=>['Bleu','Noir','Rouge'],'imgs'=>[[$I['h2'],'Bleu'],[$I['h1'],'Noir'],[$I['h3'],'Rouge']],'sizes'=>'XS,S,M,L,XL']);

        $add(['cat'=>'vtt','brand'=>'Orbea','name'=>'Orbea Rallon M20 29" Enduro 170mm','name_de'=>'Orbea Rallon M20 29" Enduro 170mm','slug'=>'orbea-rallon-m20-29-enduro','description'=>'Enduro 170mm Fox 38 Rhythm, Shimano Deore XT, freins XT 4 pistons. Pour les riders qui veulent compétitionner sur les terrains les plus extrêmes.','description_de'=>'170mm Enduro Fox 38 Rhythm, Shimano Deore XT, XT 4-Kolben Bremsen.','price'=>3499.00,'sale_price'=>2999.00,'bike_type'=>'Enduro','wheel_size'=>'29"','frame_material'=>'Aluminium 6061','number_of_speeds'=>'12 vitesses Shimano Deore XT','suspension_type'=>'Fox 38 Rhythm 170mm / Fox Float X2 170mm','brake_style'=>'Hydraulique Shimano XT 4 pistons','weight'=>'15,1 kg','warranty_type'=>'Garantie Orbea 5 ans','colors'=>['Rouge','Noir'],'imgs'=>[[$I['h3'],'Rouge'],[$I['h1'],'Noir']],'sizes'=>'S,M,L,XL']);

        $add(['cat'=>'vtt','brand'=>'Merida','name'=>'Merida Big.Nine 400 29" XC Hardtail','name_de'=>'Merida Big.Nine 400 29" XC Hardtail','slug'=>'merida-big-nine-400-29','description'=>'VTT XC hardtail aluminium Lite ultra-léger. RockShox 30 Silver 100mm, Shimano Deore 2×10. La légèreté pour le cross-country.','description_de'=>'Ultraleichtes XC Hardtail Aluminium Lite. RockShox 30 Silver 100mm, Shimano Deore 2×10.','price'=>1199.00,'sale_price'=>999.00,'bike_type'=>'XC Hardtail','wheel_size'=>'29"','frame_material'=>'Aluminium Lite (Merida)','number_of_speeds'=>'20 vitesses Shimano Deore','suspension_type'=>'RockShox 30 Silver 100mm','brake_style'=>'Hydraulique Shimano MT200','weight'=>'12,8 kg','warranty_type'=>'Garantie Merida 5 ans','colors'=>['Noir','Bleu'],'imgs'=>[[$I['h1'],'Noir'],[$I['h2'],'Bleu']],'sizes'=>'XS,S,M,L,XL,XXL']);

        $add(['cat'=>'vtt','brand'=>'Merida','name'=>'Merida One-Sixty 800 29" Enduro 160mm','name_de'=>'Merida One-Sixty 800 29" Enduro 160mm','slug'=>'merida-one-sixty-800-29','description'=>'Enduro 160mm haut de gamme avec RockShox Lyrik et Shimano Deore XT 12V. La marque taïwanaise à son meilleur niveau pour la compétition.','description_de'=>'Premium 160mm Enduro mit RockShox Lyrik und Shimano Deore XT 12-Gang.','price'=>3299.00,'sale_price'=>null,'is_new'=>true,'bike_type'=>'Enduro','wheel_size'=>'29"','frame_material'=>'Aluminium 6061','number_of_speeds'=>'12 vitesses Shimano Deore XT','suspension_type'=>'RockShox Lyrik 160mm / Super Deluxe 160mm','brake_style'=>'Hydraulique Shimano XT 4 pistons','weight'=>'14,9 kg','warranty_type'=>'Garantie Merida 5 ans','colors'=>['Gris','Noir'],'imgs'=>[[$I['h3'],'Gris'],[$I['h1'],'Noir']],'sizes'=>'S,M,L,XL']);

        $add(['cat'=>'vtt','brand'=>'Cube','name'=>'Cube Aim Pro 27.5" Hardtail','name_de'=>'Cube Aim Pro 27.5" Hardtail','slug'=>'cube-aim-pro-275-hardtail','description'=>'VTT hardtail entrée de gamme avec SR Suntour XCR 100mm, Shimano Acera 3×8. Solide et fiable pour les débutants sur les sentiers.','description_de'=>'Einstiegs-Hardtail mit SR Suntour XCR 100mm, Shimano Acera 3×8.','price'=>799.00,'sale_price'=>null,'bike_type'=>'Hardtail VTT','wheel_size'=>'27.5"','frame_material'=>'Aluminium 6061','number_of_speeds'=>'24 vitesses Shimano Acera','suspension_type'=>'SR Suntour XCR 100mm','brake_style'=>'Disque hydraulique Shimano','weight'=>'13,6 kg','warranty_type'=>'Garantie Cube 2 ans','colors'=>['Vert','Noir','Gris'],'imgs'=>[[$I['fs1'],'Vert'],[$I['h1'],'Noir'],[$I['h3'],'Gris']],'sizes'=>'XS,S,M,L,XL']);

        $add(['cat'=>'vtt','brand'=>'Cube','name'=>'Cube Stereo 140 HPC SLT 29" Carbone','name_de'=>'Cube Stereo 140 HPC SLT 29" Carbon','slug'=>'cube-stereo-140-hpc-slt-29','description'=>'Trail bike carbone HPC SLT haut de gamme 140mm. SRAM X01 AXS électronique, Fox 36 Float Factory. Le meilleur de Cube pour le trail.','description_de'=>'Premium Carbon HPC SLT Trail-Bike 140mm. SRAM X01 AXS elektronisch, Fox 36 Float Factory.','price'=>5299.00,'sale_price'=>null,'is_featured'=>true,'bike_type'=>'Trail Carbone','wheel_size'=>'29"','frame_material'=>'Carbone HPC SLT','number_of_speeds'=>'12 vitesses SRAM X01 AXS','suspension_type'=>'Fox 36 Float Factory 140mm / Fox Float DPS Factory','brake_style'=>'Hydraulique SRAM Code RSC','weight'=>'12,2 kg','warranty_type'=>'Garantie Cube 2 ans','colors'=>['Noir','Blanc'],'imgs'=>[[$I['h1'],'Noir'],[$I['tr1'],'Blanc']],'sizes'=>'S,M,L,XL']);

        $add(['cat'=>'vtt','brand'=>'Cannondale','name'=>'Cannondale Habit 4 29" Trail 130mm','name_de'=>'Cannondale Habit 4 29" Trail 130mm','slug'=>'cannondale-habit-4-29-trail','description'=>'Trail bike 130mm géométrie Progressive Sizing, SRAM SX Eagle 12V, RockShox Recon. Cannondale Proportional Response pour un grip optimal.','description_de'=>'130mm Trail-Bike mit Progressive Sizing Geometrie, SRAM SX Eagle 12-Gang, RockShox Recon.','price'=>2799.00,'sale_price'=>null,'is_new'=>true,'bike_type'=>'Trail Tout-suspendu','wheel_size'=>'29"','frame_material'=>'Aluminium SmartForm C2','number_of_speeds'=>'12 vitesses SRAM SX Eagle','suspension_type'=>'RockShox Recon 130mm / Fox Float','brake_style'=>'Hydraulique Shimano MT420','weight'=>'14,1 kg','warranty_type'=>'Garantie Cannondale à vie','colors'=>['Vert','Noir'],'imgs'=>[[$I['fs1'],'Vert'],[$I['h1'],'Noir']],'sizes'=>'S,M,L,XL']);

        $add(['cat'=>'vtt','brand'=>'Cannondale','name'=>'Cannondale Jekyll 1 29" Enduro 165mm Carbone','name_de'=>'Cannondale Jekyll 1 29" Enduro 165mm Carbon','slug'=>'cannondale-jekyll-1-29-enduro','description'=>'Enduro carbone 165mm avec Öhlins RXF 36 et Shimano Deore XT. Technologie Proportional Response unique et suspension Öhlins premium.','description_de'=>'165mm Carbon-Enduro mit Öhlins RXF 36 und Shimano Deore XT. Einzigartige Proportional Response Technologie.','price'=>6499.00,'sale_price'=>null,'is_featured'=>true,'is_new'=>true,'bike_type'=>'Enduro Carbone','wheel_size'=>'29"','frame_material'=>'Carbone BallisTec','number_of_speeds'=>'12 vitesses Shimano Deore XT','suspension_type'=>'Öhlins RXF 36 165mm / Öhlins TTX22M 165mm','brake_style'=>'Hydraulique Shimano XT 4 pistons','weight'=>'13,0 kg','warranty_type'=>'Garantie Cannondale à vie','colors'=>['Vert','Noir'],'imgs'=>[[$I['fs1'],'Vert'],[$I['h1'],'Noir']],'sizes'=>'S,M,L,XL']);

        $add(['cat'=>'vtt','brand'=>'Norco','name'=>'Norco Sight A2 29" Trail 140mm','name_de'=>'Norco Sight A2 29" Trail 140mm','slug'=>'norco-sight-a2-29-trail','description'=>'Trail bike canadien 140mm Fox 36 Rhythm, SRAM GX Eagle. Géométrie progressive pour s\'adapter à tous les terrains.','description_de'=>'Kanadisches 140mm Trail-Bike Fox 36 Rhythm, SRAM GX Eagle.','price'=>2999.00,'sale_price'=>null,'bike_type'=>'Trail Tout-suspendu','wheel_size'=>'29"','frame_material'=>'Aluminium A6061','number_of_speeds'=>'12 vitesses SRAM GX Eagle','suspension_type'=>'Fox 36 Rhythm 140mm / Fox Float DPS','brake_style'=>'Hydraulique SRAM G2 R','weight'=>'14,3 kg','warranty_type'=>'Garantie Norco à vie','colors'=>['Vert','Noir'],'imgs'=>[[$I['fs1'],'Vert'],[$I['h1'],'Noir']],'sizes'=>'XS,S,M,L,XL']);

        $add(['cat'=>'vtt','brand'=>'Scott','name'=>'Scott Genius 940 29" TwinLoc Trail','name_de'=>'Scott Genius 940 29" TwinLoc Trail','slug'=>'scott-genius-940-29-twinloc','description'=>'Trail bike unique avec système TwinLoc pour basculer entre Trail, Traction et Lock. Shimano Deore 12V, RockShox Recon 130mm.','description_de'=>'Einzigartiges Trail-Bike mit TwinLoc System für Wechsel zwischen Trail, Traktion und Sperre.','price'=>2499.00,'sale_price'=>2099.00,'bike_type'=>'Trail Tout-suspendu','wheel_size'=>'29"','frame_material'=>'Aluminium 6061','number_of_speeds'=>'12 vitesses Shimano Deore','suspension_type'=>'RockShox Recon 130mm / Scott TwinLoc 130mm','brake_style'=>'Hydraulique Shimano MT420','weight'=>'14,5 kg','warranty_type'=>'Garantie Scott 2 ans','colors'=>['Bleu','Noir'],'imgs'=>[[$I['h2'],'Bleu'],[$I['h1'],'Noir']],'sizes'=>'S,M,L,XL']);

        $add(['cat'=>'vtt','brand'=>'Scott','name'=>'Scott Scale 940 29" XC Hardtail','name_de'=>'Scott Scale 940 29" XC Hardtail','slug'=>'scott-scale-940-29-xc','description'=>'VTT XC hardtail aluminium ultra-léger Triple Butted. Shimano Deore 2×10, RockShox Judy Silver 100mm. Légèreté maximale pour le cross-country.','description_de'=>'Ultraleichtes XC Hardtail Aluminium Triple Butted. Shimano Deore 2×10, RockShox Judy Silver 100mm.','price'=>1099.00,'sale_price'=>899.00,'bike_type'=>'XC Hardtail','wheel_size'=>'29"','frame_material'=>'Aluminium 6061 Triple Butted','number_of_speeds'=>'20 vitesses Shimano Deore','suspension_type'=>'RockShox Judy Silver 100mm','brake_style'=>'Hydraulique Shimano MT200','weight'=>'12,9 kg','warranty_type'=>'Garantie Scott 2 ans','colors'=>['Blanc','Noir'],'imgs'=>[[$I['tr1'],'Blanc'],[$I['h1'],'Noir']],'sizes'=>'XS,S,M,L,XL,XXL']);

        $add(['cat'=>'vtt','brand'=>'Pivot','name'=>'Pivot Mach 4 SL Team XTR 29" XC Race','name_de'=>'Pivot Mach 4 SL Team XTR 29" XC Race','slug'=>'pivot-mach-4-sl-team-xtr-29','description'=>'VTT XC carbone UD utilisé par les équipes pro. Shimano XTR groupe complet, Fox 34 Float Factory 100mm. La compétition au plus haut niveau.','description_de'=>'Von Profi-Teams eingesetztes XC Carbon UD Bike. Shimano XTR Komplettgruppe, Fox 34 Float Factory 100mm.','price'=>9999.00,'sale_price'=>null,'is_featured'=>true,'is_new'=>true,'bike_type'=>'XC Race Carbone','wheel_size'=>'29"','frame_material'=>'Carbone UD','number_of_speeds'=>'12 vitesses Shimano XTR','suspension_type'=>'Fox 34 Float Factory 100mm / Fox Float DPS Factory','brake_style'=>'Hydraulique Shimano XTR','weight'=>'8,9 kg','warranty_type'=>'Garantie Pivot à vie','colors'=>['Blanc','Bleu'],'imgs'=>[[$I['tr1'],'Blanc'],[$I['h2'],'Bleu']],'sizes'=>'XS,S,M,L,XL']);

        $add(['cat'=>'vtt','brand'=>'Propain','name'=>'Propain Spindrift CF 29" Enduro 160mm Carbone','name_de'=>'Propain Spindrift CF 29" Enduro 160mm Carbon','slug'=>'propain-spindrift-cf-29-enduro','description'=>'Enduro carbone CF 160mm allemand avec Shimano Deore XT 12V et Fox 38 Rhythm. Rapport qualité-prix exceptionnel de la marque bavaroise.','description_de'=>'Deutsches 160mm Carbon CF Enduro mit Shimano Deore XT 12-Gang und Fox 38 Rhythm.','price'=>3999.00,'sale_price'=>null,'is_new'=>true,'bike_type'=>'Enduro Carbone','wheel_size'=>'29"','frame_material'=>'Carbone CF','number_of_speeds'=>'12 vitesses Shimano Deore XT','suspension_type'=>'Fox 38 Rhythm 160mm / Fox Float X2 160mm','brake_style'=>'Hydraulique Shimano XT 4 pistons','weight'=>'13,5 kg','warranty_type'=>'Garantie Propain 3 ans','colors'=>['Noir','Vert'],'imgs'=>[[$I['h1'],'Noir'],[$I['fs1'],'Vert']],'sizes'=>'S,M,L,XL']);

        $add(['cat'=>'vtt','brand'=>'Kona','name'=>'Kona Process 134 DL 29" Trail','name_de'=>'Kona Process 134 DL 29" Trail','slug'=>'kona-process-134-dl-29','description'=>'Trail bike canadien 134mm, SRAM GX Eagle, RockShox Pike. Kona IDS System pour ajuster la géométrie. Style et performance à l\'américaine.','description_de'=>'Kanadisches 134mm Trail-Bike, SRAM GX Eagle, RockShox Pike. Kona IDS System für Geometrie-Anpassung.','price'=>2499.00,'sale_price'=>null,'bike_type'=>'Trail Tout-suspendu','wheel_size'=>'29"','frame_material'=>'Aluminium 6061','number_of_speeds'=>'12 vitesses SRAM GX Eagle','suspension_type'=>'RockShox Pike 130mm / RockShox Deluxe Select+','brake_style'=>'Hydraulique SRAM G2 R','weight'=>'14,0 kg','warranty_type'=>'Garantie Kona à vie','colors'=>['Orange','Noir'],'imgs'=>[[$I['fs2'],'Orange'],[$I['h1'],'Noir']],'sizes'=>'S,M,L,XL']);

        // ════ ROUTE ═══════════════════════════════════════════════
        $add(['cat'=>'route','brand'=>'Trek','name'=>'Trek Émonda SL 5 Disc Carbone Shimano 105 Di2','name_de'=>'Trek Émonda SL 5 Disc Carbon Shimano 105 Di2','slug'=>'trek-emonda-sl5-disc-carbone','description'=>'Vélo de route carbone OCLV 500 ultra-léger avec Shimano 105 Di2 électronique et freins à disque. Le grimpeur parfait pour les cols alpins.','description_de'=>'Ultra-leichtes OCLV 500 Carbon-Rennrad mit Shimano 105 Di2 elektronisch und Scheibenbremsen. Der perfekte Kletterer.','price'=>4299.00,'sale_price'=>3499.00,'is_featured'=>true,'bike_type'=>'Route Carbone Grimpeur','wheel_size'=>'700c','frame_material'=>'Carbone OCLV 500','number_of_speeds'=>'22 vitesses Shimano 105 Di2','suspension_type'=>'Rigide','brake_style'=>'Disque hydraulique Shimano 105','weight'=>'7,9 kg','warranty_type'=>'Garantie Trek à vie carbone','colors'=>['Blanc','Noir','Rouge'],'imgs'=>[[$I['r1'],'Blanc'],[$I['r2'],'Noir'],[$I['r3'],'Rouge']],'sizes'=>'47,50,52,54,56,58,60,62']);

        $add(['cat'=>'route','brand'=>'Trek','name'=>'Trek Domane SL 6 Gen 4 Disc Endurance','name_de'=>'Trek Domane SL 6 Gen 4 Disc Endurance','slug'=>'trek-domane-sl6-gen4-disc','description'=>'Vélo d\'endurance carbone OCLV 500 avec IsoSpeed découplé avant/arrière. Shimano 105 Di2. Confort sur le long, performance toujours.','description_de'=>'Carbon-Endurance OCLV 500 mit IsoSpeed vorne/hinten. Shimano 105 Di2. Langstreckenkomfort mit Leistung.','price'=>5299.00,'sale_price'=>null,'is_new'=>true,'bike_type'=>'Route Endurance Carbone','wheel_size'=>'700c','frame_material'=>'Carbone OCLV 500','number_of_speeds'=>'22 vitesses Shimano 105 Di2','suspension_type'=>'IsoSpeed découplé avant/arrière','brake_style'=>'Disque hydraulique Shimano 105','weight'=>'8,4 kg','warranty_type'=>'Garantie Trek à vie','colors'=>['Bleu','Noir'],'imgs'=>[[$I['r2'],'Bleu'],[$I['r1'],'Noir']],'sizes'=>'47,50,52,54,56,58,60,62']);

        $add(['cat'=>'route','brand'=>'Trek','name'=>'Trek Madone SL 6 Gen 7 AXS Aero Carbone','name_de'=>'Trek Madone SL 6 Gen 7 AXS Aero Carbon','slug'=>'trek-madone-sl6-gen7-axs','description'=>'Vélo aéro carbone OCLV 700 avec IsoFlow et SRAM Force AXS électronique. Le vélo des champions du World Tour. Vitesse absolue.','description_de'=>'Aero-Carbon OCLV 700 mit IsoFlow und SRAM Force AXS elektronisch. Das Bike der World Tour Champions.','price'=>8499.00,'sale_price'=>null,'is_featured'=>true,'is_new'=>true,'bike_type'=>'Route Aero Carbone','wheel_size'=>'700c','frame_material'=>'Carbone OCLV 700','number_of_speeds'=>'12 vitesses SRAM Force AXS','suspension_type'=>'IsoFlow','brake_style'=>'Disque hydraulique SRAM Force','weight'=>'7,2 kg','warranty_type'=>'Garantie Trek à vie','colors'=>['Noir','Blanc','Rouge'],'imgs'=>[[$I['r1'],'Noir'],[$I['r2'],'Blanc'],[$I['r3'],'Rouge']],'sizes'=>'47,50,52,54,56,58,60,62']);

        $add(['cat'=>'route','brand'=>'Specialized','name'=>'Specialized Tarmac SL7 Expert Ultegra Di2','name_de'=>'Specialized Tarmac SL7 Expert Ultegra Di2','slug'=>'specialized-tarmac-sl7-expert-ultegra','description'=>'Vélo de route aéro carbone FACT 10r avec Shimano Ultegra Di2. Performances de compétition accessibles. Le vélo qui gagne des classiques.','description_de'=>'Aero-Carbon-Rennrad FACT 10r mit Shimano Ultegra Di2. Wettkampfleistung für alle.','price'=>5499.00,'sale_price'=>null,'is_featured'=>true,'is_new'=>true,'bike_type'=>'Route Aero Carbone','wheel_size'=>'700c','frame_material'=>'Carbone FACT 10r','number_of_speeds'=>'22 vitesses Shimano Ultegra Di2','suspension_type'=>'Rigide','brake_style'=>'Disque hydraulique Shimano Ultegra','weight'=>'7,1 kg','warranty_type'=>'Garantie Specialized 5 ans','colors'=>['Noir','Blanc','Bleu'],'imgs'=>[[$I['r1'],'Noir'],[$I['r2'],'Blanc'],[$I['r3'],'Bleu']],'sizes'=>'44,49,52,54,56,58,61']);

        $add(['cat'=>'route','brand'=>'Specialized','name'=>'Specialized Allez Sprint Comp Disc Aluminium','name_de'=>'Specialized Allez Sprint Comp Disc Aluminium','slug'=>'specialized-allez-sprint-comp-disc','description'=>'Vélo de route aluminium E5 Premium avec géométrie aéro et Shimano 105 12V. La performance aéro à prix accessible. Freins disque hydrauliques.','description_de'=>'Aero-Aluminium-Rennrad E5 Premium mit Shimano 105 12-Gang. Aerodynamische Leistung zum günstigen Preis.','price'=>1799.00,'sale_price'=>1499.00,'bike_type'=>'Route Aero Aluminium','wheel_size'=>'700c','frame_material'=>'Aluminium E5 Premium','number_of_speeds'=>'22 vitesses Shimano 105','suspension_type'=>'Rigide','brake_style'=>'Disque hydraulique Shimano 105','weight'=>'9,2 kg','warranty_type'=>'Garantie Specialized 5 ans','colors'=>['Noir','Blanc'],'imgs'=>[[$I['r1'],'Noir'],[$I['r2'],'Blanc']],'sizes'=>'44,49,52,54,56,58,61']);

        $add(['cat'=>'route','brand'=>'Giant','name'=>'Giant TCR Advanced Pro 1 Disc Carbone','name_de'=>'Giant TCR Advanced Pro 1 Disc Carbon','slug'=>'giant-tcr-advanced-pro-1-disc','description'=>'Vélo de route carbone Advanced Grade avec Shimano Ultegra Di2 électronique. Géométrie agressive pour les courses et les performances.','description_de'=>'Advanced Grade Carbon-Rennrad mit Shimano Ultegra Di2 elektronisch. Aggressive Geometrie für Rennen.','price'=>3999.00,'sale_price'=>null,'is_new'=>true,'bike_type'=>'Route Carbone','wheel_size'=>'700c','frame_material'=>'Carbone Advanced Grade','number_of_speeds'=>'22 vitesses Shimano Ultegra Di2','suspension_type'=>'Rigide','brake_style'=>'Disque hydraulique Shimano Ultegra','weight'=>'7,5 kg','warranty_type'=>'Garantie Giant 5 ans','colors'=>['Noir','Blanc','Rouge'],'imgs'=>[[$I['r1'],'Noir'],[$I['r2'],'Blanc'],[$I['r3'],'Rouge']],'sizes'=>'XXS,XS,S,M,ML,L,XL']);

        $add(['cat'=>'route','brand'=>'Cannondale','name'=>'Cannondale CAAD13 Disc 105 Aluminium Premium','name_de'=>'Cannondale CAAD13 Disc 105 Aluminium Premium','slug'=>'cannondale-caad13-disc-105','description'=>'Le meilleur vélo de route aluminium. SmartForm C1 Premium Alloy avec Shimano 105 12V. Légèreté quasi-carbone à prix accessible.','description_de'=>'Das beste Aluminium-Rennrad. SmartForm C1 Premium Alloy mit Shimano 105 12-Gang. Carbon-Leichtigkeit zum günstigen Preis.','price'=>1899.00,'sale_price'=>null,'is_new'=>true,'bike_type'=>'Route Aluminium','wheel_size'=>'700c','frame_material'=>'Aluminium SmartForm C1 Premium','number_of_speeds'=>'22 vitesses Shimano 105','suspension_type'=>'Rigide','brake_style'=>'Disque hydraulique Shimano 105','weight'=>'8,6 kg','warranty_type'=>'Garantie Cannondale à vie','colors'=>['Blanc','Noir','Gris'],'imgs'=>[[$I['r2'],'Blanc'],[$I['r1'],'Noir'],[$I['r3'],'Gris']],'sizes'=>'44,48,51,54,56,58,61']);

        $add(['cat'=>'route','brand'=>'Colnago','name'=>'Colnago C68 Disc Shimano Dura-Ace Di2 Prestige','name_de'=>'Colnago C68 Disc Shimano Dura-Ace Di2 Prestige','slug'=>'colnago-c68-disc-dura-ace-di2','description'=>'Le summum de l\'artisanat italien. Cadre carbone T800/T1000 fait à la main à Cambiago, Shimano Dura-Ace Di2. Le rêve ultime du cycliste.','description_de'=>'Gipfel italienischer Handwerkskunst. Handgefertigter T800/T1000 Carbon in Cambiago, Shimano Dura-Ace Di2.','price'=>12999.00,'sale_price'=>null,'is_featured'=>true,'is_new'=>true,'bike_type'=>'Route Prestige Carbone','wheel_size'=>'700c','frame_material'=>'Carbone T800/T1000 (fait main en Italie)','number_of_speeds'=>'22 vitesses Shimano Dura-Ace Di2','suspension_type'=>'Rigide','brake_style'=>'Disque hydraulique Shimano Dura-Ace','weight'=>'6,8 kg','warranty_type'=>'Garantie Colnago à vie','colors'=>['Blanc','Rouge','Noir'],'imgs'=>[[$I['r2'],'Blanc'],[$I['r3'],'Rouge'],[$I['r1'],'Noir']],'sizes'=>'45,48,50,52,54,56,58']);

        $add(['cat'=>'route','brand'=>'Pinarello','name'=>'Pinarello Dogma F Shimano Dura-Ace Di2','name_de'=>'Pinarello Dogma F Shimano Dura-Ace Di2','slug'=>'pinarello-dogma-f-dura-ace-di2','description'=>'Le vélo du Tour de France. Carbone TorayCA T1100, géométrie ONDA asymétrique, Dura-Ace Di2. L\'outil des champions pendant 10 ans consécutifs.','description_de'=>'Das Fahrrad der Tour de France. TorayCA T1100 Carbon, asymmetrische ONDA Geometrie, Dura-Ace Di2.','price'=>14999.00,'sale_price'=>null,'is_featured'=>true,'is_new'=>true,'bike_type'=>'Route Pro Carbone','wheel_size'=>'700c','frame_material'=>'Carbone TorayCA T1100 1K','number_of_speeds'=>'22 vitesses Shimano Dura-Ace Di2','suspension_type'=>'Rigide ONDA','brake_style'=>'Disque hydraulique Shimano Dura-Ace','weight'=>'6,5 kg','warranty_type'=>'Garantie Pinarello 5 ans','colors'=>['Noir','Blanc'],'imgs'=>[[$I['r1'],'Noir'],[$I['r2'],'Blanc']],'sizes'=>'44,46,50,51.5,53,54,55,56,57.5,59,62']);

        $add(['cat'=>'route','brand'=>'Bianchi','name'=>'Bianchi Oltre RC Dura-Ace Di2 Celeste Iconic','name_de'=>'Bianchi Oltre RC Dura-Ace Di2 Celeste Iconic','slug'=>'bianchi-oltre-rc-dura-ace-di2','description'=>'Le vaisseau amiral Bianchi avec la légendaire couleur Celeste. Carbone CounterVail, Dura-Ace Di2. L\'élégance italienne au sommet de la performance.','description_de'=>'Bianchis Flaggschiff mit legendärer Celeste Farbe. CounterVail Carbon, Dura-Ace Di2. Italienische Eleganz auf höchstem Leistungsniveau.','price'=>11999.00,'sale_price'=>null,'is_featured'=>true,'bike_type'=>'Route Aero Prestige','wheel_size'=>'700c','frame_material'=>'Carbone CV CounterVail','number_of_speeds'=>'22 vitesses Shimano Dura-Ace Di2','suspension_type'=>'Rigide','brake_style'=>'Disque hydraulique Shimano Dura-Ace','weight'=>'6,9 kg','warranty_type'=>'Garantie Bianchi à vie','colors'=>['Celeste','Noir'],'imgs'=>[[$I['r2'],'Celeste'],[$I['r1'],'Noir']],'sizes'=>'44,47,50,53,55,57,59']);

        $add(['cat'=>'route','brand'=>'BMC','name'=>'BMC Teammachine SLR 01 Shimano Dura-Ace Di2','name_de'=>'BMC Teammachine SLR 01 Shimano Dura-Ace Di2','slug'=>'bmc-teammachine-slr-01-dura-ace','description'=>'Le vélo suisse de référence. Carbone ACE (Advanced Composite Engineering), Dura-Ace Di2. La précision suisse au service de la vitesse.','description_de'=>'Das Schweizer Referenz-Rennrad. ACE Carbon (Advanced Composite Engineering), Dura-Ace Di2.','price'=>13499.00,'sale_price'=>null,'is_featured'=>true,'bike_type'=>'Route Pro Carbone','wheel_size'=>'700c','frame_material'=>'Carbone ACE','number_of_speeds'=>'22 vitesses Shimano Dura-Ace Di2','suspension_type'=>'Rigide','brake_style'=>'Disque hydraulique Shimano Dura-Ace','weight'=>'6,7 kg','warranty_type'=>'Garantie BMC 5 ans','colors'=>['Rouge','Blanc'],'imgs'=>[[$I['r3'],'Rouge'],[$I['r2'],'Blanc']],'sizes'=>'44,47,49,51,53,55,57,61']);

        $add(['cat'=>'route','brand'=>'Cervélo','name'=>'Cervélo R5 Shimano Ultegra Di2 Grimpeur','name_de'=>'Cervélo R5 Shimano Ultegra Di2 Bergfahrer','slug'=>'cervelo-r5-ultegra-di2-grimpeur','description'=>'Vélo grimpeur carbone HM ultra-léger avec Shimano Ultegra Di2. Le choix des spécialistes de l\'ascension. Chaque gramme compte.','description_de'=>'Ultraleichtes HM Carbon-Kletterrad mit Shimano Ultegra Di2. Die Wahl der Bergspezialisten.','price'=>7499.00,'sale_price'=>null,'is_new'=>true,'bike_type'=>'Route Grimpeur Carbone','wheel_size'=>'700c','frame_material'=>'Carbone HM','number_of_speeds'=>'22 vitesses Shimano Ultegra Di2','suspension_type'=>'Rigide','brake_style'=>'Disque hydraulique Shimano Ultegra','weight'=>'6,9 kg','warranty_type'=>'Garantie Cervélo 5 ans','colors'=>['Noir','Blanc','Bleu'],'imgs'=>[[$I['r1'],'Noir'],[$I['r2'],'Blanc'],[$I['r3'],'Bleu']],'sizes'=>'44,48,51,54,56,58,61']);

        $add(['cat'=>'route','brand'=>'Look','name'=>'Look 795 Blade RS Disc Shimano Ultegra Di2','name_de'=>'Look 795 Blade RS Disc Shimano Ultegra Di2','slug'=>'look-795-blade-rs-disc-ultegra','description'=>'Vélo aéro français avant-gardiste. Carbone HM UD, Shimano Ultegra Di2. L\'élégance française au service de l\'aérodynamisme.','description_de'=>'Avantgardistisches französisches Aero-Bike. HM UD Carbon, Shimano Ultegra Di2.','price'=>8499.00,'sale_price'=>null,'is_featured'=>true,'bike_type'=>'Route Aero Carbone','wheel_size'=>'700c','frame_material'=>'Carbone HM UD','number_of_speeds'=>'22 vitesses Shimano Ultegra Di2','suspension_type'=>'Rigide','brake_style'=>'Disque hydraulique Shimano Ultegra','weight'=>'7,2 kg','warranty_type'=>'Garantie Look 5 ans','colors'=>['Noir','Blanc'],'imgs'=>[[$I['r1'],'Noir'],[$I['r2'],'Blanc']],'sizes'=>'44,47,49,52,54,56,58']);

        $add(['cat'=>'route','brand'=>'Ridley','name'=>'Ridley Helium SLX Disc 105 Di2 Belge','name_de'=>'Ridley Helium SLX Disc 105 Di2 Belgisch','slug'=>'ridley-helium-slx-disc-105-di2','description'=>'Vélo belge ultra-léger carbone HM UD avec Shimano 105 Di2. Conçu pour les grimpeurs. La légèreté belge au service des cols.','description_de'=>'Belgisches Ultraleicht Carbon HM UD Rennrad mit Shimano 105 Di2. Für Kletterer auf Bergpässen.','price'=>4499.00,'sale_price'=>3999.00,'bike_type'=>'Route Grimpeur','wheel_size'=>'700c','frame_material'=>'Carbone HM UD','number_of_speeds'=>'22 vitesses Shimano 105 Di2','suspension_type'=>'Rigide','brake_style'=>'Disque hydraulique Shimano 105','weight'=>'7,0 kg','warranty_type'=>'Garantie Ridley 5 ans','colors'=>['Noir','Vert'],'imgs'=>[[$I['r1'],'Noir'],[$I['r2'],'Vert']],'sizes'=>'XS,S,M,L,XL']);

        // ════ GRAVEL ══════════════════════════════════════════════
        $add(['cat'=>'gravel','brand'=>'Trek','name'=>'Trek Checkpoint ALR 5 Gravel GRX 600','name_de'=>'Trek Checkpoint ALR 5 Gravel GRX 600','slug'=>'trek-checkpoint-alr5-gravel-grx','description'=>'Gravel bike aluminium IsoSpeed, Shimano GRX 600, freins hydrauliques. Polyvalent route et chemins. L\'aventure commence ici.','description_de'=>'Gravel-Bike Aluminium IsoSpeed, Shimano GRX 600, hydraulische Bremsen. Vielseitig auf Straße und Wegen.','price'=>1999.00,'sale_price'=>null,'is_new'=>true,'bike_type'=>'Gravel Aventure','wheel_size'=>'700c','frame_material'=>'Aluminium Alpha Platinum IsoSpeed','number_of_speeds'=>'20 vitesses Shimano GRX 600','suspension_type'=>'Rigide IsoSpeed','brake_style'=>'Disque hydraulique Shimano GRX','weight'=>'9,4 kg','warranty_type'=>'Garantie Trek à vie','colors'=>['Gris','Noir','Vert'],'imgs'=>[[$I['g1'],'Gris'],[$I['g2'],'Noir'],[$I['s1'],'Vert']],'sizes'=>'47,50,52,54,56,58,61']);

        $add(['cat'=>'gravel','brand'=>'Trek','name'=>'Trek Checkpoint SL 6 Carbone GRX Di2','name_de'=>'Trek Checkpoint SL 6 Carbon GRX Di2','slug'=>'trek-checkpoint-sl6-carbone-grx','description'=>'Gravel bike carbone OCLV 500 haut de gamme avec IsoSpeed et Shimano GRX Di2 électronique. L\'aventure sans compromis.','description_de'=>'Premium Carbon OCLV 500 Gravel-Bike mit IsoSpeed und Shimano GRX Di2 elektronisch.','price'=>3999.00,'sale_price'=>null,'is_featured'=>true,'bike_type'=>'Gravel Carbone','wheel_size'=>'700c','frame_material'=>'Carbone OCLV 500','number_of_speeds'=>'22 vitesses Shimano GRX Di2','suspension_type'=>'IsoSpeed carbone','brake_style'=>'Disque hydraulique Shimano GRX','weight'=>'8,5 kg','warranty_type'=>'Garantie Trek à vie','colors'=>['Noir','Blanc'],'imgs'=>[[$I['g1'],'Noir'],[$I['g2'],'Blanc']],'sizes'=>'47,50,52,54,56,58,61']);

        $add(['cat'=>'gravel','brand'=>'Specialized','name'=>'Specialized Diverge Comp Carbone GRX Di2','name_de'=>'Specialized Diverge Comp Carbon GRX Di2','slug'=>'specialized-diverge-comp-carbon-grx','description'=>'Gravel carbone FACT 9r avec Future Shock 2.0 et Shimano GRX Di2. Confort maximal pour les longues aventures hors bitume.','description_de'=>'Carbon FACT 9r Gravel mit Future Shock 2.0 und Shimano GRX Di2. Maximaler Komfort für lange Schotter-Abenteuer.','price'=>3799.00,'sale_price'=>3199.00,'is_featured'=>true,'bike_type'=>'Gravel Endurance Carbone','wheel_size'=>'700c','frame_material'=>'Carbone FACT 9r','number_of_speeds'=>'22 vitesses Shimano GRX Di2','suspension_type'=>'Future Shock 2.0 (30mm)','brake_style'=>'Disque hydraulique Shimano GRX','weight'=>'8,7 kg','warranty_type'=>'Garantie Specialized 5 ans','colors'=>['Sable','Bleu','Noir'],'imgs'=>[[$I['g1'],'Sable'],[$I['g2'],'Bleu'],[$I['s1'],'Noir']],'sizes'=>'44,49,52,54,56,58,61']);

        $add(['cat'=>'gravel','brand'=>'Giant','name'=>'Giant Revolt Advanced Pro 0 SRAM Force AXS','name_de'=>'Giant Revolt Advanced Pro 0 SRAM Force AXS','slug'=>'giant-revolt-advanced-pro-0-axs','description'=>'Gravel carbone Advanced Grade avec D-Fuse et SRAM Force AXS électronique. Pour les longues aventures sans compromis sur la performance.','description_de'=>'Advanced Grade Carbon Gravel mit D-Fuse und SRAM Force AXS elektronisch. Für lange Abenteuer.','price'=>4299.00,'sale_price'=>null,'is_new'=>true,'bike_type'=>'Gravel Carbone','wheel_size'=>'700c','frame_material'=>'Carbone Advanced Grade','number_of_speeds'=>'12 vitesses SRAM Force AXS','suspension_type'=>'D-Fuse carbone','brake_style'=>'Disque hydraulique SRAM Force','weight'=>'8,3 kg','warranty_type'=>'Garantie Giant 5 ans','colors'=>['Noir','Vert'],'imgs'=>[[$I['g1'],'Noir'],[$I['g2'],'Vert']],'sizes'=>'XXS,XS,S,M,ML,L,XL']);

        $add(['cat'=>'gravel','brand'=>'Cannondale','name'=>'Cannondale Topstone Carbon GRX 600 KingPin','name_de'=>'Cannondale Topstone Carbon GRX 600 KingPin','slug'=>'cannondale-topstone-carbon-grx-600','description'=>'Gravel carbone BallisTec avec suspension KingPin 30mm et Shimano GRX 600. Confort et agilité pour le gravel racing.','description_de'=>'BallisTec Carbon Gravel mit KingPin 30mm Federung und Shimano GRX 600. Komfort und Agilität.','price'=>3299.00,'sale_price'=>null,'bike_type'=>'Gravel Aventure','wheel_size'=>'700c','frame_material'=>'Carbone BallisTec','number_of_speeds'=>'22 vitesses Shimano GRX 600','suspension_type'=>'KingPin 30mm (arrière)','brake_style'=>'Disque hydraulique Shimano GRX','weight'=>'9,0 kg','warranty_type'=>'Garantie Cannondale à vie','colors'=>['Vert','Gris'],'imgs'=>[[$I['g2'],'Vert'],[$I['g1'],'Gris']],'sizes'=>'XS,S,M,L,XL,XXL']);

        foreach([
            ['Trek','Trek Checkpoint ALR 4 GRX Aluminium','trek-checkpoint-alr4-grx-alu','Gravel aluminium accessible avec GRX et IsoSpeed. L\'aventure au meilleur rapport qualité-prix.',1499.00,null,'g1','g2'],
            ['Salsa','Salsa Warbird Carbon GRX 600 Race','salsa-warbird-carbon-grx-600','Gravel carbone américain pour les longues distances et gravel races. Confort et performance.',3799.00,3299.00,'g1','g2'],
            ['Orbea','Orbea Terra M30 GRX Aluminium','orbea-terra-m30-grx-alu','Gravel aluminium espagnol avec GRX 1x. Géométrie aventure pour explorer sans limites.',1699.00,null,'g2','g1'],
            ['Scott','Scott Addict Gravel 20 HMF Carbone','scott-addict-gravel-20-hmf','Gravel carbone HMF léger avec GRX 600. Légèreté et polyvalence pour tous les terrains.',3499.00,null,'g1','g2'],
            ['Cube','Cube Nuroad Race GRX Disc Aluminium','cube-nuroad-race-grx-disc','Gravel aluminium Superlite avec GRX 600. Performance et endurance pour le gravel allemand.',1199.00,999.00,'g2','g1'],
        ] as [$brand,$name,$slug,$desc,$price,$sale,$i1,$i2]) {
            $add(['cat'=>'gravel','brand'=>$brand,'name'=>$name,'name_de'=>$name,'slug'=>$slug,'description'=>$desc,'description_de'=>$desc,'price'=>$price,'sale_price'=>$sale,'bike_type'=>'Gravel','wheel_size'=>'700c','frame_material'=>'Aluminium/Carbone','number_of_speeds'=>'22 vitesses Shimano GRX','suspension_type'=>'Rigide','brake_style'=>'Disque hydraulique','weight'=>'9,5 kg','warranty_type'=>'Garantie 2-5 ans','colors'=>['Noir','Vert'],'imgs'=>[[$I[$i1],'Noir'],[$I[$i2],'Vert']],'sizes'=>'XS,S,M,L,XL']);
        }

        // ════ VILLE ═══════════════════════════════════════════════
        $add(['cat'=>'ville','brand'=>'Trek','name'=>'Trek FX 3 Disc Fitness Ville','name_de'=>'Trek FX 3 Disc Fitness Stadtrad','slug'=>'trek-fx3-disc-fitness-ville','description'=>'Vélo de ville polyvalent avec fourche carbone et Shimano Acera 24V. Freins disque hydrauliques. Parfait pour la ville et les sorties sport.','description_de'=>'Vielseitiges Stadtrad mit Carbon-Gabel und Shimano Acera 24-Gang. Hydraulische Scheibenbremsen.','price'=>899.00,'sale_price'=>null,'is_featured'=>true,'bike_type'=>'Fitness/Ville','wheel_size'=>'700c','frame_material'=>'Aluminium Alpha Gold','number_of_speeds'=>'24 vitesses Shimano Acera','suspension_type'=>'Fourche rigide carbone','brake_style'=>'Disque hydraulique Shimano','weight'=>'10,8 kg','warranty_type'=>'Garantie Trek à vie','colors'=>['Gris','Noir','Bleu'],'imgs'=>[[$I['v1'],'Gris'],[$I['v2'],'Noir'],[$I['g1'],'Bleu']],'sizes'=>'XS,S,M,L,XL,XXL']);

        $add(['cat'=>'ville','brand'=>'Trek','name'=>'Trek Verve 2 Disc Confort Quotidien','name_de'=>'Trek Verve 2 Disc Komfort Alltag','slug'=>'trek-verve-2-disc-confort','description'=>'Vélo de ville confortable position droite. Shimano 21V, freins disque mécaniques. Idéal pour les déplacements quotidiens en toute sécurité.','description_de'=>'Komfortables Stadtrad mit aufrechter Position. Shimano 21-Gang, mechanische Scheibenbremsen.','price'=>749.00,'sale_price'=>649.00,'bike_type'=>'Ville Confort','wheel_size'=>'700c','frame_material'=>'Aluminium Alpha Silver','number_of_speeds'=>'21 vitesses Shimano','suspension_type'=>'Fourche rigide','brake_style'=>'Disque mécanique Tektro','weight'=>'12,4 kg','warranty_type'=>'Garantie Trek à vie','colors'=>['Noir','Blanc','Bleu'],'imgs'=>[[$I['v1'],'Noir'],[$I['v2'],'Blanc'],[$I['g1'],'Bleu']],'sizes'=>'XS,S,M,L,XL,XXL']);

        $add(['cat'=>'ville','brand'=>'Giant','name'=>'Giant Escape 2 Disc Commuter Rapide','name_de'=>'Giant Escape 2 Disc Pendler Schnell','slug'=>'giant-escape-2-disc-commuter','description'=>'Vélo commuter rapide avec freins hydrauliques Tektro et Shimano Claris 16V. Position sportive pour un pédalage efficace au quotidien.','description_de'=>'Schnelles Pendlerrad mit Tektro hydraulischen Bremsen und Shimano Claris 16-Gang.','price'=>749.00,'sale_price'=>649.00,'bike_type'=>'Ville/Commuter','wheel_size'=>'700c','frame_material'=>'Aluminium ALUXX','number_of_speeds'=>'16 vitesses Shimano Claris','suspension_type'=>'Rigide','brake_style'=>'Disque hydraulique Tektro','weight'=>'11,2 kg','warranty_type'=>'Garantie Giant 2 ans','colors'=>['Noir','Gris','Bleu'],'imgs'=>[[$I['v1'],'Noir'],[$I['v2'],'Gris'],[$I['g2'],'Bleu']],'sizes'=>'XS,S,M,L,XL,XXL']);

        $add(['cat'=>'ville','brand'=>'Cube','name'=>'Cube Hyde Race Commuter Shimano Deore','name_de'=>'Cube Hyde Race Pendler Shimano Deore','slug'=>'cube-hyde-race-commuter-deore','description'=>'Commuter performant Shimano Deore 10V et freins hydrauliques. Cadre aluminium léger pour distancer les embouteillages avec style.','description_de'=>'Leistungsstarkes Pendlerrad Shimano Deore 10-Gang und hydraulische Bremsen.','price'=>999.00,'sale_price'=>null,'is_new'=>true,'bike_type'=>'Ville/Commuter','wheel_size'=>'700c','frame_material'=>'Aluminium 6061','number_of_speeds'=>'10 vitesses Shimano Deore','suspension_type'=>'Rigide','brake_style'=>'Disque hydraulique Shimano','weight'=>'10,4 kg','warranty_type'=>'Garantie Cube 2 ans','colors'=>['Noir','Gris','Vert'],'imgs'=>[[$I['v1'],'Noir'],[$I['v2'],'Gris'],[$I['g1'],'Vert']],'sizes'=>'XS,S,M,L,XL']);

        foreach([
            ['Gazelle','Gazelle Esprit C7 HMS Hollandais','gazelle-esprit-c7-hollandais','Vélo hollandais 7V Nexus et rétropédalage. Design intemporel pour les déplacements quotidiens.',849.00,null,'v1','v2'],
            ['Batavus','Batavus Dinsdag 8D Pure Ego Hollandais','batavus-dinsdag-8d-ego','Vélo hollandais 8V Nexus internes. Entretien minimal, style maximal. L\'ère du vélo pratique.',1099.00,null,'v2','v1'],
            ['Peugeot','Peugeot LC01 7 Allure Ville Élégant','peugeot-lc01-7-allure-ville','Vélo de ville élégant 7V Altus. Le style français pour vos trajets quotidiens.',699.00,599.00,'v1','v2'],
            ['Specialized','Specialized Sirrus 3.0 Disc Fitness','specialized-sirrus-3-disc-fitness','Vélo fitness disque hydraulique Shimano Deore 10V. Efficace et confortable pour la ville.',899.00,null,'v1','v2'],
            ['Scott','Scott Sub Cross 50 EQ Ville Équipé','scott-sub-cross-50-eq-ville','Vélo de ville entièrement équipé (garde-boues, porte-bagages). Shimano 21V pour tous les usages.',749.00,649.00,'v2','v1'],
        ] as [$brand,$name,$slug,$desc,$price,$sale,$i1,$i2]) {
            $add(['cat'=>'ville','brand'=>$brand,'name'=>$name,'name_de'=>$name,'slug'=>$slug,'description'=>$desc,'description_de'=>$desc,'price'=>$price,'sale_price'=>$sale,'bike_type'=>'Ville','wheel_size'=>'700c','frame_material'=>'Aluminium','number_of_speeds'=>'7-11 vitesses','suspension_type'=>'Rigide','brake_style'=>'Hydraulique/Mécanique','weight'=>'12 kg','warranty_type'=>'Garantie 2 ans','colors'=>['Noir','Gris'],'imgs'=>[[$I[$i1],'Noir'],[$I[$i2],'Gris']],'sizes'=>'XS,S,M,L,XL']);
        }

        // ════ ÉLECTRIQUE ═══════════════════════════════════════════
        $add(['cat'=>'electrique','brand'=>'Trek','name'=>'Trek Powerfly FS 9 Equipped E-MTB Bosch CX','name_de'=>'Trek Powerfly FS 9 Equipped E-MTB Bosch CX','slug'=>'trek-powerfly-fs9-equipped-emtb','description'=>'VTT électrique tout-suspendu 140mm Bosch Performance CX 85Nm, batterie 625Wh intégrée. Fox 36 Rhythm, Shimano Deore XT 12V. 100km d\'autonomie en mode Eco.','description_de'=>'Fully E-MTB 140mm Bosch Performance CX 85Nm, 625Wh integrierter Akku. Fox 36 Rhythm, Shimano Deore XT 12-Gang. 100km Reichweite.','price'=>6499.00,'sale_price'=>5799.00,'is_featured'=>true,'is_new'=>true,'bike_type'=>'E-MTB Tout-suspendu','wheel_size'=>'29"','frame_material'=>'Aluminium Alpha Platinum','number_of_speeds'=>'12 vitesses Shimano Deore XT','suspension_type'=>'Fox 36 Rhythm 140mm / Fox Float DPS 140mm','brake_style'=>'Hydraulique Shimano Deore XT 4 pistons','power_source'=>'Batterie lithium-ion intégrée','motor_power'=>'Bosch Performance CX 250W / 85Nm','battery_capacity'=>'625 Wh','max_speed'=>'25 km/h (assistance électrique)','max_range'=>'100 km mode Eco','charging_time'=>'4h30 (charge complète)','weight'=>'24,5 kg','warranty_type'=>'Garantie Trek 2 ans + Bosch 2 ans batterie','colors'=>['Noir','Bleu','Anthracite'],'imgs'=>[[$I['e1'],'Noir'],[$I['e2'],'Bleu'],[$I['fs1'],'Anthracite']],'sizes'=>'S,M,L,XL']);

        $add(['cat'=>'electrique','brand'=>'Trek','name'=>'Trek Verve+ 3 Lowstep E-Bike Urbain Équipé','name_de'=>'Trek Verve+ 3 Lowstep E-Bike Urban Ausgestattet','slug'=>'trek-verve-plus-3-lowstep-urbain','description'=>'E-Bike step-through Bosch Active Line Plus 50Nm, batterie 500Wh. Garde-boues, porte-bagages, béquille et éclairage intégrés. Prêt pour la ville dès la sortie du magasin.','description_de'=>'Step-Through E-Bike Bosch Active Line Plus 50Nm, 500Wh Akku. Schutzbleche, Gepäckträger, Ständer und integrierte Beleuchtung. Sofort einsatzbereit.','price'=>2799.00,'sale_price'=>2399.00,'bike_type'=>'E-Bike Urbain Step-Through','wheel_size'=>'700c','frame_material'=>'Aluminium Alpha','number_of_speeds'=>'9 vitesses Shimano Alivio','suspension_type'=>'Fourche rigide carbone','brake_style'=>'Disque hydraulique Shimano MT200','power_source'=>'Batterie lithium-ion amovible','motor_power'=>'Bosch Active Line Plus 250W / 50Nm','battery_capacity'=>'500 Wh','max_speed'=>'25 km/h','max_range'=>'90 km mode Eco','charging_time'=>'4h','weight'=>'23,6 kg','warranty_type'=>'Garantie Trek 2 ans + Bosch 2 ans','included_components'=>'Garde-boues, porte-bagages, béquille, éclairage intégré','colors'=>['Gris','Noir','Blanc'],'imgs'=>[[$I['e1'],'Gris'],[$I['v1'],'Noir'],[$I['e2'],'Blanc']],'sizes'=>'XS,S,M,L,XL']);

        $add(['cat'=>'electrique','brand'=>'Specialized','name'=>'Specialized Turbo Levo SL Comp Carbone 17,5kg','name_de'=>'Specialized Turbo Levo SL Comp Carbon 17,5kg','slug'=>'specialized-turbo-levo-sl-comp-carbone','description'=>'E-MTB carbone FACT 11m ultra-léger 17,5kg. Moteur SL 1.1 240W 35Nm, batterie 320Wh + Range Extender 160Wh. Sensations VTT pure avec assistance discrète.','description_de'=>'Carbon FACT 11m Ultraleicht E-MTB 17,5kg. SL 1.1 Motor 240W 35Nm, 320Wh Akku + 160Wh Range Extender. Pures MTB-Gefühl.','price'=>8999.00,'sale_price'=>null,'is_featured'=>true,'is_new'=>true,'bike_type'=>'E-MTB Léger Carbone','wheel_size'=>'29"','frame_material'=>'Carbone FACT 11m','number_of_speeds'=>'12 vitesses SRAM GX Eagle','suspension_type'=>'Fox 34 Float 130mm / Fox Float DPS 130mm','brake_style'=>'Hydraulique SRAM G2 R','power_source'=>'Batterie intégrée + Range Extender','motor_power'=>'Specialized SL 1.1 240W / 35Nm','battery_capacity'=>'320 Wh (+ Range Extender 160 Wh = 480 Wh)','max_speed'=>'25 km/h','max_range'=>'130 km avec Range Extender','charging_time'=>'2h30','weight'=>'17,5 kg','warranty_type'=>'Garantie Specialized 5 ans','special_features'=>"• Moteur SL ultra-léger (-40% vs concurrents)\n• Range Extender compatible +160Wh\n• Application Mission Control (personnalisation)\n• Batterie invisible dans le cadre",'colors'=>['Vert','Noir','Blanc'],'imgs'=>[[$I['e2'],'Vert'],[$I['e1'],'Noir'],[$I['fs1'],'Blanc']],'sizes'=>'S,M,L,XL']);

        $add(['cat'=>'electrique','brand'=>'Giant','name'=>'Giant Explore E+ 2 Pro E-Trekking SyncDrive','name_de'=>'Giant Explore E+ 2 Pro E-Trekking SyncDrive','slug'=>'giant-explore-e-plus-2-pro-trekking','description'=>'E-Bike trekking SyncDrive Pro2 80Nm, batterie EnergyPak 500Wh. Fourche télescopique 63mm, Shimano Deore 11V. Le compagnon idéal des randonnées.','description_de'=>'E-Trekking SyncDrive Pro2 80Nm, EnergyPak 500Wh Akku. 63mm Teleskopgabel, Shimano Deore 11-Gang.','price'=>3299.00,'sale_price'=>2899.00,'bike_type'=>'E-Trekking','wheel_size'=>'700c','frame_material'=>'Aluminium ALUXX','number_of_speeds'=>'11 vitesses Shimano Deore','suspension_type'=>'Fourche télescopique 63mm','brake_style'=>'Disque hydraulique Shimano Deore','power_source'=>'Batterie EnergyPak intégrée','motor_power'=>'Giant SyncDrive Pro2 250W / 80Nm','battery_capacity'=>'500 Wh','max_speed'=>'25 km/h','max_range'=>'100 km mode Eco','charging_time'=>'4h','weight'=>'22,3 kg','warranty_type'=>'Garantie Giant 2 ans + 2 ans batterie','colors'=>['Noir','Gris','Bleu'],'imgs'=>[[$I['e1'],'Noir'],[$I['e2'],'Gris'],[$I['v1'],'Bleu']],'sizes'=>'XS,S,M,L,XL']);

        $add(['cat'=>'electrique','brand'=>'Cube','name'=>'Cube Stereo Hybrid 140 HPC Race 750 Carbone','name_de'=>'Cube Stereo Hybrid 140 HPC Race 750 Carbon','slug'=>'cube-stereo-hybrid-140-hpc-750','description'=>'VTT électrique tout-suspendu carbone HPC, batterie 750Wh Bosch Performance CX Smart System. Fox 36 Float 140mm. L\'autonomie absolue pour les trails lointains.','description_de'=>'Carbon HPC Fully E-MTB, 750Wh Bosch Performance CX Smart System Akku. Fox 36 Float 140mm.','price'=>5999.00,'sale_price'=>null,'is_featured'=>true,'bike_type'=>'E-MTB Carbone','wheel_size'=>'29"','frame_material'=>'Carbone HPC','number_of_speeds'=>'12 vitesses Shimano Deore XT','suspension_type'=>'Fox 36 Float 140mm / Fox Float X2 140mm','brake_style'=>'Hydraulique Shimano XT 4 pistons','power_source'=>'Batterie lithium-ion Smart System','motor_power'=>'Bosch Performance CX Smart System 85Nm','battery_capacity'=>'750 Wh','max_speed'=>'25 km/h','max_range'=>'120 km mode Eco','charging_time'=>'5h','weight'=>'25,8 kg','warranty_type'=>'Garantie Cube 2 ans + Bosch 2 ans','colors'=>['Noir','Gris'],'imgs'=>[[$I['e1'],'Noir'],[$I['e2'],'Gris']],'sizes'=>'S,M,L,XL']);

        $add(['cat'=>'electrique','brand'=>'Riese & Müller','name'=>'R&M Supercharger GT Rohloff Double Batterie 1125Wh','name_de'=>'R&M Supercharger GT Rohloff Doppelakku 1125Wh','slug'=>'riese-muller-supercharger-gt-rohloff-1125wh','description'=>'Le roi des e-bikes longue distance. Double batterie 1125Wh, transmission Rohloff 14V électronique. Bosch Performance CX. Jusqu\'à 200km d\'autonomie. L\'ultime voyageur.','description_de'=>'Der König der Langstrecken-E-Bikes. Doppelakku 1125Wh, Rohloff 14-Gang elektronisch. Bosch Performance CX. Bis 200km Reichweite.','price'=>8499.00,'sale_price'=>null,'is_featured'=>true,'is_new'=>true,'bike_type'=>'E-Trekking Longue Distance','wheel_size'=>'29"','frame_material'=>'Aluminium premium R&M','number_of_speeds'=>'14 vitesses Rohloff E-14 (électronique)','suspension_type'=>'Fourche suspendue 63mm','brake_style'=>'Disque hydraulique Magura MT5e','power_source'=>'Double batterie lithium-ion intégrée','motor_power'=>'Bosch Performance CX 250W / 85Nm','battery_capacity'=>'1125 Wh (2 × 562,5 Wh)','max_speed'=>'25 km/h','max_range'=>'200+ km mode Eco','charging_time'=>'6h (charge complète)','weight'=>'33,5 kg','warranty_type'=>'Garantie R&M 2 ans + Bosch 2 ans batterie','colors'=>['Noir','Gris','Bleu'],'imgs'=>[[$I['e1'],'Noir'],[$I['e2'],'Gris'],[$I['v2'],'Bleu']],'sizes'=>'43,49,54']);

        $add(['cat'=>'electrique','brand'=>'Stromer','name'=>'Stromer ST5 Sport 45km/h Speed Pedelec Premium','name_de'=>'Stromer ST5 Sport 45km/h Speed-Pedelec Premium','slug'=>'stromer-st5-sport-45kmh-speed-pedelec','description'=>'Speed pedelec suisse 45km/h. Moteur SYNO Drive II 250W/48Nm, batterie 983Wh. SRAM Red eTap AXS, Magura MT5e. Application myStromer connectée. Ultra-premium.','description_de'=>'Schweizer 45km/h Speed-Pedelec. SYNO Drive II 250W/48Nm, 983Wh Akku. SRAM Red eTap AXS, Magura MT5e. myStromer App vernetzt.','price'=>7999.00,'sale_price'=>null,'is_featured'=>true,'is_new'=>true,'bike_type'=>'Speed Pedelec 45 km/h','wheel_size'=>'27.5"','frame_material'=>'Aluminium Stromer','number_of_speeds'=>'12 vitesses SRAM Red eTap AXS','suspension_type'=>'Rigide','brake_style'=>'Disque hydraulique Magura MT5e','power_source'=>'Batterie intégrée','motor_power'=>'Stromer SYNO Drive II 250W / 48Nm','battery_capacity'=>'983 Wh','max_speed'=>'45 km/h (assistance)','max_range'=>'150 km mode Eco','charging_time'=>'4h30','weight'=>'26,5 kg','warranty_type'=>'Garantie Stromer 2 ans','colors'=>['Noir','Blanc'],'imgs'=>[[$I['e1'],'Noir'],[$I['e2'],'Blanc']],'sizes'=>'42,48,54']);

        $add(['cat'=>'electrique','brand'=>'Haibike','name'=>'Haibike AllMtn 6 29" E-MTB Yamaha PW-X3','name_de'=>'Haibike AllMtn 6 29" E-MTB Yamaha PW-X3','slug'=>'haibike-allmtn-6-29-yamaha-pwx3','description'=>'VTT électrique tout-suspendu marque pionnière des e-MTB. Yamaha PW-X3 250W/85Nm, batterie 630Wh. Fox 36 Rhythm 150mm, Shimano Deore XT 12V.','description_de'=>'Fully E-MTB von der E-MTB Pioniermarke. Yamaha PW-X3 250W/85Nm, 630Wh Akku. Fox 36 Rhythm 150mm, Shimano Deore XT 12-Gang.','price'=>4499.00,'sale_price'=>3899.00,'bike_type'=>'E-MTB Tout-suspendu','wheel_size'=>'29"','frame_material'=>'Aluminium 6061','number_of_speeds'=>'12 vitesses Shimano Deore','suspension_type'=>'Fox 36 Rhythm 150mm / Fox Float DPS 150mm','brake_style'=>'Hydraulique Shimano Deore XT 4 pistons','power_source'=>'Batterie Yamaha intégrée','motor_power'=>'Yamaha PW-X3 250W / 85Nm','battery_capacity'=>'630 Wh','max_speed'=>'25 km/h','max_range'=>'95 km mode Eco','charging_time'=>'4h','weight'=>'24,8 kg','warranty_type'=>'Garantie Haibike 2 ans','colors'=>['Noir','Vert','Bleu'],'imgs'=>[[$I['e1'],'Noir'],[$I['fs1'],'Vert'],[$I['e2'],'Bleu']],'sizes'=>'S,M,L,XL']);

        $add(['cat'=>'electrique','brand'=>'Orbea','name'=>'Orbea Rise LT M20 E-MTB Carbone Léger 19kg','name_de'=>'Orbea Rise LT M20 E-MTB Carbon Leicht 19kg','slug'=>'orbea-rise-lt-m20-emtb-carbone','description'=>'E-MTB carbone OMX ultra-léger 19kg avec Shimano EP8 RS 85Nm. Range Extender compatible. Sensations VTT pures avec l\'assistance en discrétion totale.','description_de'=>'Carbon OMX Ultraleicht E-MTB 19kg mit Shimano EP8 RS 85Nm. Range Extender kompatibel. Pures MTB-Erlebnis mit diskreter Unterstützung.','price'=>6499.00,'sale_price'=>null,'is_new'=>true,'is_featured'=>true,'bike_type'=>'E-MTB Léger Carbone','wheel_size'=>'29"','frame_material'=>'Carbone OMX','number_of_speeds'=>'12 vitesses Shimano Deore XT','suspension_type'=>'Fox 34 Float 130mm / Fox Float DPS 130mm','brake_style'=>'Hydraulique Shimano XT','power_source'=>'Batterie lithium-ion','motor_power'=>'Shimano EP8 RS 250W / 85Nm','battery_capacity'=>'360 Wh + Range Extender possible','max_speed'=>'25 km/h','max_range'=>'100 km avec Range Extender','charging_time'=>'2h30','weight'=>'19,5 kg','warranty_type'=>'Garantie Orbea 5 ans','colors'=>['Bleu','Vert','Noir'],'imgs'=>[[$I['e2'],'Bleu'],[$I['fs1'],'Vert'],[$I['e1'],'Noir']],'sizes'=>'XS,S,M,L,XL']);

        $add(['cat'=>'electrique','brand'=>'Moustache','name'=>'Moustache Samedi 28.7 Open E-Bike Français','name_de'=>'Moustache Samedi 28.7 Open E-Bike Französisch','slug'=>'moustache-samedi-28-7-open-epinal','description'=>'E-Bike trekking fabriqué à Épinal (France). Bosch Performance CX 85Nm, batterie 625Wh. Shimano Deore 11V. Le fleuron du savoir-faire français en e-bike.','description_de'=>'E-Trekking aus Épinal (Frankreich) gefertigt. Bosch Performance CX 85Nm, 625Wh Akku. Shimano Deore 11-Gang.','price'=>3999.00,'sale_price'=>null,'is_new'=>true,'bike_type'=>'E-Trekking Français','wheel_size'=>'28"','frame_material'=>'Aluminium Moustache','number_of_speeds'=>'11 vitesses Shimano Deore','suspension_type'=>'Fourche suspendue 63mm','brake_style'=>'Disque hydraulique Shimano Deore','power_source'=>'Batterie Bosch intégrée','motor_power'=>'Bosch Performance CX 250W / 85Nm','battery_capacity'=>'625 Wh','max_speed'=>'25 km/h','max_range'=>'120 km mode Eco','charging_time'=>'4h30','weight'=>'25,4 kg','warranty_type'=>'Garantie Moustache 2 ans + Bosch 2 ans','colors'=>['Vert','Gris','Noir'],'imgs'=>[[$I['e2'],'Vert'],[$I['e1'],'Gris'],[$I['v1'],'Noir']],'sizes'=>'40,44,48,52,56']);

        foreach([
            ['Cannondale','Cannondale Moterra Neo Carbon 1 E-MTB Bosch Gen4','cannondale-moterra-neo-carbon-bosch-gen4','E-MTB carbone BallisTec Bosch Performance CX Gen4 85Nm, batterie 630Wh. Fox 38 Factory 150mm. Le summum de Cannondale.',7499.00,null,'e1','e2'],
            ['BMC','BMC Roadmachine AMP ONE E-Route Fazua Carbone','bmc-roadmachine-amp-one-fazua','E-Route carbone ACE Fazua Ride 60 250W/60Nm, batterie 430Wh amovible. Shimano Ultegra Di2. L\'e-route suisse ultime.',8499.00,null,'e1','r1'],
            ['Gazelle','Gazelle Ultimate T10 HMB E-Trekking Hollandais','gazelle-ultimate-t10-hmb-trekking','E-Trekking hollandais Bosch Performance Line Speed 65Nm, batterie 750Wh. Enviolo 10V continu. Jusqu\'à 140km.',4299.00,3799.00,'e2','v1'],
            ['Giant','Giant Reign E+ 1 Pro E-Enduro 160mm Carbone','giant-reign-e-plus-1-pro-enduro','E-Enduro carbone 160mm SyncDrive Pro2 85Nm, EnergyPak 600Wh. Fox 38 Factory. L\'enduro électrique de référence.',6499.00,null,'e1','fs1'],
        ] as [$brand,$name,$slug,$desc,$price,$sale,$i1,$i2]) {
            $add(['cat'=>'electrique','brand'=>$brand,'name'=>$name,'name_de'=>$name,'slug'=>$slug,'description'=>$desc,'description_de'=>$desc,'price'=>$price,'sale_price'=>$sale,'bike_type'=>'E-Bike','wheel_size'=>'29"','frame_material'=>'Aluminium/Carbone','number_of_speeds'=>'12 vitesses','suspension_type'=>'Suspendu','brake_style'=>'Disque hydraulique','power_source'=>'Batterie lithium-ion','motor_power'=>'Bosch Performance CX 250W / 85Nm','battery_capacity'=>'625 Wh','max_speed'=>'25 km/h','max_range'=>'100 km mode Eco','charging_time'=>'4h','weight'=>'25 kg','warranty_type'=>'Garantie 2 ans','colors'=>['Noir','Gris'],'imgs'=>[[$I[$i1],'Noir'],[$I[$i2],'Gris']],'sizes'=>'S,M,L,XL']);
        }

        // ════ BMX ═════════════════════════════════════════════════
        foreach([
            ['Mongoose','Mongoose Legion L60 20" Freestyle Acier','mongoose-legion-l60-20-freestyle','BMX freestyle acier Hi-Ten robuste. Parfait pour les riders intermédiaires au skatepark et dans la rue.',399.00,329.00],
            ['Wethepeople','Wethepeople Crysis 20" Race Aluminium','wethepeople-crysis-20-race-alu','BMX race aluminium 6061 T6 ultra-léger. Conçu pour la compétition sur piste.',699.00,null],
            ['Colony','Colony Apprentice 20" Freestyle Australien','colony-apprentice-20-freestyle','BMX freestyle australien robuste et abordable. Cadre Hi-Ten pour encaisser tous les tricks.',449.00,369.00],
            ['Subrosa','Subrosa Salvador Park 20" Chromoly','subrosa-salvador-park-20-chromoly','BMX park Chromoly léger. Géométrie optimisée pour les bowls, rampes et parcs.',599.00,null],
            ['GT','GT Performer Heritage 20.5" Chromoly','gt-performer-heritage-205','BMX freestyle iconique Chromoly. La légende du freestyle depuis 1979. Intemporel.',799.00,699.00],
            ['Stolen','Stolen Casino XL 20" Street Acier','stolen-casino-xl-20-street','BMX street acier Tibo Heat Treated. Taillé pour le street et les obstacles urbains.',549.00,null],
            ['Haro','Haro Lineage Team 20.5" Race','haro-lineage-team-205-race','BMX race Chromoly 4130 Hi-Ten. Performance et légèreté pour les compétitions sur piste.',649.00,null],
            ['Sunday','Sunday Primer Park 20" Chromoly','sunday-primer-park-20-chromoly','BMX park Chromoly 4130 multi-butted. Design épuré et géométrie précise pour le parc.',499.00,null],
        ] as [$brand,$name,$slug,$desc,$price,$sale]) {
            $add(['cat'=>'bmx','brand'=>$brand,'name'=>$name,'name_de'=>$name,'slug'=>$slug,'description'=>$desc,'description_de'=>$desc,'price'=>$price,'sale_price'=>$sale,'bike_type'=>'BMX','wheel_size'=>'20"','frame_material'=>'Acier/Aluminium','number_of_speeds'=>'1 vitesse','suspension_type'=>'Rigide','brake_style'=>'Patins V-Brake','weight'=>'11 kg','warranty_type'=>'Garantie 1 an','colors'=>['Noir','Blanc','Rouge'],'imgs'=>[[$I['b1'],'Noir'],[$I['h1'],'Blanc'],[$I['h3'],'Rouge']],'sizes'=>'Taille unique']);
        }

        // ════ ENFANT ══════════════════════════════════════════════
        $add(['cat'=>'enfant','brand'=>'Trek','name'=>'Trek Precaliber 20" 7 Vitesses Enfant 6-10 ans','name_de'=>'Trek Precaliber 20" 7 Gang Kind 6-10 Jahre','slug'=>'trek-precaliber-20-7v-enfant-6-10','description'=>'Vélo enfant 6-10 ans avec transmission 7V Shimano et freins ajustables. Cadre aluminium alpha léger. Grandit avec l\'enfant grâce aux réglages adaptés.','description_de'=>'Kinderrad 6-10 Jahre mit 7-Gang Shimano und anpassbaren Bremsen. Leichter Alpha Aluminiumrahmen.','price'=>499.00,'sale_price'=>449.00,'bike_type'=>'Vélo Enfant 20"','wheel_size'=>'20"','age_range'=>'6 – 10 ans','frame_material'=>'Aluminium Alpha (Trek)','number_of_speeds'=>'7 vitesses Shimano','suspension_type'=>'Rigide','brake_style'=>'Patins ajustables avant/arrière','weight'=>'9,3 kg','max_load'=>'50 kg','warranty_type'=>'Garantie Trek à vie cadre','colors'=>['Rose','Bleu','Vert','Noir'],'imgs'=>[[$I['k1'],'Rose'],[$I['h2'],'Bleu'],[$I['fs1'],'Vert'],[$I['h1'],'Noir']],'sizes'=>'Taille unique']);

        $add(['cat'=>'enfant','brand'=>'woom','name'=>'woom 4 Vélo Enfant 20" Ultra-Léger 6,9kg','name_de'=>'woom 4 Kinderfahrrad 20" Ultraleicht 6,9kg','slug'=>'woom-4-velo-enfant-20-ultra-leger','description'=>'Le vélo enfant autrichien légendaire 6-9 ans. Ultra-léger 6,9kg avec composants spécifiquement conçus pour les enfants. Mondialement reconnu comme le meilleur.','description_de'=>'Das legendäre österreichische Kinderfahrrad 6-9 Jahre. Ultraleicht 6,9kg mit kinderspezifisch entwickelten Komponenten. Weltweit als das Beste anerkannt.','price'=>449.00,'sale_price'=>null,'is_featured'=>true,'bike_type'=>'Vélo Enfant Premium','wheel_size'=>'20"','age_range'=>'6 – 9 ans','frame_material'=>'Aluminium ultra-léger woom','number_of_speeds'=>'7 vitesses Shimano','suspension_type'=>'Rigide','brake_style'=>'Patins spécial enfant (petites mains)','weight'=>'6,9 kg','max_load'=>'50 kg','warranty_type'=>'Garantie woom 2 ans','colors'=>['Orange','Bleu','Rouge','Vert'],'imgs'=>[[$I['k1'],'Orange'],[$I['h2'],'Bleu'],[$I['h3'],'Rouge'],[$I['fs1'],'Vert']],'sizes'=>'Taille unique']);

        $add(['cat'=>'enfant','brand'=>'woom','name'=>'woom 5 Vélo Enfant 24" Trail 8-11 ans','name_de'=>'woom 5 Kinderfahrrad 24" Trail 8-11 Jahre','slug'=>'woom-5-velo-enfant-24-trail','description'=>'Vélo enfant 8-11 ans ultra-léger 7,6kg avec 8 vitesses Shimano. Composants adaptés aux petites mains. La référence autrichienne pour les enfants actifs.','description_de'=>'Kinderfahrrad 8-11 Jahre Ultraleicht 7,6kg mit 8-Gang Shimano. Kleine-Hände-angepasste Komponenten.','price'=>499.00,'sale_price'=>null,'bike_type'=>'Vélo Enfant 24"','wheel_size'=>'24"','age_range'=>'8 – 11 ans','frame_material'=>'Aluminium ultra-léger woom','number_of_speeds'=>'8 vitesses Shimano','suspension_type'=>'Rigide','brake_style'=>'Patins spécial enfant','weight'=>'7,6 kg','max_load'=>'60 kg','warranty_type'=>'Garantie woom 2 ans','colors'=>['Orange','Bleu','Rouge','Vert','Blanc'],'imgs'=>[[$I['k1'],'Orange'],[$I['h2'],'Bleu'],[$I['h3'],'Rouge'],[$I['fs1'],'Vert'],[$I['tr1'],'Blanc']],'sizes'=>'Taille unique']);

        $add(['cat'=>'enfant','brand'=>'Scamp','name'=>'Scamp TallFox VTT Enfant 24" Semi-Rigide','name_de'=>'Scamp TallFox Kinder-MTB 24" Hardtail','slug'=>'scamp-tallfox-vtt-enfant-24-semi','description'=>'VTT enfant 8-13 ans avec fourche suspendue 50mm et composants Shimano Tourney. Un vrai VTT pour les jeunes riders en herbe qui veulent progresser.','description_de'=>'Kinder-MTB 8-13 Jahre mit 50mm Federgabel und Shimano Tourney. Ein echtes MTB für junge aufstrebende Fahrer.','price'=>599.00,'sale_price'=>null,'is_new'=>true,'bike_type'=>'VTT Enfant Hardtail','wheel_size'=>'24"','age_range'=>'8 – 13 ans','frame_material'=>'Aluminium 6061','number_of_speeds'=>'7 vitesses Shimano Tourney','suspension_type'=>'Fourche suspendue 50mm','brake_style'=>'Disque mécanique avant / V-Brake arrière','weight'=>'10,5 kg','max_load'=>'65 kg','warranty_type'=>'Garantie 2 ans','colors'=>['Blanc','Bleu','Rouge'],'imgs'=>[[$I['k1'],'Blanc'],[$I['h2'],'Bleu'],[$I['h3'],'Rouge']],'sizes'=>'Taille unique']);

        $add(['cat'=>'enfant','brand'=>'Puky','name'=>'Puky LR Ride 12" Draisienne 2-5 ans','name_de'=>'Puky LR Ride 12" Laufrad 2-5 Jahre','slug'=>'puky-lr-ride-12-draisienne-2-5-ans','description'=>'Draisienne premium 2-5 ans avec guidon et selle réglables. Frein à main arrière. Apprend l\'équilibre aux tout-petits naturellement. La référence allemande.','description_de'=>'Premium Laufrad 2-5 Jahre mit verstellbarem Lenker und Sattel. Hinterradbremse. Lehrt Kleinkinder natürlich Gleichgewicht.','price'=>149.00,'sale_price'=>129.00,'bike_type'=>'Draisienne Premium','wheel_size'=>'12"','age_range'=>'2 – 5 ans','frame_material'=>'Acier (Puky)','number_of_speeds'=>'Sans vitesses','suspension_type'=>'Rigide','brake_style'=>'Frein à main arrière','weight'=>'3,5 kg','max_load'=>'25 kg','warranty_type'=>'Garantie Puky 2 ans','assembly_required'=>true,'colors'=>['Bleu','Rose','Rouge','Vert'],'imgs'=>[[$I['k1'],'Bleu'],[$I['h2'],'Rose'],[$I['h3'],'Rouge'],[$I['fs1'],'Vert']],'sizes'=>'Taille unique']);

        foreach([
            ['Frog Bikes','Frog 70 Vélo Enfant 26" Ultra-Léger Britannique','frog-bikes-70-26-leger','Vélo enfant britannique 10-14 ans ultra-léger 8,6kg. Conçu pour que les enfants progressent rapidement.',649.00,549.00,'9 – 14 ans'],
            ['Islabikes','Islabikes Beinn 20 Small Premium Britannique','islabikes-beinn-20-small-premium','Vélo enfant britannique premium 5-8 ans. Ultra-léger 6,2kg avec composants entièrement adaptés.',399.00,null,'5 – 8 ans'],
            ['Orbea','Orbea MX 24 XC VTT Enfant Premium Espagnol','orbea-mx-24-xc-vtt-enfant','VTT enfant espagnol premium 9-13 ans fourche suspendue Shimano Altus 8V. Le vrai VTT pour les jeunes.',549.00,489.00,'9 – 13 ans'],
            ['Trek','Trek Marlin 4 24" Junior Hardtail','trek-marlin-4-24-junior-hardtail','VTT hardtail junior 10-14 ans avec fourche suspendue et freins disque hydrauliques. Pour les jeunes riders exigeants.',599.00,null,'10 – 14 ans'],
            ['Specialized','Specialized Riprock 20" Enfant Pneus Larges','specialized-riprock-20-pneus-larges','Vélo enfant pneus 20×2,3" pour plus d\'adhérence. Idéal pour apprendre le trail en toute sécurité.',449.00,null,'6 – 10 ans'],
        ] as [$brand,$name,$slug,$desc,$price,$sale,$age]) {
            $add(['cat'=>'enfant','brand'=>$brand,'name'=>$name,'name_de'=>$name,'slug'=>$slug,'description'=>$desc,'description_de'=>$desc,'price'=>$price,'sale_price'=>$sale,'bike_type'=>'Vélo Enfant','wheel_size'=>'20-26"','age_range'=>$age,'frame_material'=>'Aluminium','number_of_speeds'=>'7-8 vitesses','suspension_type'=>'Rigide','brake_style'=>'Patins/Disque','weight'=>'8 kg','max_load'=>'60 kg','warranty_type'=>'Garantie 2 ans','colors'=>['Bleu','Rose','Vert','Noir'],'imgs'=>[[$I['k1'],'Bleu'],[$I['h2'],'Rose'],[$I['fs1'],'Vert'],[$I['h1'],'Noir']],'sizes'=>'Taille unique']);
        }

        // ════ RECONDITIONNÉ ═══════════════════════════════════════
        foreach([
            ['Trek','Trek Marlin 5 29" Reconditionné Grade A Certifié','trek-marlin-5-29-recon-grade-a','VTT hardtail 29" entièrement révisé Grade A. Aucun défaut visible. Transmission et freins en parfait état. Certifié technicien.',549.00,'Grade A - Comme neuf'],
            ['Specialized','Specialized Stumpjumper 29" Reconditionné A Carbone','specialized-stumpjumper-29-recon-a','Trail bike tout-suspendu 29" révisé Grade A. SRAM et freins hydrauliques parfaits. Occasion rare à saisir.',1799.00,'Grade A - Comme neuf'],
            ['Trek','Trek FX 3 Disc Reconditionné Grade B Quelques Rayures','trek-fx3-disc-recon-grade-b','Vélo fitness quelques légères rayures esthétiques. Tous composants vérifiés, pièces d\'usure remplacées. Fonctionnellement parfait.',449.00,'Grade B - Très bon état'],
            ['Giant','Giant Explore E+ 1 Pro E-Bike Reconditionné Batterie 92%','giant-explore-e-plus-1-recon-batterie-92','E-Bike trekking reconditionné. Batterie 92% capacité d\'origine. Moteur et électronique parfaits. Grade B.',1899.00,'Grade B - Batterie 92%'],
            ['Cannondale','Cannondale SuperSix EVO Carbon Route Reconditionné A','cannondale-supersix-evo-recon-a-carbone','Vélo de route carbone Grade A. Shimano Ultegra révisé intégralement. Cadre carbone intact sans défaut structurel.',1999.00,'Grade A - Comme neuf'],
            ['Trek','Trek Checkpoint ALR 5 Gravel Reconditionné Grade B','trek-checkpoint-alr5-gravel-recon-b','Gravel bike aluminium Grade B. Quelques rayures. Groupe Shimano GRX révisé. Excellent rapport qualité-prix gravel.',799.00,'Grade B - Très bon état'],
            ['Cube','Cube Stereo 140 HPC Trail Reconditionné Grade B','cube-stereo-140-hpc-recon-grade-b','Trail bike tout-suspendu carbone Grade B. Suspension révisée, transmission SRAM fonctionnelle. Occasion carbone à prix cassé.',2499.00,'Grade B - Très bon état'],
            ['Trek','Trek Powerfly FS 5 E-MTB Reconditionné Batterie 95%','trek-powerfly-fs5-emtb-recon-95','VTT électrique tout-suspendu Grade A. Batterie 95% capacité. Moteur Bosch révisé et certifié. L\'e-MTB occasion premium.',3499.00,'Grade A - Batterie 95%'],
        ] as [$brand,$name,$slug,$desc,$price,$grade]) {
            $add(['cat'=>'reconditionne','brand'=>$brand,'name'=>$name,'name_de'=>$name,'slug'=>$slug,'description'=>$desc.' '.$grade.'. Garantie reconditionnement 6 mois pièces et main d\'œuvre.','description_de'=>$desc.' '.$grade.'. 6 Monate Wiederaufbereitungsgarantie auf Teile und Arbeit.','price'=>$price,'sale_price'=>null,'bike_type'=>'Reconditionné','wheel_size'=>'Selon modèle','frame_material'=>'Selon modèle original','number_of_speeds'=>'Selon modèle','suspension_type'=>'Selon modèle','brake_style'=>'Hydraulique (révisé)','weight'=>'Variable','warranty_type'=>'Garantie reconditionnement 6 mois','colors'=>['Coloris d\'origine'],'imgs'=>[[$I['s1'],'Coloris d\'origine'],[$I['s2'],'Coloris d\'origine']],'sizes'=>'Selon modèle']);
        }

        $total = Product::count();
        $imgs  = ProductImage::count();
        $cats  = Category::count();

        $this->command->info('');
        $this->command->info('╔══════════════════════════════════════════╗');
        $this->command->info('║  ✅  MegaBikeSeeder terminé !            ║');
        $this->command->info('╠══════════════════════════════════════════╣');
        $this->command->info("║  📂  {$cats} catégories                       ║");
        $this->command->info("║  🚲  {$total} produits vélos réels          ║");
        $this->command->info("║  🖼   {$imgs} images (Unsplash vélos)      ║");
        $this->command->info('╚══════════════════════════════════════════╝');
    }
}
